{{{film}}}
#+date: 338; 12025 H.E. 2131 PST
* Angel's Egg
Walking blind into the movie theater---I must confess---I was not ready for
what played on the screen. Having just finished worked and hurriedly arriving to
my local AMC, so I could rendezvous in time with my friends, the mental and
emotional space that /Angel's Egg/ required in general, and that specific night,
was not something I could easily extend. It is one of those experiences that
feel richer in retrospect. I hear some call it ``/Type-II fun/,'' where the
enjoyment of the event is intensified through memories, rather than whatever was
felt in the duration of.

Being dubbed as ``the guy that watches them old boring movies'' against my own
volition, /Angel's Egg/'s pace and progression had made me itchy to move and do
something else, like those kids in social studies, where they lock them up in a
room with some form entertainment and then with none, seeing them spinning in
chairs and electrocuting themselves when there are no stimuli. I was that kid.

The art is unique and almost every frame could be hung on a wall, where that one
friend of yours would ask you, ``What anime is that from?'' And sure, the story
offered bits of the lore and its message its trying to convey through fish that
are no longer there, the men that fight shadows; our male antagonist that
arrives on some post-nuclear holocaust kind of a vehicle---the world had reached
its end. Only this girl's egg, representing nature's attempt to revitalize
itself is brutally crushed and destroyed, because /War Never Changes/. With a
heavy implication that we will fight each other, and continue fighting each
other, even in times when there is nothing left to fight for.

The message is great, the delivery though is something I wish to re-evaluate
within the next 5 years, after I had felt that a sufficiently long enough
cooldown period had lapsed. Similar to what I thought in [[/blogs/against-interpretation][Against Interpretation]],
/Angel's Egg/ relies heavily on after-the-fact analysis, even though the art style
was delightful, it did not last long enough to help the inertia of the story,
which dragged on for my taste. Hopefully, I can change my mind in the future.

*P.S.* My absolute favorite shot was at the very end with the big eye, with nature
longing for its return, having an army of Greek-looking statues in full elegant
armor praying with two hands, fingers interlocking. I keep thinking about it.

{{{three}}}
