#+setupfile: ../00_film_skipthis.org
#+date: 21; 12024 H.E. 2300
* Mishima: A Life in Four Chapters
I felt so frustrated with myself. Paul Schrader, what have you done. How can one
film such a unique, thorough, and breathtaking biographical picture of someone's
life, where someone is such a complex and layered figure that unraveling it
would seem to be an insurmountable mountain for anyone; especially when it means
respectfully and faithfully portraying the culture and soul of a nation that is
a secret of its own to all the outsiders.

As Susan Sontag used to say, [[https://sandyuraz.com/blogs/against-interpretation/][/Against Interpretation/]], I'll focus on the form. The
visuals are simply—stunning. Similarly to one of my all-time favorites in story
telling, /Solaris/ by Stanislaw Lem, Paul Schrader depicts /Mishima: A Life in Four
Chapters/, in four chapters (heh), in a tripartite. First, a political thriller
going through Mishima's last day, November 25, 1970. Second, a series of
flashbacks to his youth. Third, an over-dramatization of Mishima's finest works
in the flesh. The perfect combination of reality, memory, and imagination. Let
me speak a bit more about the imagination part.

The Criterion booklet that came with the box has an essay written by the film's
production designer, Eiko Ishioka, and let me say—I don't think I have ever seen
anything like this ever put on film. Maybe Apocalypse Now's poster, oh wait,
that was also her. Dream-like sets, very different compared to the nature of
David Lynch's [[https://sandyuraz.com/drama/blue-velvet/][sets]], in the sense that Eiko Ishioka herself put the best, ``It
would be like the sets themselves were characters, as though they were actors,
and they would challenge the real actors.'' There is a grand actor in the
background, always third-wheeling, aggressively, and in such a way that is truly
overwhelming. Just like that acolyte burning the pavilion, as it was too
beautiful, therefore, it was insulting to the human nature.

Circling back, as the ye old tradition states—I felt angry with myself. I was
sitting here, in the night, watching the film, and as Mishima contemplated the
inadequacy of even the most articulate words describe the nature, the world,
which was never meant, and could never be described in words—it calls for the
combination of art and action. It called out to me something so close to Oscar
Wilde, but to a further, riskier, radical, ultranationalistic way, which is by
all means and definitions, reactionary, yet has that warped beauty, a
Byron-esque essence. Where is the line at which the artist becomes the art?

There was so much that when I was done, I simply turned off the lights and went
to bed. Didn't write, as I was too stumped to come out with anything coherent
and structured. The clash of self-creation and self-destruction, which spurred
within the theater of gore, blood, masochism, honor, guilt, and pride, have all
resulted in a tense, ultimately, tragic climax, of Yukio Mishima becoming ``Yukio
Mishima.'' The grande finale. As much as I myself disagreed deeply with the
tactics, reactionary movements, the especially dangerous ones, I could not avoid
observing in awe at how far some would go to realize their ideas, or at the very
least, do the unthinkable to explore them as far as they can, till death do them
apart.

I remember that in university literature courses, I always liked the idea of a
duel, this ``glory'' that it entails. As much we look down upon those (usually,
fatal) acts, calling them downright barbaric, sitting on our high thrones of
retroactive judgement, ``this all could be avoided if he did X,'' all of that
happened in human history happened because of the factors of the time, because
those people existed, and some, even took on the radical idea of
living. Stepping down from the ``high and mighty'' pedestal we built for
ourselves; training ourselves out of the awful ``we are smarter and better than
the men before us'' attitude; we might learn a thing or two about the very core
of the human spirit, which resides so deep and hidden within us that in the
world filled with shallow thoughts and even shallower minds we are adopting;
where the very action of venturing beyond is no longer considered
``over-dramatic,'' but rational to the very notion that makes us human.

-----

*January 3rd, 2025* \
Unsurprisingly to me, this continues to be one of my all-time favorites. The
everything in this, from the story, composition, structure, sets, soundtrack,
actors, the making of, everything is made to perfection. It was the last day we
were visiting family, so I'm happy this is what we decided on—everybody was sold
when I said "this is my personal favorite."

There isn't much that I can add when writing about Mishima. I am simply not
there yet. The thoughts I have are too abstract to be put into words. And truly,
you reach such a point, when words are no longer enough and only action can
convey the meaning. The film captures such a deep string that I can't really
shake it off nor come to peace with what it provokes within me.

Form and content come together into a fiery helix of the spirit of the human
soul. You will read me say this about very few films and this is one of
them. This time, I watched more of the original interviews with Mishima from
1960s and documentaries about how the movie was made. No spoilers, but I do
encourage watching what Criterion has to offer.

1st review: [[https://boxd.it/5FgPKb][https://boxd.it/5FgPKb]]

