{{{film}}}
#+date: 53; 12025 H.E. 2333
* 8½
Ahead of its time. I think the magic behind /8½/ lies in knowing the whole story
behind making of /8½/ and if we are straight honest out of the gate, what is /8½/
but a film about making a film, where the film being made is /8½/ itself? That is
Federico Fellini's /8½/. The stories behind on how it was made; how Federico
Fellini was behind on making a film and decided to make a film exactly about
that; the never finished movie of his---all of this trivia is fascinating to
learn about.

The film itself has something special and magical in it, but I may not be able
to grasp it as much as I would have wanted to because I'm not a director or
simply not in the state of the mind to take it in---it was also 5am. Not to
make it sound shallow, as I appreciated and adored /8½/ for the technical aspects,
for how it made me feel, for how absolutely drop-dead gorgeous and stunning
Marcello Mastroianni looks playing as Guido Anselmi. Most definitely, one of the
most influential movies of all time---it will take me a bit of time to develop
more of a taste for it to properly appreciate it. Give me some time.

I just want to breathe in the entirety of it like an inhaler.

{{{four}}}
