#+setupfile: ../00_sasakura_skipthis.org
#+date: 249; 12025 H.E. 2313
* Old Pal 🍎

{{{pics(old-pal.jpg)}}}

While watching /The Hero X/ this Tuesday night, the boys had a healthy dose of
four negronis, which prompted us to indulge ourselves in three dinners. It being
one of the most frequently ordered cocktails in the world, if not topping the
charts---it's really easy to see why. Incredibly inoffensive, tasty, and
straight-forward to make with any ingredients resembling the Big Three. I like
to think the recent Mads Mikkelsen ad for /Campari/ helped the good cause.

Perusing my bible of cocktails, aka Adrienne Spillman's /Spirited/, I found they
devoted up to a dozen pages to just all kinds of negroni riffs and variations
concocted by professional bartenders living their craft any time between late
1800s and today. It was nice to see some familiar names, one of them
/Boulevardier/, but even more so, an /Old Pal/, which is a rye variation of it. It's
been a while since I posted anything here, let's get it out of the way.

Here it is, a /delicious/ negroni with a deeper sense of sweet-but-not-sweet
thanks to its rye mainliner.

- 1 ounce of /Old Forester 100 Proof Rye Whiskey/
- 1 ounce of /Dolin Sweet Vermouth/
- 1 ounce of /Contratto Bitter/

Build all in a neat or rocks glass over a large chunk of ice, stirring for about
10 seconds or to taste, and serving with a slice of orange. I prefer /Contratto
Bitter/ to /Campari/ for the sole reason of the former not using Red#40 as a cheap
way of getting the extreme rouge.
