* You make your own reality 👒

101; 12022 H.E.

``Hey you, listen, /snap back into reality/'', someone might have told you at some
point in your life. I want to understand, what does it mean? What reality are
you talking about, my friend? It is absolutely crazy to me that select
individuals (many more, actually) dare to dictate one or another how to live by
boxing them into their worldview.

#+drop_cap
There is this misconception, a crucial misunderstanding that is happening, where
people seem to think that this way is /the right way to spend time and live/ while
/that one over there is not/. Similar to the question I asked in [[https://sandyuraz.com/blogs/living/][``Living
Consciously'']], who made those criteria? Sure, society and its constructs evolved
one way or another, however, it is not ironclad; simply a product of its time
and circumstances.

I am writing this out of frustration I had from talking to other people about my
favorite movies and shows. Of course, I do not expect everyone to like the same
things that I like, however, what I do not expect is for someone to start
imposing their views, trying to convince you that what you love and adore *is
bad*. Keep in mind that this is different from a healthy discussion or
argumentation.

It is only human for me, personally, to get a little disheartened if another
person (especially a friend of mine) just keeps going down on what I hold so
dearly, as if having no care for my feelings and uneasiness at the moment,
whilst still knowing all of it. I am too considerate and delicate to make a
snarky remark or get back at something of theirs, it's not fun.

This is in the same vein of ridicule that comes about reading ``juvenile
fiction'' or ``this anime is too [[https://en.wikipedia.org/wiki/Shōnen_manga][/shouneny/]]'', which sounds pejorative, to say
the least, as if to shame me for liking it just for the way it is. How many
friendships and relationships have collapsed because someone said with a judging
tone in their voice, ``oh, you like /this/?''

You can still critique whatever you don't like or rubs you the wrong way; do it
constructively and logically. Leave the raw and uncontrolled emotions of yours
out of it, so you are not stumbling into other people's feelings' territories
spraying dirt all over them. We can try to put ourselves in their shoes to see
where they are coming from.

#+drop_cap
The reality and world that surrounds you are exactly what you make of it. Every
interaction you have, every path you take, and every food you eat; all
contribute to your perception of what is around you. Two identical physical
worlds can be interpreted as completely different realities, to the point that
one might not even be able to imagine the very existence of the second one.

What you think of the world, of a movie you watched, of a coffee you had in that
cafe can and will differ from that other person. That is expected and good. You
just live in your own Universes, so give each other space and a chance to
experience life the way you want, leaving all that mud and filth out of it. We
are only given one tenure at life, let us spend it on living.
