* Literate sorting visualizer 😎
I must disclose that I have been infected by the dream that
[[https://www-cs-faculty.stanford.edu/~knuth/][Donald E. Knuth]] wanted to give us with the [[http://www.literateprogramming.com][Literate Programming]]
paradigm. Many decades have passed since his original papers and the [[https://www-cs-faculty.stanford.edu/~knuth/lp.html][book]]
that archives all of those papers into a nice piece of literature.

I would say that for me, Literate Programming is the way that we should think
about writing software and code. Such that we ought to address our programs
to people and not to machines. Programming itself should be regarded as a
process of writing essays, therefore considered as a process of creating
/works of literature/, which are meant to be read. (the book above says is
better)

Many aspiring computer scientists and programmers have the audacity to say
that one can be a good software developer without knowing how to write
properly or do math rigorously. Both of those claims to me are quite
outrageous. Those are the foundations of our field and what we are.

Below is a link to a simple terminal-based sorting algorithm visualizer I
wrote in [[https://www-cs-faculty.stanford.edu/~knuth/cweb.html][CWEB]]. Writing programs and explaining algorithms to people rather
than to computers is actually fun! One can say, it's very much enlightening.

-> [[https://github.com/thecsw/literate-bubble-sort][Go to the literate sorting repository]]
