#+options: draft:t preview:playlist_21.jpg preview-height:1182 preview-width:1862
* My playlist #21 🤠

Hah, look at this couch. Almost midnight, I am in a dazed melancholic feel. I
suppose that's what /Tinker Tailor Soldier Spy/ would do to you. What do I want?
What do I need? What do I *deserve*?

Oh yeah, how about that /My playlist #21/? hi, zuul🤠

** /Them Changes/ by Thundercat

{{{spotify_embed(them-changes.toml)}}}

I'm in a small, funky bar, somewhere midtown. I don't know how I ended up. Did I
drink too much? Where are my friends? Why am I alone? I have so many questions
and only one answer. But that one answer is enough for me. *I'm just jamming*. So
I'm doing pretty good. This is a solid jam.

** /Show Me the Right/ by NEIL FRANCES

{{{spotify_embed(show-me-the-right.toml)}}}

Oooh, a nice pop. Feels like I need a refreshing, cool drink (definitely pour
some alcohol in it), play it through a speaker, while I'm lounging on a
reclinable thingy near a pool. Of course with the sunscreen on and everything,
just living in that moment. It's one of those moments, when it's your immediate
surroundings and music make you go, ``Everything is alright.''

** /Doomsday/ by MF DOOM

{{{spotify_embed(doomsday.toml)}}}

Fire artist name, *MF DOOM*. Doo-doo-doo-doo-doo!. I had to re-listen to this a
couple of times with the lyrics on to catch what the meaning is. Apparently,
he's big. Hah, shows how little I'm acquianted with the world of rapping. The
line

#+begin_quote
``Ever since the womb 'til I'm back where my brother went\
That's what my tomb will say\
Right above my government, Dumile''
#+end_quote

kinda goes hard. The tune is
smooth, I like it a lot. I tried to read up more on the meaning, it's more about
how ''my word is my bond,''
[fn:: The wikipedia page with an interview
https://en.wikipedia.org/wiki/Doomsday_(MF_Doom_song)]
I can see it!

** /Coco Mango/ by MF DOOM

{{{spotify_embed(coco-mango-flofilz-remix.toml)}}}

Good opportunity to learn more about MF DOOM! I love these like 50s and 60s TV
ads, whatever trans atlantic voice bits used as base drops. Goes hard. Similar
thoughts like on the above! That last 20 seconds were groovy

** /Their13/ by JGrrey

{{{spotify_embed(theirs13.toml)}}}

Already love the opening. Kind of a bossa nova feeling with early 2000s, jazzy
feeling to it. Hmmmmmm. The lyrics are sweet!! I believe this is about
self-expression, finding yourself, coming of age? It's short and sweet. Or maybe
finding yourself and who you are when entering a romantic relationship?

** /Gorilla/ by Little Simz

{{{spotify_embed(gorilla.toml)}}}

That drawl she has at the end of some lines is pretty sick. It's an interesting
choice, which I like, to separate the song into section by using fanfares as the
separator. I like the revolutionary and standing-up-for-what-you-believe mood of
the song---break out and pierce through the expectations set. This line says it
all

#+begin_quote
``I'm cut with a different scissor\ 
From the same cloth as my dear ancestors''
#+end_quote

** /I Hate Everything/ by The Alchemist

{{{spotify_embed(i-hate-everything-feat-action-bronson.toml)}}}

Welcome back, fanfares! This one is kinda straightforward. Finding yourself.

/(I'm not impressed) (I hate everything)/

** /Self/ from noname

{{{spotify_embed(self.toml)}}}

That line reading goes slapping. Super short and based. Pretty clean and shoots
straight to the point. Gotta have that yin and yan.


** /Easter Sunday/ by Zelooperz

{{{spotify_embed(easter-sunday.toml)}}}

I think I'm yet to get used to this style of rapping---it's using tunes and
notes I'm not super familiar with, which is spinning my head a bit, but in a
good way. Can't really say what it's about yet... The backdrop rhythm is catchy!

** /kometostai.aintreallynootherwaytoputtitro/ by Knxwledge

{{{spotify_embed(kometostai-aintreallynootherwaytoputitro.toml)}}}

Love this aesthetic. And the cover is stylish too. That was a bit of a dreamy,
hallucinatory experience. Solid

** /Hold My Head/ by Kenny Beats

{{{spotify_embed(hold-my-head.toml)}}}

Their opening line is cool,

#+begin_quote
DON'T OVER THINK SHIT . COM
#+end_quote

amen 🙏 Now the song---it's alright, not really my style---too much happening at
the same time for muh brain to handle the tunes, but I can see the appeal. The
intermitten drops are good

** /Deceptacon/ by Le Tigre

{{{spotify_embed(deceptacon.toml)}}}

Kind of /le/ 80s style of a song. Ahhh, because it's like 80s, hard to say what it
reminds me of, but the whole genre. The rebellious, punk-ish, a little bit of
daft on top when it comes to the melody.

** /One Night with The Valet/ by Tennis

{{{spotify_embed(one-night-with-the-valet.toml)}}}

That's a charming title lol. Very... California? I can definitely imagine
playing this while riding across the Bay, seeing the palm trees, and a warm cali
sun, while we talk about whatever---this is a great mood setter for that occasion.

** /Charmed/ by Σtella

{{{spotify_embed(charmed.toml)}}}

Also a bit of a dreamy song... I think this would be a great selection to play
in the background somewhere between 8-10pm on a warm Saturday evening. While the
listeners share a nice glass of wine, drinks, snacks (love them jalapeno chips).

#+begin_quote
Cos now you're gone\
Far away\
Far away\
If you could\
Would you stay\
Would you stay\
...with me
#+end_quote

** /Je ne Te connais pas/ by Prototypes

{{{spotify_embed(je-ne-te-connais-pas.toml)}}}

Hi, I don't know you either, the French version of /The Strokes/. hah. Ah, it's
been a while since my high school French A2, but it definitely got that dog in
it, with boutique-esque lyrics, and the revolutionary spirit ✊

** /1 4 2/ by Inner Wave

{{{spotify_embed(1-4-2.toml)}}}

I've got a problem too. If only I could show her. All the things I want to.

It's like... a romantic version of... something. The industrial-like filter and
synthesizer on top of the vocalist is so raw. The 70-80s Japanese-style album
cover with like gundam is /a e s t h e t i c s/.

Inner Wave isn't that big, interesting. Solid solid song. Has a whole story to
tell, with a lyric repetition, something made me think of like Daft Punk.

#+begin_quote
We fall in love and fall apart again\
We fall in love and fall apart again\
We fall in love and fall apart again\
We fall in love and fall apart again\
#+end_quote

** /Rockstar/ by N.E.R.D.

{{{spotify_embed(rockstar.toml)}}}

The cooler version of a N.E.E.T. Dam that started strong, just no dinner, and
straight to the line. Oh my, this is heavy, heavy on the ears and it dam knows
it well. Hmmmmmm. I'll confess, not really my type---it hits the melody a bit
too hard, it's like overwhelming lmao. Maybe if I listen to it more---I'll get
used to it, that's how it was with my starting into heavier metal and rock.

** /Rapp Snitch Knishes/ by MF DOOM

{{{spotify_embed(rapp-snitch-knishes-feat-mr-fantastik.toml)}}}

MF DOOM!!! Welcome back to the programming. Your style stays consistent. I don't
really know what's going on, but you are most certainly living up to your name
and I'm feeling it.

** /Rock Co.Kane Flow/ by De La Soul

{{{spotify_embed(rock-co-kane-flow-feat-mf-doom.toml)}}}

That beatttttttttttt. I see MF DOOM is also in it---I'm just here for the beats
and that rap flow. I guess maybe I'm just built... wrong? Or maybe lack of
something, it doesn't really connect with me, but I will listen through every
song in full before I form an opinion.

** /Put Your Records On/ by Ritt Momney

{{{spotify_embed(put-your-records-on.toml)}}}

Ritt Momney... why does that sound familiar? Oh my god, because it's [[https://en.wikipedia.org/wiki/Mitt_Romney][Mitt Romney]]
lmao. This is a nice change of pace from the rap-style to something more pop and
beat-sy. I don't really get it---is it a father seeing his daughter growing up,
becoming of age, and leaving for the wider world out there---to her own life. Or
is it a breakup in progress? The notion of, ``if you love her, let her go''? I'd
bet it's the former. And woah, the back accompaniement with the instrumental
keeps slamming harder and like... more... humongously as the song progresses.

** /Ridin Round/ by Kali Uchis

{{{spotify_embed(ridin-round.toml)}}}

Cool cover. Call me crazy, but I've never heard of Kali Uchis. I feel so
under-cultured and like I'm living under a rock, not knowing these huge artists
and spotify profiles. Are my tastes really that divergent? huh

This is a clean, like 2021-2023 style pop. The lyrics is also straight---u go girl

** /This Must Be The Place/ by Sure Sure

{{{spotify_embed(this-must-be-the-place.toml)}}}

OH YES! I FORGET WHERE THIS TUNE AND THE LYRICS STYLE IS FROM. It's from a super
popular song that I'm definitely sinning right now by not recalling. Good vibes
with this piece---perfect for a cool afternoon ride across town and just vibing.

** /Holywood Forever Cemetery Sings/ by Father John Misty

{{{spotify_embed(hollywood-forever-cemetery-sings.toml)}}}

Now, this... this is some combination of a title and artist's name.

/Jesus Christ, girl/. What ungodly things are they up to with weed, adderall, and
her American back at the cemetery 😳

** /L.E.S. Artistes/ by Santigold

{{{spotify_embed(l-e-s-artistes.toml)}}}

Don't have to say much, but it's not healthy eating that much
glitter. Especially with them getting outlawed for sale in Europe
[fn:: What To Know About Europe’s New ‘Glitter Ban’—As EU Cracks Down On Plastic
[[https://www.forbes.com/sites/maryroeloffs/2023/10/17/what-to-know-about-europes-new-glitter-ban-as-eu-cracks-down-on-plastic/?sh=1a6424e233ee][source]]] that's a crime i think now

** /Where Is My Mind?/ by Pixies

{{{spotify_embed(where-is-my-mind.toml)}}}

Hah! I know I'm cultured for at least 0.01% when I recognize this song. What
more could be said? I always had a weak spot for solo guitars. 

** /Smack a Bitch/ by Rico Nasty

{{{spotify_embed(smack-a-bitch.toml)}}}

Hmmmm, it's very specific for a specific mood. If you're there, you're there,
and it's gonna slap

** /Float On/ by Good Tiger

{{{spotify_embed(float-on.toml)}}}

First, /Le Tiger/, now, /Good Tiger/. Another classic, that ``AHHHHHH'' is iconic.

** /Fantasy/ by Eternity Forever

{{{spotify_embed(fantasy.toml)}}}

Sheeeeshh. Smooth opening. This might be one of my favorites with /Them Changes/
as an example---it's a sweet love song with a dog in it and the delivery.

#+begin_quote
I'll take you to the front row
#+end_quote

** /Covet/ by Basement

{{{spotify_embed(covet.toml)}}}

Oh yeah. Oh yeah. Gives off a bit more punk-ish /The Strokes/ vibes with early 00s
and maybe very late 90s. They'll be good Romeo and Juliet duo

** /Wasted Nun/ by Cherry Glazerr

{{{spotify_embed(wasted-nun.toml)}}}

Now this! This is a banger name, a /Wasted Nun/. I always loved contradictions
like those. Forgotten Gods, Sinful Nuns, etc. Nice song.

** /Jungle (Radio Edit)/ by Tash Sultana

{{{spotify_embed(jungle-radio-edit.toml)}}}

smewth pop. Maybe because it's explicitly says /(Radio Edit)/, but I feel as if I
would hear this on the radio on my way to school in the morning. Probably every
day too, because it's hitting the top charts, so every radio station feels as if
it's their sacred duty to replay the same song every day, every time lol

** /Jusfayu/ by KAMAUU

{{{spotify_embed(jusfayu-feat-no-wyld-lion-babe-remix.toml)}}}

yo, u know who this whole page is written for? jusfayu

** /Desperate/ by Kurt Travis

{{{spotify_embed(desperate.toml)}}}

spooky cover, this is good---maybe I'm getting worn off---the high pitch is a
bit much for me, but whenever that electric guitar solo just riffs it---oh yeah,
gimme more of that!

** /Artificial Red/ by Mad Season

{{{spotify_embed(artificial-red.toml)}}}

This is more of my style, I think. A slow burn rock, reminds me a bit of
/French Fries w Pepper/ by Morphine. This has a spunk, but then goes down, until
the next hit. I like this!

** /Mass Appeal/ by Gang Starr

{{{spotify_embed(mass-appeal.toml)}}}

Last but from least. This is like prime 90s---I remember seeing or hearing
something about it on [[https://en.wikipedia.org/wiki/Mass_Appeal_(song)][the grapevine]]. That distortian and replays in the
back vocals is so good. This is also probably on of my favs from the
playlist---it's crisp and knows exactly what it is (not to say others didn't)

** exeunt

I would also call this a ``High Octane'' playlist---really good to stimulate
your brain to the next gear, heh

I have much learning to do, master
