#+date: 23; 12023 H.E.

* On /Brothers Karamazov/ ☦️

23; 12023 H.E.

As more time passed since I first read /Brothers Karamazov/ (BK) by Fyodor
Dostoevsky, I realized more clearly how profoundly this novel impacted
me. Without all the exaggeration and even excluding the flowery language -- I
consider myself to be, if not radically, but consciously different people before
and after my journey with BK.

If we were talking and through some avenue of thoughts, we get myself to get
started on it; I won't stop talking for many hours if you let me. Instead of
endlessly holding people hostage listening to me going on the brilliance of
Dostoevsky and the intricacies of his /Brothers Karamazov/, I thought I would put
my thoughts down here. Not exactly ink on paper, but something nonetheless.

/Brothers Karamazov/ is a profoundly religious work. Imagine all the literature
world has ever written, crossing borders, races, and cultures. If I see it as a
big pile of everything together, BK stands there utterly alone from the
group. In all my arrogance, I would proclaim that nothing close to it has ever
been written -- it is in a whole league of its own, which makes it unfair for
any other work to be compared to /Brothers Karamazov/.

After finishing the book in over three weeks (the most turbulent and longest
three weeks of my life for many other reasons), I found peace within
myself. Somehow, many things that bothered and burned me from the inside about
relationships and worries discovered a way to resolve themselves. Not that I
forgot about them or consciously ignored the issues, but the brain rewired
itself to deal with regular pleasantries and unpleasantries of life in a new
way.

/Brothers Karamazov/ made me love God again. The brothers helped to find
forgiveness in me for other people and situations. Most importantly, forgiveness
for myself. I remember this distinct feeling after finishing the book -- ``I
will never read anything better than this.'' Of course, /never say never/;
however, this one is /my/ exception. This thought didn't trouble me either. I was
happy to know I reached this kind of literature and experienced it while alive.

It does not mean that I won't enjoy any other literature I come across in the
future or snarkily compare everything to BK -- no, no. *That* would defeat the
purpose of acquiring a taste for high literature. I will still enjoy reading any
other book and still do; I will critique and review anything I read by the
baseline that I feel is proper; however, deep down, I know that my limit has
been reached. Similarly, I know that I would never be able to write like
Dostoevsky. Even if I am ever as good as the smallest and tiniest sliver of his
early writings -- that part of me can retire fulfilled.
