#+options: draft:t
#+date: 50; 12023 H.E.
* In Pursuit of Happyness 🧸

Wake up in the morning to that god-awful alarm clock ringtone you set who knows
when. It's early enough, so you won't be late for work but too late to get a bit
more sleep. Go to work, come back home, too tired to do anything requiring too
much energy. ``No worries,'' you say to yourself, ``Better times will surely
come.'' Just one of the many cliches that hepled over the years, ``I just need
to save up this much'' or ``this is just a small obstacle, a hiccup -- my time
is yet to come.''

Saying this daily, almost as a lullaby helps to calm the
inquisitive and worried mind, more importantly, it brings some remedy for the
longing -- the longing for something greater, more noble, at the very least,
something meanniful. Until the moment those surface-level affirmations stop
working, the ``better'' times *better* come or what was all this wasted time and
potential for? Could I have done something differently? Can I do something
different now?
