#+latex_class: sandy-article
#+author: Sandy Urazayev
#+date: February 25th, 2026
#+email: sandy@sandyuraz.com
#+options: toc:nil email:t
#+title: The Death of the Art of Computer Science

#+begin_quote
/Written and delivered as a speech on February 25th, 2026, and left here, exactly as
is, for the future to keep it honest./
#+end_quote

When it comes to AI, I quite dislike it. You could even say hate it. On every
possible level. I find it vile to what it does to our minds, bodies, and how we
see and treat each other. It's fundamentally the single most influential
across-the-board technology we have ever discovered and decided to pursue
blindly.

Financially, it's prohibitively expensive for the regular person to use whether
through paying  for at the moment VC-subsidized subscriptions or acquiring the
hardware needed to run the LLMs locally at a fast enough inference speed that it
makes sense.

Environmentally, it's killing our forests, heating up the planet, the data
centers burn the land, violate the nature, poison our water, and in turn, also
have severely negative effects on our bodies for anyone nearby one of them.

Societally, it's a grifter's economy, where anybody with the smallest amount of
skillset and ample of free time is happy to abuse the technology to take
advantage of their fellow man. Number 1 usage of AI is for mental health, like
that is not already in crisis of in itself, and AI sycophantically supporting
everything you say is not good.

Ethically, it blurs the line for people between human-made and machine-made,
resulting in a never-ending slopification of all things we hold dear and that
had for tens of thousands of years made us human---art, music, painting, cartoon,
filmmaking, gaming. Verbatim regurgitation of copyrighted works. Displacement of
creative endeavors.

Professionally, it's impoverishing the talent and robbing us of our skills that
we had spent years, decades honing, training, and taking pride in. We are
getting stuck in an ouroboros setup, where with junior talent getting squeezed,
all the people who ``were in'' will die or retire, if they ever get a chance to
get to the latter.

In spite of it all, when it comes down to it, to my day to day life, I quite
love AI. I use it daily, we all use it daily. If you were to ask me if I'd give
it up to go back to my daily life as a software engineer, my answer would be an
astounding no. We use it to such an extent that we even joke---but actually just
saying the truth, so we don't out ourselves too much---without AI, if work doesn't
come to a complete halt, it will be a fraction of what we are doing now, unless
we go and kill ourselves by getting that LED monitor tan 24/7.

Why is that? Why is it that I find it so vile yet can't go back. It's not like
it's illegal, like some hard drug you got from John over the street. It's not a
forbidden fruit you've been told not to touch, otherwise you'll get banished to
Hell, on the contrary, your performance and bonuses rely on you using it. And
when it comes to using it, it makes life, when used properly, so much easier.

In my tenure as a software engineer, I have always---without ego nor some cursed
form of self-congratulating---saw myself as a high-performing engineer. Not
because I worked excessively---though I did work pretty standard hours---but because
I focused and would lock in, which helped me to enjoy a good share of
visibility, promotions, and awards.

Yet now, I'm delivering even more, more than ever, that comparing me doing
something now to then, and me then now, I would get a sit-down with my manager
over my performance and if I have had something happen in my life that is
affecting the throughput of my work.

If I ever bring these concerns with my friends or other people in the industry,
they'd immediately retort, ``Yeah Sandy, do you also hate cars and modern
medicine?'' 

In the process of thinking and living through it, I've come to a harsh truth
realization of it, specifically in the context of software engineering and the
industry that we decided to devote ourselves to---at least right now, here,
today---not so sure about tomorrow.

As a little background about me, I sat exactly where you are 4 years
ago. Graduated in 2022, did three majors, decided to go work for Microsoft. At
3.5 years, reached the coveted Senior title and left a month after that to work
for a stealth AI company. Stealth means that we are working away from the
public's eye, pre-GA product, GA stands for General Availability, meaning
whatever we sell is for you to buy.

Working at an AI-first company, even from Microsoft, who had reach $4T market
valuation, in only thanks to the massive AI push and OpenAI partnership,
essentially, selling shovels in this gold rush, what we do know is moving so
fast that in a week we collectively do more than we could at Microsoft in half a
year, and the people I work with, we are all ex-Microsoft. Same people.

We get to enjoy to be frightened of what is to come, since we witness things a
few months, maybe years in advance, before they reach all corners of our
profession. In all the flame wars, on hackernews, in the streets, across the
halls of LEEP2 and Eaton---is AI truly replacing us and coming after our
jobs? The answer is yes. Is there no art to what we do anymore, no place for a
human? There is none. 

It comes to the crucial distinction that we must make between Programming and
Software Engineering.

Programming of in itself, is us learning how to code, obsessing over the
smallest pieces of code, finding beauty in the structures we build, order in the
algorithms we employ, poetry in how every single piece falls into its place, and
that we did, what we did, is so uniquely ours, that we marvel at it. We did
it. We solved it, and reached the promised land with the power of code.

In the end, it is quite useless. That is the beauty of it. We may not make any
money out of it, we might leave it unchanged for years and decades. But we will
obsess over it. One of my proudest projects is building a website builder. It's
been around for 6-7 years now, continuously maintained, some odd 10k LOC in go,
and I love it. I use it daily, write my website in it, but what matters to me is
not that it works, but how much I've learned throughout it.

Or when I learned how to use Donald Knuth's CWEB and got infected with the idea
of Literate Programming, which once and forever changed how I see programming
completely, not as a means to an end of explaining code to a machine and make it
go brrr, but writing a work of literature for my fellow brother, for someone
else to read and marvel at it as I do. 

In Picture of Dorian Gray, Oscar Wilde says in the Preface,

#+begin_quote
/We can forgive a man for making a useful
thing as long as he does not admire it. The
only excuse for making a useless thing is that
one admires it intensely./            
#+end_quote

#+begin_export latex
\begin{flushright}
\textit{All art is quite useless.}
\end{flushright}
#+end_export

That is art. We give it meaning, through the process of doing it, through
learning, failing, and loving it. Through the attention to detail and
experiencing all sorts of emotions throughout. Yet, we live in a capitalistic
society that has no care for that and the brutal reality, to the dismay and
disappointment of Ancient Romans, who would find it vulgar to how we have to
work to survive---we have to work to afford life and to exist, and software
engineering is what gets us there.

In contrast to programming, where we talk of the journey and the in-betweens,
software engineering primarily and solely devotes its attention to the final
product. It doesn't have to be beautiful or elegant or perfect, but it does have
to be good enough, which AI today, even if it all goes up in flames and the
bubble pops, deafening everyone in vicinity, as it is right now, even the open
source models, the AI does it very very well.

The boss, the business, doesn't care whether this new Java service that handles
the checkout flow for the customers is written with AI and runs the same as what
the human would, but the former taking a few minutes vs the human taking weeks
to do so---the cost benefit analysis an executive would do in their heads puts the
human in the loop in a disadvantageous position.

The models that exist today and the skillsets that senior-plus engineers had
already developed in working with them, the produced code would be of the
similar if not the same quality as the person would write, but created in a
fraction of a time and even smaller fraction of pain and trial and error that it
takes to get there. It is true, because we see it, I see it daily.

In programming, we would work on all these algorithms of traversing graphs as
quickly as possible and all the math behind it, in software engineering, even
the most naive approach would do just fine, when the scale and scenario are
taken into account, and again, AI is great at that, since it devoured all of
that information, and it knows what libraries to use, even if it doesn't, it can
autonomously experiment, just as a human would, but with the human now out of
the picture completely.

Even if we stick to our ideals and say that we will do it ourselves---we cannot
forget how competitive our profession is. In college, we all go towards the same
goal, and the University is incentivized to graduate as many students as
possible, which works with our goal of doing as little amount of work as
possible and to still graduate.

In the ``real world'' of working for a company, the reality is more
cut-throat. You will be surrounded by career people, psychopaths, 10x-100x
engineers, bureaucrats, back-stabbers, such that even if the company says there
are no heroes and we all work together to reach the company's goal---as it should
be---the company will always reward people for the extra effort.

The ones with maximum impact and throughput, will get the bonuses, and
promotions, and some-sort of job stability (never a guarantee), and it is easier
to get there and be that when you have such powerful tooling like AI, which can
save you hours per day when doing real corporate work, like writing another Helm
Chart, writing another Github/ADO workflow, addressing another product manager's
JIRA ticket in the codebase, implementing another unit or integration test.

If you don't do it, then someone else around you, in your team, the pragmatic
engineer with no qualms of rushing forward will do it. In this way, triggering
and fueling the AI arms race amongst the software engineers. Is it a rat race?
Yes. Is it a race t the bottom, de-skilling ourselves and producing possibly
hollow work? Yes. Is there a way out of it? I don't see it, at the moment.

Unless you get rich, never have to work a day because your dividends from stocks
are doing all the hard work, and you can finally enjoy an Ancient Roman's
``otium''---spending time on things that life is meant for: hanging out with
friends, reading fulfilling literature, listening to good music, bettering
yourself as a human, and most importantly, drinking great wine.
