* What are leader's ethics on nuclear deterrence?

NOTE: This story was written as a paper ([[deterrence.pdf][original]]) for my Islamic Ethics
course.

My assistant came running to me, looking all disturbed and worried. I wonder
what could have gotten into him?

``Lord Sandy!,'' he exclaimed loudly, while still paying appropriate respects.

``How can I help you, Ishmael?''

``I have an essay deadline for my Ethics class tomorrow. You are the greatest
leader to ever grace our cursed land with your holy presence,'' my assistant
said adoringly.

``All of that is true. Is there something I can do about your ethics essay?''

``Well, yes. One of the questions is something I believe your majesty can
enlighten us. Would you equip your country's armed forces with nuclear weapons
as deterrence or use a nuclear weapon against an enemy country?''

As a leader of a nation, it is no secret that most of all, I must protect and
improve the rights, safety, and security of my people. The pride and
independence of citizens of my nation. If another nation-state or a country
comes to us with a fight or dares to threaten us, we shall match the foreign
terror and threat with our own, until the said influence and caused are fully
eradicated from my people's minds and hearts. Yes, I would and will use nuclear
weapons as a deterrence. If it ever comes to a necessity of a nuclear response
against an enemy country, then we shall strike them down from above with all of
our might and power.

I do wonder on those lonely nights, starving for some real human connection,
longing for a true feeling flowing through my veins, just once. I wonder, am I
an ethical person? Is it ethical for me to use nuclear weapons as a deterrence,
putting the scare into the entire world of my arsenal? I want to ponder about
that with my imaginary deontological and utilitarian friends.

From a deontologist's point of view, nuclear deterrence policy goes strongly
against moral principles, as it involves a conditional statement of using them
in a specific situation, which by itself is wholly immoral. Usage of such a
dramatic weapon will cause deaths of not thousands, maybe millions, but most
assuredly of billions of people. All those lives will be lost, therefore for
deontologists, which focus on the argument of the morality of the action itself,
nuclear deterrence is simply wrong.

However, is it the right ethical framework to apply in this situation? If we are
threatened by someone else with fewer deontological moral principles, the next
sure thing coming for us is sure destruction.[fn:: /Pakistan's Nuclear Testing/,
Hasan-Askari Rizvi, pp. 98-100] I do not believe Deontologists’ Argument can
keep a nation safe in the modern world, equipped with nuclear toys. What is also
wrong with it is not only its absolutionist position regarding nuclear
deterrence but also its focus on a hypothetical scenario of using nuclear
weapons under possible conditions.

The mere fact that I would write a plan of defending myself with a nuclear
arsenal in case of my nation got attacked with the same type of weapon is itself
morally wrong. If a nation doesn't have a nuclear deterrence policy set up,
another nuclear power could easily overwhelm with a high chance of attacking the
ones who cannot defend themselves with nukes. Having a nuclear deterrence
policy, but with no actionable blueprint on what to do in case of a real attack
also makes a nation weaker, therefore even more of a military target.[fn::
/Deterrence and Deontology/, McMahan, pp. 531-532]

This leads me to the realization that the Deontologist's Argument would prevent
me from equipping my country with nuclear weapons, even if it is meant for
deterrence, for the protection of my people against external threats of a
nuclear nature. As for a leader, this is unacceptable. What leader would blindly
stick to the ethical argument that only works on a small scale and apply it to
the security considerations of a whole nation? I must find another way.

Utilitarianism tells us that if any action leads to a consequence of maximizing
the happiness and well-being of affected people, therefore it must be
justified. It is the only ethical construct, in which we can safely and easily
argumentative pro-war stances, such as viewing even the short-term negative
effects as leading to the prosperity and good of a nation in the long-term
run. My decision to equip my country with nuclear weapons would be wholly
justified and approved from a utilitarian framework, as I am providing security
to my nation.

However, it makes me think, about whether the utilitarian mindset and the
utility should apply only to my countrymen or the whole world. Defending for
ourselves is a positive for us, however, the heated geopolitical nature of
nuclear deterrence policies might, directly and indirectly, result in much
discomfort not only to my people, but to the whole world, such as economic
restrictions, limitations on free trade, hostile relationships, and restricted
travel. The utilitarian point of view on nuclear deterrence depends from which
angle we will look.

History teaches us all. Recall the still ongoing debates over the atomic
bombings of Hiroshima and Nagasaki. Many arguments share the utilitarian point
of view, such that it was impossible to make Japan surrender unless there was an
overwhelming destructive force pushed on them. They believe that the bombings
themselves prevented massive casualties on both sides from the planned invasion
of Japan. Kyushu was to be invaded in November 1945 and Hondo four months
later. However, after many decades of discussing the event, other analyses have
been brought up.

Many critics believe that the nuclear attack on Japan was inherently immoral and
a war crime.[fn:: /The Collins Encyclopedia of Military History/, Dupuy & Dupuy,
BCA 1994, p. 1308] Further discussion on Japan's armed forces and military
strategies now lead us to believe that a simple naval blockade and an invasion
by conventional warfare would have forced Japan to surrender with no
conditions.[fn:: /Nuclear weapons, international law, and the normalization of
state crime/, Kramer, Ronald C, pp. 94-121] Some critics of the bombings have
even concluded that Japan was to surrender after the Soviet Union invaded
Manchuria.[fn:: /The Battle for Manchuria and the Fate of China: Siping, 1946
(Twentieth-Century Battles)/, Harold M. Tanner, pp. 30-31] Did the
utilitarian-backed usage of nuclear weapons result in the greater good? No, it
has only resulted in tragic losses, inhuman treatment of the Japanese people,
and a big crisis back at home, where the usage of nuclear weapons was widely
condemned.[fn:: /Recent Literature on Truman's Atomic Bomb Decision: A Search for
Middle Ground/, Walker, J. Samuel, pp. 311-315]

Many heinous acts could be viewed from a utilirianistic point of view as fully
justified and ethical. However, standing here, I realize, that violence breeds
violence, and it has to be this way. The actual usage of nuclear weapons as of
means of attacking another country would be deemed highly unethical by
deontology and utilitarianism, as both would result in great human suffering,
which is incredibly tough to offset with any financial or political gains
received by any of the sides.

On the other hand, nuclear deterrence for the sake of the security of a nation
is fully justified and deemed ethical from a Utilitarinistic point of view, so I
would equip my nation with such a force as a last-resort instrument against any
foreign aggression. The usage of such an instrument, however, is something that
cannot be found ethical, no matter from what lens you look. The destruction and
human price paid are simply too high. Even if it is unethical, whether it comes
to the point of retaliating against someone else's aggression, I would be called
an unethical leader. That is the price I will pay.
