= Sandy's Website
Sagindyk Urazayev <ctu@ku.edu>
LinkedIn_LINK | GitHub_LINK | Resume_LINK | PGP Key_LINK 

== Welcome to my website!

=== About me

My name is Sagindyk, everybody just calls me Sandy. Currently, I am a
Computer Science undergraduate student at https://ku.edu[University of
Kansas] I am a huge fan of `+*UNIX*+` philosophy and `+Linux+` tools in
general. Wield the power of the terminal with `+awk+`, `+sed+`, and
`+grep+`! I have interests in cyber-security, DevOps, Software
Development, System Automation, Data Science, and Typesetting tools. I
am the current active CTO at https://kuisc.com[KU Information Security
Club].

I am the creator and founder of
https://reddit.com/u/MemeInvestor_bot[Meme Investor Bot] - the biggest
interactive reddit bot on the platform that allows users from all over
to world to invest in memes and collaborate together around their
favorite content! Almost a year after the initial launch, more than 20
developers and ethusiasts worked together towards making a better
platform for collaborative content creation and promotion. We have more
than 100 thousand registered users on our system. We have our
https://meme.market[website] where we keep all the statistics updated
and available with the current trends, popular content, and meme
markets! I am the main maintainer of the project. Feel free to check out
our https://github.com/thecsw/memeinvestor_bot[github page] and commit
new changes!

I am also the creator of other various projects and bots, such as
https://reddit.com/u/prequelmemes_bot[u/PrequelMemes_bot],
https://reddit.com/u/HiveWriting_bot[u/HiveWriting_bot],
https://reddit.com/u/MemePolice_bot[u/MemePolice_bot], and so much
more! For a more detailed list of my open projects, check
https://github.com/thecsw[my github page]!

TIP: Scroll to the bottom for details on how this website is built.

=== My online articles

Here is a list of my articles I have online. I hope you will find some
of them interesting and you can learn something new! Always learn
something new!

* link:./articles/year_12019/[Welcome to year 12,019]
* link:./articles/mini_jenni/[Mini Jenni - my new best friend]
* link:./articles/using_mutt/[Bring joy back to e-mail with Mutt]
* link:./articles/installing_arch/[Installing Glorious Arch Linux]

=== My documents

This is a list of some articles, essays, reports and presentations I
have made for purposes other than publishing online. Most of them (if
not all) should be in a PDF format, typed in LaTeX, Org-Mode, or
troff/groff. I hope you find them interesting!

* link:./documents/20191005-Jeffersonian-Democracy.pdf[Jeffersonian
Democracy and Education]
* link:./documents/20190320-KCDC-Alpha-Report.pdf[KCDC Alpha
Cybersecurity competition]
* link:./documents/20181130-Twin-Peaks-as-a-Cult-Film.pdf[Twin Peaks as
a Cult Film]
* link:./documents/20180500-IB-EE-RSA.pdf[RSA: Encrypting, Decrypting,
Hacking.]
* link:./documents/20180400-Approximation-of-Divergent-Series.pdf[Approximation
of Divergent Series]

=== My quotes

I have some of my favorite quotes and sayings recorded. Some of them are
mine. link:./quotes[The page is here!]

=== My favorite movies

I love movies and I think movies deserve a separate full section on my
website. Well, I have taken a Film class my freshman year and I loved
it. It was a class about trash movies. Talk to me about that! Alright,
here is the list:

* The Godfather
* The Godfather Part II
* 2001: A Space Odyssey
* The Big Lebowski

=== My favorite books

I love reading too! Here is some list of my favorites:

* Solaris
* The Tao of Pooh
* A Doll's House

=== This Website

I love typesetting tools. In my experience, I have used and written
articles and papers using the following list of tools: `+LaTeX+`,
`+groff+`, `+markdown+`, `+Org-Mode+`, `+asciidoctor+`, `+HTML+`,
`+plain text+`. I had to uncompress Word files and work with raw XML
files there, what a trip that was.

This beautiful website typed in https://orgmode.org/[Org-Mode] and built
using http://asciidoctor.org[Asciidoctor]. The source code can be found
https://github.com/thecsw/thecsw.github.io[here].

It is one of my dreams to typeset documents and books like Brian
Kernighan:

* https://www.amazon.com/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440/ref=sr_1_1?keywords=The+go+programming+languagu&qid=1556766950&s=gateway&sr=8-1-spell[The
GO Programming Language, title="Best GO Book you can find out there"]
* https://www.amazon.com/Programming-Language-2nd-Brian-Kernighan/dp/0131103628/ref=sr_1_2?crid=3CGWLG27VTZ18&keywords=the+c+programming+language+2nd+edition&qid=1556952161&s=gateway&sprefix=The+c+program%252Caps%252C182&sr=8-2[C
Programming Language, 2nd Edition, title="The Bible of computing world"]
* https://www.amazon.com/gp/product/013937681X/ref=dbs_a_def_rwt_hsch_vapi_taft_p1_i5[The
Unix Programming Environment, title="The Almanac of computing world"]
