* Politeness is Dead

NOTE: This was a research paper written for the graduate course /SLAV 540:
Language and Identity in East-Central Europe and Former Soviet Union/ taught by 
the incredible [[https://mlg.ku.edu][Marc L. Greenberg]]. See the [[Politeness is Dead.pdf][original paper]].

** Introduction

Politeness theory was proposed by P. Brown and S. Levinson in the late
70s. It focuses on the original notion of politeness, which Mary
Henningsen describes as „efforts on redressing the affronts to a
person's self-esteem of effectively claiming positive social values ."
The central concept of the theory is based on the idea of the face,
understood in terms of sociology. ``Face'' is something that can be lost,
maintained, or enhanced. "Every person lives in a world of social
encounters, involving him either in face-to-face or mediated contact
with other participants [...]. The term face may be defined as the
positive social value a person effectively claims for himself by the
line others assume he has taken during a particular contact". It is
generally in every participant's interest to maintain each others'
“face”: "The combined effect of the rule of self-respect and the rule of
the considerateness is that the person tends to conduct himself during
an encounter to maintain both his face and the face of other
participants." The actions by means of which people cooperate in
maintaining a face are called “face-work.”

Brown and Levinson, inspired by Goffman's work, especially the part
dedicated to the „face-work,” developed their own theory that one's face
is categorized into two forms: positive and negative. “Positive face”
refers to the positive, consistent “self-image” or personality claimed
by interactants, including the desire that others appreciate and approve
of this image. “Negative face,” on the other hand, refers to any speaker
́s right not to be imposed upon and the right to be independent of the
social world. To quote Brown and Levinson, "negative face: the want of
every “competent adult member” that his actions be unimpeded by others.
Positive face: the want of every member to be desirable to at least some
others”.

“Face” can be defined as the self-image during the action of speaking.
During any interaction, the faces of both interlocutors are threatened
or can even be damaged. Because of that, Brown and Levinson are forging
the term „face-threatening act,” FTA. As Anna Żurek points out, „to be
polite does not only mean respecting other people's rights; politeness
should also protect the message's sender, to be specific - their social
image”. We can divide the FTAs into negative FTAs and positive FTAs.

It goes without saying that speakers who want to reach their aims cannot
do without FTAs. Politeness, as Brown and Levinson define it, consists
of a set of strategies that serve to minimize the risks to “face” or
“self-esteem” whenever a speaker commits a “face-threatening act.” They
argue that politeness strategies follow from the human ability to reason
and find means to achieve one ́s ends. The question is how to perform
the FTAs. There are various ways, depending on the context of
interaction, the speakers' social relationship, and the amount of
imposition that the FTA entails. To carry out an FTA, a speaker may
select one of the four following strategies (here very shortly about
strategies)

** Motivation

We have chosen this topic thanks to its close ties to sociolinguistics.
We explored other options before pursuing this research, which resulted
in weak connections to the course. We think Politeness Theory is a
fascinating topic. It helps us look closer into everyday conversations
and appreciate all the linguistic techniques applied by every person. We
do not talk explicitly about it, as it is usually considered “common
sense” and something built off intuition. This inspection will allow us
to grasp the foundation of human communication and language as a sharp
instrument.

** Dead Souls

To showcase the application and usefulness of the Politeness Theory, we
must choose an appropriate case study to base our research on. For that
purpose, we decided Nikolai Gogol's satirical masterpiece - /Dead
Souls/. This exemplar of 19th-century Russian literature takes place in
at the time, contemporary Russia. Chichikov, a mysterious man, visits a
small provincial town with a single goal of acquiring the souls of the
dead surfs. He displays the most extraordinary moral rot, yet through
many of his shady exchanges, we discover his incredible skill at
communication and getting the sweet end of a deal. Thanks to its
satirical style, /Dead Souls/ is a perfect example of how politeness can
be wielded in a multitude of ways and across social hierarchies.

** Politeness in Russian

In this chapter, we shall discover how Dead Souls explores the
applications of politeness theory in social situations of 19th-century
Russia. To efficiently illustrate the usage of face theory, we will go
over ten examples of conversations selected from the novel using
qualitative and quantitative reasoning. Firstly, we will analyze each
excerpt individually, explicitly focusing on context, sentence
structure, word choice, dialogue construction, and speech patterns. This
first approach should give us a better in-depth understanding of
self-esteem dynamics in conversations and how social values are
presented. This would apply to such concepts as “losing face” or “saving
face.” Secondly, we will take a numerical approach by giving each
selected passage an absolute score of one to ten. One would signify
complete impoliteness, and ten would indicate an extraordinary
application of the politeness theory. This methodology will help us
compare the same passages from different languages objectively. In this
paper, we are only focusing on comparing Russian and Polish. Let us
start exploring the excerpts.

*** First passage. Chapter II.

#+begin_quote
-- Сделайте милость, не беспокойтесь так для меня, я пройду после, --
говорил Чичиков.\
-- Нет, Павел Иванович, нет, вы гость, -- говорил Манилов, показывая
ему рукою на дверь.\
-- Не затрудняйтесь, пожалуйста, не затрудняйтесь. Пожалуйста,
проходите, -- говорил Чичиков.\
-- Нет уж извините, не допущу пройти позади такому приятному,
образованному гостю.\
-- Почему ж образованному?.. Пожалуйста, проходите.
#+end_quote

In this hilarious passage, we see how Chichikov and Manilov argue about
who will be entering through the door first. The term arguing might be
even too extreme to use in this case. They are blockading each other by
letting the other one pass through first as a sign of friendly courtesy.
Chichikov aims to get in Manilov's good grace to close a deal with dead
souls further, whereas Manilov is a sentimental man by nature. This
scene is funny by how overly polite they are, which makes analyzing this
excerpt even more enjoyable.

Chichikov starts by asking Manilov to indulge him by not worrying about
him. In this first section, Chichikov immediately performs a negative
face-threatening act, such as making a request, therefore dealing damage
to the hearer, Manilov. Even though negative face-threatening acts are
defined as obstructing the interlocutor's freedom of action, Chichikov
uses the request to perform a positive face-threatening act, where he
takes damage by bringing the status of his well-being down.

Manilov takes an offensive response on the counter by stating that
Chichikov is his guest; therefore, he must go through the door first.
Notice that Manilov also used Chichikov's full address -- Pavel
Ivanovich, indicating that he wishes to bring serious attention to his
statement. We just witnessed an exchange of negative face-threatening
acts, which is expected in this case, where both are attempting to
request something from each other, like going first. Manilov also
performed a non-verbal gesture, such as pointing toward the door, which
only exemplifies his intent on letting Chichikov pass first. We must
notice that this exchange by Manilov, even recognized as forward, is
still perceived as polite.

It follows Pavel Ivanovich taking damage to himself in his positive face
by apologizing and then dealing damage to Manilov's negative face by
stating he would not let such an intelligent and pleasant man walk
behind him. His description of Manilov is an act of kindness, as saving
face and bringing Manilov up in the exchange's hierarchy. In Russian,
Chichikov not only describes Manilov but prepends it with “такому,”
which acts as an amplifier to the following adjectives.

Manilov recounts Chichikov's description of him by asking why he called
him educated, which could be seen as his positive face-threatening act,
where he damages himself by losing face. Finally, this passage showed a
great example of mutual exchanges of face-threatening actions, where
both sides consistently take damage to respond to their interactor's
advances. Numerically, this passage receives a score of nine out of ten.

*** Second passage. Chapter II.

#+begin_quote
-- А вице-губернатор, не правда ли, какой милый человек? -- сказал
Манилов, опять несколько прищурив глаза.\
-- Очень, очень достойный человек, -- отвечал Чичиков.\
-- Ну, позвольте, а как вам показался полицеймейстер? Не правда ли, что
очень приятный человек?\
-- Чрезвычайно приятный, и какой умный, какой начитанный человек! Мы у
него проиграли в вист вместе с прокурором и председателем палаты до
самых поздних петухов; очень, очень достойный человек.\
-- Ну, а какого вы мнения о жене полицеймейстера? -- прибавила
Манилова. -- Не правда ли, прелюбезная женщина?\
-- О, это одна из достойнейших женщин, каких только я знаю, -- отвечал
Чичиков.
#+end_quote

This passage follows swiftly the first one. Manilov and Chichikov are
currently in the former's residence, having supper with tea and
discussing the town's government figures and municipalities. The whole
conversation does not seem to involve any direct damage to either the
hearer or the speaker; instead, it follows a lengthy yet flattering
description of each person they mention. However, it does indirectly
save the face of each interlocutor. By praising another person for their
qualities and characteristics, one can keep their face by associating
with such a figure, also showing their abilities to recognize
characters' qualities.

Interestingly enough, none of them even thought of criticizing any
people mentioned. When Manilov wants to hear Chichikov's opinion on
someone, he asks him about them in a positive affirmation, “isn't he a
lovely person,” which leaves Pavel Ivanovich no choice but to agree and
contribute the qualities expressed. This is a necessary exchange, as it
is how Chichikov is personally acquainted with the most critical figures
in town, which only grants him more credibility and status by
association.

The way that Chichikov describes those people is the most exaggerated.
For example, talking about the chief of police, he describes him as
“очень, очень достойный человек,” by using the double “очень.” It is
usually only used once and in cases to show extreme affection toward
something. Repeated amplifier usage might seem childish, yet it works
/very, very/ well in this case. Not only do they describe people by
their qualities, but they also note them as the best they ever had the
pleasure to meet, such as “достойнейших женщин, каких только я знаю.”
Only for the lack of direct politeness actions, this excerpt receives a
six out of ten.

*** Third passage. Chapter IV.

#+begin_quote
-- Ну, послушай, чтоб доказать тебе, что я вовсе не какой-нибудь
скалдырник, я не возьму за них ничего. Купи у меня жеребца, я тебе дам их в
придачу.\
-- Помилуй, на что ж мне жеребец? -- сказал Чичиков, изумленный в
самом деле таким предложением.\
-- Как на что? да ведь я за него заплатил десять тысяч, а тебе отдаю за
четыре.\
-- Да на что мне жеребец? завода я не держу.\
-- Да послушай, ты не понимаешь: ведь я с тебя возьму теперь всего
только три тысячи, а остальную тысячу ты можешь заплатить мне после. -- Да не
нужен мне жеребец, Бог с ним!
#+end_quote

The context for the third passage differs dramatically from the ones
before with Manilov. In this chapter, Chichikov is dealing with another
soul owner -- Nozdrev. He is a rash man and a bully; precisely for those
reasons, it is a true struggle for Chichikov to advance in his shady
business. In comparison with Manilov, Nozdrev is a much more irrational
man.

Nozdrev is no gambler to miss an opportunity if he smells one appearing
right before him. While Chichikov is trying to close his deal, the
unreasonable soul owner swiftly pushes his value onto Chichikov in
attempting to sell him a stallion with dead souls. It's directly
damaging Chichikov's negative face, as he is almost forced to purchase a
stallion that he doesn't need or want. One could reply with a
straight-forward “no” or similar; however, it might shut down the dead
souls' purchase, so Chichikov asks him why he would need to get a
stallion. In his repertoire, Nozdrev pushes forward the offer by
outlining the financial profit for Chichikov, as he bought it for ten
thousand and is ready to sell it for four thousand instead. It's an act
of losing one face to score a profit.

Chichikov stays firm to his statement regarding the necessity of a
stallion for him instead of refusing the offer as his agenda hangs on
the weird machinations put forward by Nozdrev. Nozdrev offers him to pay
the first three thousand in advance and later pay the remaining thousand
to sweeten the deal. This passage is an excellent example of applying
the politeness theory and face strategies to save or salvage a bargain,
especially with incoherent and pushy entrepreneurs. This passage will
receive a score of eight out of ten.

*** Fourth passage. Chapter IV.

#+begin_quote
-- Экой ты, право, такой! с тобой, как я вижу, нельзя, как водится
между хорошими друзьями и товарищами, такой, право!.. Сейчас видно, что
двуличный человек!\
-- Да что же я, дурак, что ли? ты посуди сам: зачем же приобретать
вещь, решительно для меня ненужную?\
-- Ну уж, пожалуйста, не говори. Теперь я очень хорошо тебя знаю.
Такая, право, ракалия! Ну, послушай, хочешь метнем банчик? Я поставлю
всех умерших на карту, шарманку тоже.
#+end_quote

In a concise amount of time, an already strained duologue between
Nozdrev and Chichikov heats up even further. The impatient soul owner
blows up by accusing our protagonist of his untrustworthiness and
double-faced nature. However, this kind of treatment is not called for,
all resulting from polite refusals from Chichikov to buy his horses and
stallions. Even with his face strategies, our shady dealer uses a bald
on-record technique of asking whether Nozdrev takes him for a fool to
buy something he has no interest in nor use for. To smoothen the
interaction, we see how Chichikov attempts to minimize the threat to the
hearer's positive face by setting his direct annoyance with received
offers in the form of a question. Nozdrev realizes that this leads to
the end of any deal; to save it in any way possible, he soothes it over
by proposing another deal -- gambling it away. There isn't much
politeness involved, except for attempting to save both faces from a
value that will never happen. Therefore, it gets a score of three out of
ten.

*** Fifth passage. Chapter V.

#+begin_quote
-- У губернатора, однако ж, недурен стол, -- сказал Чичиков.\
-- Да знаете ли, из чего это все готовится? вы есть не станете, когда
узнаете.\
-- Не знаю, как приготовляется, об этом я не могу судить, но свиные
котлеты и разварная рыба были превосходны.\
-- Это вам так показалось. Ведь я знаю, что они на рынке покупают.
Купит вон тот каналья повар, что выучился у француза, кота, обдерет его,
да и подает на стол вместо зайца.\
-- Фу! какую ты неприятность говоришь, -- сказала супруга Собакевича.
#+end_quote

After an irritating interaction with Nozdrev, Chichikov visits a new
soul owner -- Sobakevich, a strong, silent, and economical man. Compared
with Manilov, he would inquire deeper into Pavel Ivanovich's underlying
motives and angles, making closing the deal more complicated. He would
also be more sensible and battle-trained in sales than Nozdrev. This
calls for new strategies.

This excerpt is similar to the second passage, where we are in the
middle of supper. However, even though the setups and topics are
similar, the flow of the conversation is entirely different. Chichikov
attempts to save face by indirectly raising his status and credibility
by bringing up and discussing his acquaintances with the town's elite.
To his surprise, Sobakevich is not of a high opinion of all the people
that Chichikov uses as examples, which results in an inverse effect that
he was expecting. We also must notice that our protagonist realizes he
has to be more reserved with Sobakevich; instead of describing the
governor's reception as “the best I have ever had the pleasure to
receive” or something similar that he would use on Manilov, he states
that “it's not bad.”

Even for the reserved praise that Chichikov gave to the town's
representatives, Sobakevich does not hold back on calling all of them
thieves and liars. Even going as far as claiming all their dishes are
prepared using second- or third-rate ingredients, which completely
nullifies any praise Chichikov tried to extend. Throughout this
conversation, even with our shady hero applying all the courtesy
strategies to let the landowner warm up toward him, it results in the
opposite effect. It is an excellent example of using politeness theory
when the interlocutor does not reciprocate. Sobakevich is so
uncooperative that even his wife reprimands him for his nasty
allegations. This passage gets a score of five out of ten.

*** Sixth passage. Chapter V.

#+begin_quote
-- Что ж, разве это для вас дорого? -- произнес Собакевич и потом
прибавил: -- А какая бы, однако ж, ваша цена?\
-- Моя цена! Мы, верно, как-нибудь ошиблись или не понимаем друг друга,
позабыли, в чем состоит предмет. Я полагаю с своей стороны, положа руку
на сердце: по восьми гривен за душу, это самая красная цена!\
-- Эк куда хватили -- по восьми гривенок!
#+end_quote

Succeeding in a sale with Sobakevich might take everything Chichikov can
offer. As expected, the stern soul owner starts aggressively haggling
and raising the prices to the roof, therefore testing how much money
Chichikov is willing to put on the table. This is a prime example of a
negative face-threatening act, as our dead souls' trader is getting
forced to get into a deal that is not beneficial to him. A confrontation
follows, where the two of them start arguing regarding the pricing and
whether it is justified by the underlying product, the souls of the dead
serfs. Chichikov attempts to smoothen the interaction by minimizing the
imposition, implying he would not go lower than eight hryvnias for a
soul. This is an example of positive politeness, where he emphasizes his
goal of avoiding imposition on the hearer, Sobakevich. This passage gets
a five out of ten.

*** Seventh passage. Chapter VI.

#+begin_quote
-- Это бы еще слава Богу, -- сказал Плюшкин, -- да лих-то, что с того
времени до ста двадцати наберется.\
-- Вправду? Целых сто двадцать? -- воскликнул Чичиков и даже разинул
несколько рот от изумления.\
-- Стар я, батюшка, чтобы лгать: седьмой десяток живу! -- сказал
Плюшкин. Он, казалось, обиделся таким почти радостным восклицанием.
Чичиков заметил, что в самом деле неприлично подобное безучастие к
чужому горю, и потому вздохнул тут же и сказал, что соболезнует.
#+end_quote

In this sad chapter, we meet Plyushkin, a compulsive hoarder who is not
complacent with his lot in life and is miserable daily. This is the
first example when Chichikov fails at keeping both the friendly and
professional courtesy he had toward people he encountered before. His
greed and poshlost' get the upper hand over him when he replies
excitingly to the tragedy of a man losing over a hundred and twenty
serfs in a short amount of time.

Plyushkin is fast to notice his misplaced happiness that he even takes
offense because of it. Our sleazeball lost face by getting too excited
over the possibility of a great deal. Recognizing the missed strategy,
he quickly recuperates from his indecent indifference to someone else's
grief by sharing his condolences. The societal status of his
interlocutor also influences why Chichikov made this misstep. His
previous partners: Manilov, Nozdrev, and Sobakevich, were wealthy and
well-respected amongst the townsfolk, whereas Plyushkin is simply a
failed landowner who doomed his serfs to their demise. Because Chichikov
recovered in the end, this excerpt gets a score of two.

*** Eighth passage. Chapter VI.

#+begin_quote
-- Только, батюшка, ради нищеты-то моей, уже дали бы по сорока копеек.\
-- Почтеннейший! -- сказал Чичиков, -- не только по сорока копеек, по
пятисот рублей заплатил бы! с удовольствием заплатил бы, потому что вижу --
-- почтенный, добрый старик терпит по причине собственного добродушия.\
-- А ей Богу, так! ей Богу, правда! -- сказал Плюшкин, свесив голову
вниз и сокрушительно покачав ее. -- Всё от добродушия.\
-- Ну, видите ли, я вдруг постигнул ваш характер. Итак, почему ж не
дать бы мне по пятисот рублей за душу, но... состоянья нет; по пяти
копеек, извольте, готов прибавить, чтобы каждая душа обошлась, таким
образом, в тридцать копеек.\
-- Ну, батюшка, воля ваша, хоть по две копейки пристегните:
#+end_quote

In this part, we observe how politeness strategies can be used toward
unethical means, such as Chichikov buttering Plyushkin up and swindling
him out of dead souls for almost nothing. Plyushkin damages his positive
face in his impoverished situation by underselling himself and pleading
for Chichikov to pay forty kopeks per soul. In his true fashion, the
protagonist calls Plyushkin the most venerable and swears that not only
would he pay forty kopeks per soul but would give out give hundred
rubles thanks to his good nature and bonhomie character. However, none
of those statements are true to Chichikov's conscience. It is all
strategically plotted to get the older man back in his good grace and
force an unfair deal onto him. Getting Plyushkin all excited, keeping
him dealing damage to himself and his status, finally, Chichikov makes
the final statement that he would pay up by the highest price, only if
he had the fortune to do so. Instead, he would pay thirty kopeks, which
was more than two magnitudes lower than what he promised the older man.
Accepting the inevitability of the deal and damaged face, Plyushkin is
ready to take the value at the lowest price. This passage will receive a
score of nine.

*** Ninth passage. Chapter VII.

#+begin_quote
-- Да вы всегда славились здоровьем, -- сказал председатель, -- и
покойный ваш батюшка был также крепкий человек.\
-- Да, на медведя один хаживал, -- отвечал Собакевич.\
-- Мне кажется, однако ж, -- сказал председатель. -- вы бы тоже
повалили медведя, если бы захотели выйти против него.\
-- Нет, не повалю, -- отвечал Собакевич, -- покойник был меня
покрепче, -- и, вздохнувши, продолжал:-- Нет, теперь не те люди: вот хоть и моя
жизнь, что за жизнь? так как-то себе...
#+end_quote

Let us refreshen us a little bit. This passage will explore the
politeness between the town's elites. The chairperson in this excerpt
flatters Sobakevich by praising his father's health. This works in the
framework of a negative face-threatening act, as the chairman expresses
his sentiments about the hearer's and his father's health by stating
they could even topple a bear. This gets a score of seven out of ten.

*** Tenth passage. Chapter IX.

#+begin_quote
-- Да, однако же, нашлись некоторые дамы, которые были неравнодушны к
нему.\
-- Я, Анна Григорьевна? Вот уж никогда вы не можете сказать этого,
никогда, никогда! -- Да я не говорю об вас, как будто, кроме вас,
никого нет.\
-- Никогда, никогда, Анна Григорьевна! Позвольте мне вам заметить, что
я очень хорошо себя знаю; а разве со стороны каких-нибудь иных дам, которые
играют роль недоступных.\
-- Уж извините, Софья Ивановна! Уж позвольте вам сказать, что за мной
подобных скандальозностей никогда еще не водилось. За кем другим разве,
а уж за мной нет, уж позвольте мне вам это заметить.\
-- Отчего же вы обиделись? ведь там были и другие дамы, были даже
такие, которые первые захватили стул у дверей, чтобы сидеть к нему поближе.
#+end_quote

Finally, in this last passage, closer to the end of the novel, we get to
a conversation between two most esteemed town ladies.

** Politeness in Polish

In this chapter, I am going to analyze nine passages from „Dead Souls”
by Nikolai Gogol, translated to Polish by Wiktor Dłuski. My goal is to
find out what linguistic means the translator used to express
politeness. These means are primarily linguistic, but as we know - the
language does not exist in the void. Therefore, I am taking into account
also cultural factors.

*** Passage I

#+begin_quote
(1) - Błagam pana, niechże się pan tak dla mnie nie krępuje, wejdę za
panem - mówił Cziczikow.\
(2) - Ach, nie, nie, drogi panie, pan jest gościem - mówił Maniłow,
wskazując ręką drzwi.\
(3) - Niechże pan się nie krępuje, proszę się nie krępować. Proszę
przejść - mówił Cziczikow.\
(4) Nie, proszę jednak wybaczyć, ale nie pozwolę przejść za mną takiemu
przyjemnemu, wykształconemu gościowi.\
(5) A czemuż to wykształconemu?... Proszę przejść.
#+end_quote

The passage above presents a short discussion between Chichikov and
Manilov. They are trying to convince one another to enter the door
first. The situation is very uncomplicated and does not require extreme
politeness used by both characters. The dialogue starts with Chichikov
saying „ Błagam pana, niechże się pan tak dla mnie nie krępuje, wejdę za
panem”. The first thing we should pay attention to is the usage of the
„pan” form. There is no „Vy” form in the Polish language, understood as
a means of expressing politeness towards the interlocutor, as it is in
Russian or Czech. Polish „Wy” can be used only in its basic grammatical
form - indicating 2nd person of Plural. Therefore, the same level of
politeness as in Russian while using the „vy” form is attained with the
form of „Pan/pani.”

Another factor making the above passage polite is using certain verbs to
stress the degree of goodwill. The first sentence starts with the word
„błagam,” English „I beg.” There is no other reason than stressing
politeness in using the strong expression of „błagać” instead of, more
natural here, „proszę” (Eng. „please”) or even „nalegam” (Eng. „I
insist”). „Proszę” is used in line (3) twice. In both sentences we can
observe the construction „Proszę” + infinitive („proszę przejść”). The
same communication would be maintained using the form „proszę” +
imperative („proszę przejdź”); however, the first version is considered
more polite. The reluctance to use the imperatives and employing other
forms instead is also one of the ways of showing respect and politeness
in the Polish language.

The other language technique applied in the passage above is using the
intensifiers instead of imperative. The particle -że („niechże”) or -ż
(„czemuż”) are making the statement firm, but in the way, much more
polite than using a simple imperative, which operated here could be
considered rude.

Other factors making the passage polite are certain adjectives that
refer directly to the good features of the interlocutor (line (4) -
„przyjemny,” „wykształcony” - Eng. „nice,” „educated”) and
extralinguistic, cultural factor -- a reference to the traditional
hospitality and highest position of the guest (line (2) - „pan jest
gościem”). We can also indicate the set phrase „proszę wybaczyć, ale...”
(line (4)), also traditionally used as means of expressing politeness.

Numerically, this passage receives 10/10.

*** Passage II

#+begin_quote
(1) A wicegubernator, prawda, jaki to miły człowiek? - powiedział
Maniłow, znów z lekka mrużąc oczy.\
(2) Bardzo, bardzo godny człowiek - odrzekł Cziczikow.\
(3) No a, za pozwoleniem, jaki się panu wydał policmajster? Prawda, że
to bardzo przyjemny człowiek?\
(4) Nadzwyczaj przyjemny i jaki mądry, jaki oczytany człowiek! Graliśmy
z nim w wista razem z prokuratorem i prezesem sądu do najostatniejszego
piania kogutów. Bardzo, bardzo godny człowiek.\
(5) A jakiego jest pan zdania o żonie policmajstra? - dodała Maniłowa -
Prawda, że to nadzwyczaj uprzejma kobieta?\
(6) O, to jedna z najgodniejszych kobiet, jakie w ogóle znam -
odpowiedział Cziczikow.
#+end_quote

In the passage, we can observe the continuation of the first dialogue
between Chcichikov and Manilov. They are discussing other people, the
crucial figures in society.

As the primary way of expressing politeness, we can again acknowledge
using the form „pan” instead of the direct form „ty.” Using „pan”
indicates basic respect between two sides of the conversation and that
both sides keep the conversation polite. Also, once again, we can point
out using certain positive adjectives as one the indicators of
politeness - „przyjemny,” „oczytany,” „mądry” (sentence (4)) - „nice,”
„widely-read,” „smart.” The new mean used in this particular passage is
employing the superlative - in the sentence (6), Chichikov describes the
policeman's wife as „najgodniejsza” = „the most noble.” Using a
superlative here is a way of expressing politeness and respect; there is
no justification for using it in any other meaning. Objectively, we
cannot say if the policeman's wife is or is not the noblest woman in the
world. This exaggeration's goal is exclusively being polite. The other
linguistic technique is the repetition - in the sentence (2), it would
definitely be enough if Chichikov said only „Godny czlowiek” (Eng. „A
noble man”) or even „Bardzo godny człowiek” = „very noble man.” Adding
seemingly redundant repetition is another means used to express
politeness. The exact role has the word „nadzwyczaj,” an old-fashioned
way of saying „extremely” - in this case, once again, a kind of
exaggeration used to show politeness.

Numerically, this passage receives 9/10.

*** Passage III

#+begin_quote
(1) No więc posłuchaj, żeby ci dowieść, że żadnym liczykrupą nie jestem,
ja nic za nich nie wezmę. Kup ode mnie ogiera, ja ci dam dusze na
dokładkę.\
(2) Zlituj się, na co mi ogier? - powiedział Cziczikow, zaiste zdumiony
taką propozycją.\
(3) Jak to na co? Przecież ja za niego dziesięć tysięcy zapłaciłem, a
tobie go oddaję za cztery.\
(4) Ale na co mi ogier? Stadniny nie trzymam.\
(5) Posłuchaj, nic nie rozumiesz: przecież ja od ciebie teraz wezmę
tylko trzy tysiące, a ostatni tysiąc możesz mi zapłacić później.\
(6) Ale mnie ogier niepotrzebny, Bóg z nim!
#+end_quote

The passage above is a dialogue between Chichikov and Nozdarev. What is
noticeable at first sight is an entirely different character of the
conversation compared to the dialogue with Mamilov. The main difference
is conducting the exchange using the „ty” form - the „pan” form is
absent; instead of the sides of the dialogue, use the forms of 2nd
person of Singular. This leads to the conclusion that politeness is on a
lower level in this particular passage than in previous ones. We also
can observe using the imperative instead of form „proszę” + infinitive
(„posłuchaj” instead of „proszę posłuchać” or „kup” instead of „proszę
kupić” in sentence (1)). Another factor lowering the level of politeness
is the resignation from the conditional mood when asking for a favor or
expressing doubt. In line (4), Chichikov says, „Ale na co mi ogier?”
using no conditional. If he wanted to be polite, he would use the second
conditional, a widely used means to make the statement less direct,
hence - more polite. Directness itself is considered rather impolite --
the interlocutor is making no effort to make the other side feel better,
using smooth words. There is a vivid example of such behavior in line
(5) - Nozdarev says: „Posłuchaj, nic nie rozumiesz (...)” - Eng.
„Listen, you don't understand a single thing.” If Nazdarev wanted to
maintain a high level of politeness he would probably say „Obawiam się,
że mnie źle zrozumiałeś” = „I am afraid you did not understand me”.

At the same time, we cannot say that this dialogue is impolite -- it is
direct and between people who do not need to use the „pan” form between
each other because their relationship is close, not because of being
impolite.

Numerically, this passage receives 7/10.

*** Passage IV

#+begin_quote
(1) Ech, naprawdę, co z ciebie...! Z tobą, widzę, nie można, jak wypada
między dobrymi przyjaciółmi i towarzyszami, taki z ciebie naprawdę...!
Teraz widać, że ty dwulicowy jesteś!\
(2) Ale co ty, czy ja dureń jestem czy jak? Sam pomyśl: po co kupować
rzecz, która mi całkiem do niczego nie jest potrzebna?\
(3) No, już ja cię proszę, nawet nie mów. Teraz to ja już ciebie bardzo
dobrze znam. Po prostu szubrawiec z ciebie! No więc posłuchaj, chcesz,
rozegramy banczek. Postawię wszystkich zmarłych na kartę i katarynkę
też.
#+end_quote

This passage continues the dialogue between Chichikov and Nozdarev. The
conversation does not go directly where Nozdarev wishes, and he is
frustrated. This frustration is well seen in the low level of
politeness. Still, as in the previous passage, they address each other
using the form of „ty.” What is new in this passage is using the words
unquestionably impolite - „szubrawiec” = rogue is almost calling names.
Also, using the adjective „dwulicowy” = double-faced points out a flaw
directly. What also draws attention is the syntax - sentences are not
grammatically correct, are not thought through, and the syntax is
reversed, which may indicate indignation. In the line (1) Nozdarev says
„Teraz widać, że ty dwulicowy jesteś!”. According to the rules of Polish
syntax, the verb should be put before the adjective, and there is no
need to indicate the subject (ty). The sentence constructed this way is
received as impolite.

In line (3), we can observe using the imperative „nie mów” - „don't say
anything.” Asking people to stop talking is generally considered rude,
along with imperative form; this message is even stronger.

Numerically, this passage receives 3/10.

*** Passage V

#+begin_quote
(1) U gubernatora jednak stół jest nie najgorszy - powiedział Cziczikow.\
(2) A wie pan, z czego oni to wszystko przyrządzają? Jeść pan nie
będziesz, kiedy się dowiesz.\
(3) Nie wiem, jak się przyrządza, o tym wypowiadać się nie mogę, ale
kotlety wieprzowe i ryba z wody były doskonałe.\
(4) To się panu tylko tak wydawało. Przecież ja wiem, co oni na rynku
kupują. Kupi ta kanalia, kucharz, ten co się u Francuza wyuczył, kota,
obedrze ze skóry i poda na stół zamiast zająca.\
(5) Fu, jakie ty nieprzyjemności mówisz! - powiedziała małżonka
Sobakiewicza.
#+end_quote

In passage V, we listen to the dialogue between Chichikov and
Sobakevich. We can observe a fascinating interaction - while Chichikov
decides to keep his words polite and measured, Sobakevich is far more
direct and is not very careful about his comments. They keep using the
„pan” form, which naturally indicates a high level of politeness.
However, in line (2), we experience very unusual use of this form.
Sobakevich says „Jeść pan nie będzie, kiedy się dowie” instead of
definitely more polite „Kiedy pan się dowie, nie będzie pan (tego)
jadł”. Sobakevich uses the vocative form of „pan” along with the verb
with the ending of the 2nd person of Singular, which is polite only on
the surface. Sobakevich is also very direct in his statement, which is
considered impolite, as we stated earlier. In section (4), he
dismissively responds to Chichikov's opinion, saying, „To się panu tylko
tak wydawało” - he does not even try to say „you were wrong” in a
friendly way. Sobakevich also uses the universally considered rude
words, like „kanalia” = „scum.” Chichikov, on the other hand, is trying
to remain polite, elevating the level of politeness in this dialogue.

Numerically, this passage receives 5/10.

*** Passage VI

#+begin_quote
(1) A czy to dla pana za drogo? - spytał Sobakiewicz, po czym dodał - A
jaka, powiedzmy, byłaby pańska cena?\
(2) Moja cena! My się chyba jakoś pomyliliśmy albo nie rozumiemy się
wzajemnie, zapomnieliśmy na czym sprawa polega. Ja ze swej strony
uważam, rękę kładąc na sercu: osiemdziesiąt kopiejek za duszę, to
najprzyzwoitsza cena!\
(3) A to dopiero, osiemdziesiąt kopiejek!
#+end_quote

In this passage, we can observe that Sobakevich's attitude changes. He
begins being more polite, which proves, for example, using the
conditional while asking about opinion: „jaka byłaby pańska cena?”.
Also, asking the interlocutor for an opinion is an expression of
politeness itself. Also, Chichikov remains polite, although he seems to
be frustrated. In section (2), he does not address his statement
directly to Sobakevich. He does not say, „You were wrong, or you don't
understand me” instead, he is using the forms of 2nd person of Plural,
making an impression that is not only Sobakevich's fault but that they
are in this situation together: „My się chyba jakoś pomyliliśmy albo nie
rozumiemy się wzajemnie” = „We probably both were wrong or we do not
understand each other.” Putting words this way makes the communication
smoother, with no direct attack or accusation.

Numerically, this passage receives 6/10.

*** Passage VII

#+begin_quote
(1) Gdyby tak, to jeszcze chwała Bogu - powiedział Pluszkin - Niech mnie
licho, że od tamtego czasu do stu dwudziestu się zbierze.\
(2) Naprawdę, całe sto dwadzieścia? - zawołał Cziczikow i aż usta trochę
otworzył ze zdumienia.\
(3) Za stary jestem, ojczulku, żeby łgać: siódmy krzyżyk mam na karku -
powiedział Pluszkin.
#+end_quote

Passage VII is a dialogue between Plyushkin and Chichikov. Plyushkin in
the social hierarchy is situated lower than Chichikov, which is
reflected in their conversation. Plyushkin uses towards Chichikov the
vocative form - „ojczulku,” which may be an indicator of respect.
Chichikov, for the first time, is not extremely polite - he cannot hide
his excitement, while in the face of Plyushkin's tragedy, the politeness
would require him to act differently.

Numerically, this passage receives 3/10.

*** Passage VIII

#+begin_quote
(1) Tylko, ojczulku, dla nędzy mojej już dalibyście po czterdzieści
kopiejek.\
(2) Najszacowniejszy! - powiedział Cziczikow - Nie tylko po czterdzieści
kopiejek, ale i po pięćset rubli bym zapłacił. Z zadowoleniem bym
zapłacił, bo widzę: szacowny, zacny starzec cierpi z powodu własnej
zacności.\
(3) A jak Boga kocham, że tak! Bóg widzi, że prawda - powiedział
Pluszkin, zwiesiwszy głowę i z zatroskaniem nią kiwając - Wszystko z
zacności.\
(4) No, sam pan widzi, ja pański charakter od razu przejrzałem. No, więc
czemu bym miał nie dać po pięćset rubli za duszę, ale...majątku nie ma.
Po pięć kopiejek, proszę bardzo, mogę dodać, tak żeby każda dusza w ten
sposób wypadła po trzydzieści kopiejek.\
(5) Ale, ojczulku, z łaski swojej, choć po dwie kopiejki dorzuć.
#+end_quote

In the passage above, we can observe how politeness can be used for
somebody's benefit and to achieve their goals. Chichikov is being very
friendly and polite to Plyushkin to get what he wants. Discussing
linguistic means he is using, we definitely can indicate the usage of
conditional (section 2). He is also referring to Plyushkin's features,
using positive adjectives to describe him: „szacowny,” „zacny” =
„noble”, „worthy”. Chichikov also uses the superlative in the vocative
form when he addresses Plyushkin - „Najszacowniejszy!” = „The most
noble!”. They are not using the „pan” form under the same conditions -
only Chichikov does that. In contrast, Plyushkin calls him in the
diminutive form of „ojczulku,” which may indicate his lower position.

Numerically, this passage receives 8/10.

*** Passage IX

#+begin_quote
(1) No przecież pan zawsze słynął z dobrego zdrowia - powiedział
prezes - i świętej pamięci ojczulek pański był krzepkim człowiekiem.\
(2) A tak, sam na niedźwiedzia chodził - odrzekł Sobakiewicz.\
(3) Wydaje mi się jednak - powiedział prezes - że pan też by
niedźwiedzia powalił, gdyby zechciał pójść po niego.\
(4) Nie, nie powalę - rzekł Sobakiewicz - Nieboszczyk ode mnie
mocniejszy był. - I westchnąwszy, mówił dalej - Nie, teraz ludzie już
nie tacy, no choćby i moje życie, co to za życie?
#+end_quote

Passage IX is a dialogue between two prominent, equal people -
Sobakevich and the chairperson. As it is easy to predict, they are
keeping the form of „pan” in their conversation in such a situation. In
this passage, besides only-linguistic means of expressing politeness, we
can observe how the chairman is trying to please Sobakevich by
mentioning his father and listing his features. He also uses the phrase
„świętej pamięci” (=Eng. „Of blessed memory”), a traditional word being
used to show respect for the dead. By referring to Sobakevich's late
father, showing respect to him, and finally comparing Sobakevich to him,
the chairman tries to make his interlocutor good.

Numerically, this passage receives 7/10.

** Comparative analysis

This chapter is fully dedicated to analyze and compare how, and to what
extent, the level of politeness was maintained in the original text and
translation.

In the table below, we compare the subjective level of politeness using
the numerical scale. The maximum point is 10 (=extremely polite), the
minimum is 0 (=extremely impolite)

#+caption: Politeness scores and their differences
| 死せる魂     | *Original text* | *Translation* | *Difference* |
|--------------+---------------+-------------+------------|
| Passage I    |             9 |          10 |          1 |
| Passage II   |             6 |           9 |          3 |
| Passage III  |             8 |           7 |         -1 |
| Passage IV   |             3 |           3 |          0 |
| Passage V    |             5 |           5 |          0 |
| Passage VI   |             5 |           6 |          1 |
| Passage VII  |             2 |           3 |          1 |
| Passage VIII |             9 |           8 |         -1 |
| Passage IX   |             7 |           7 |          0 |

Let us perform a statistical analysis to see whether we can conclude a
significant difference between the scores above. Let us assume present a
null hypothesis of the translation average score matching the original
text, and the alternative hypothesis would state that it does differ. We
will use the difference scores above and assume William Gosset's sample
t-test statistical hypothesis test under the null hypothesis proposed
above. We have 9 passages, which means we have 8 degrees of
freedom; call it $v$. We compute the mean and standard deviation of
the differences to be $\overline{x} = 0.44$ and $s_{x} = 1.24$,
respectively. Using Student's t-test statistic, we find the t-value,

\begin{align*}
t=\frac{\bar{x}-0}{s_{x} / \sqrt{v+1}}=\frac{0.44}{1.24 / \sqrt{9}} \approx 1.065.
\end{align*}

Using the $t$ value of $1.065$, we can find its respective p-value
to determine whether the change in politeness was significantly observed
in our sample. We find,

\begin{align*}
	p=2 \times \operatorname{Pr}(T[v=8] \geq t)
	 & =2 \times \operatorname{Pr}(T[v=8] \geq 1.065) \\
	 & \approx 2 \times 0.147 \\
	 & =0.294.
\end{align*}

This concludes to be a 29.4% confidence rate of politeness scores
differing in a major way; therefore, we fail to reject the null
hypothesis. We observe that in both the Russian and Polish versions of
Dead souls, politeness scores are significantly similar.

There are a few conclusions we can draw from the presented data. The
general conclusion is that the fluctuations between our subjective
impressions are rather little - usually no more than +/- one point. This
is undoubtedly proof that the translator successfully transferred a
certain level of politeness from one language to another.

In Passage I, we are facing the highest level of politeness from all of
the presented examples. However, the same goal is achieved by using
different means. As a part of the Russian way of expressing politeness,
Manilov is addressing Chichikov using his patronym - Pavel Ivanovich.
This, translated to Polish, would be confusing since the Polish language
does not use patronyms. Still, the translator had to maintain the same
very high level of politeness. To do that, he decided to use the
addressative form of „szanowny panie” - which is not a part of direct
translation but serves as a great substitute in terms of politeness.
Using the form „pan” is a natural choice in Polish conditions as well.

Passage II is the one where we assessed the level of politeness with the
most difference. Sandy, when deciding to give this passage 6 out of 10
points, writes about the lack of direct politeness actions in the
original text. In Polish translation, the level of politeness maintains
very high - using a lot of positive adjectives (also as superlatives)
and a kind of exaggerated kindness makes this particular passage may
seem more polite in Polish than in Russian.

In passage III, we both assessed as very polite. In the Polish version,
the dialogue remains polite even without the form „pan” - but because of
the lack of this form, I decided to subtract one point on my scale. My
subjective, native-Polish speaker opinion, which, however, stems from
the experience of using Polish in both formal and informal ways, is that
resigning from „pan” form is making a whole conversation less formal.
Even if it stays polite, the level of politeness is lowered because of
lacking formality.

Passages IV and V, we both decided to score with equal points. Passage
IV is one of the dialogues we assessed as least polite. In Polish
translation, the translator decided to use the form „ty” instead of
„pan”, but, as I pointed out above, this alone is not enough to make the
conversation impolite. The other factors taken into account while
assessing this passage as impolite were pejorative epithets (in both
versions, like ‘дурак' or ‘dureń') and intensive use of imperative. As
an interesting discovery, I would like to indicate the reverse syntax in
the Polish version, which is making the whole communication almost rude.
In Passage V, we both point out extralinguistic factors as a reason for
lowering the level of politeness in the dialogue.

In Passage VI, one of the factors present in both language versions and
making them more polite is the presence of conditional. Conditional,
hence making the statement less firm, apparently is one of the reasons
why we both decided that this particular passage deserves to be
described as „polite”, even though the sides of the dialogue are
arguing.

Passage VII we both decided to assess as „rather impolite”, giving it
only 2/10 and 3/10. What is interesting is that what decided to give
this passage such a low note are not strictly linguistic factors but the
fact that Chichikov is being happy because of the Plyushkin's loss. In
both cultures, Russian and Polish, such behavior is received as very
impolite.

Passage VIII and IX, once again, we assessed almost equally. Both in the
Russian and Polish versions, we observe the usage of similar linguistic
means, which make the dialogues polite on a comparable level.

** Conclusion

The main goal of the analysis of the particular passages of „Dead souls”
was to examine and compare how politeness is expressed in two
languages - Russian and Polish. By „how” we mean what factors - both
linguistic and extra-linguistic - were used to maintain the same level
of politeness in both versions of the novel.

Moreover, as the socio-linguistic part of this research, we decided to
analyze mentioned passages with regard to politeness theory.

The main conclusion seems to be the fact that the linguistic and
cultural factors which make the particular expressions being received as
polite or impolite are similar in both languages. As main factors we
indicated, among others, using positive adjectives, using conditional,
avoiding using imperative, and using proper syntax. However, due to
different cultures, some of the cultural aspects of politeness could not
be translated directly. The most vivid example is the fact of using
patronyms in Russian culture, which are completely absent in Polish
conditions. The translator decided that the same role in maintaining the
level of politeness expressed by using patronyms may play using the form
„pan”, often followed by „szanowny”.

The main conclusion of this project seems to be the fact that expressing
politeness in two different languages (even if being close to each other
genetically) is not only a matter of language but also culture and other
non-linguistic factors. At the same time, it is possible, taking into
account all possible differences, to transfer the same level of
politeness from one language to another, using the means (again, both
linguistic and extra-linguistic) proper to this particular language and
culture.

** References

- Nikolai Gogol (1842). /Dead Souls./
- Foley, William (1997). /Anthropological Linguistics: An
  introduction./ Blackwell. ISBN 978-0-631-15122-7
- Wiktor Dłuski (2014). Polish translation of /Dead souls. Martwe
  dusze./ Znak. ISBN 978-8-324-03127-6
- Marek Lazinski (2009). /O panach i paniach: polskie rzeczowniki
  tytularne i ich asymetria rodzajowo-plciowa./ Warszawa. ISBN
  978-8-301-14806-5
- M. Henningsen, Politeness theory. M. Allen (Ed.) The SAGE
  Encyclopedia of Research Methods. Thousand Oaks, CA: Sage., 2017.
- E. Goffman, 1967. Interaction Ritual: Essays on Face to Face
  Behaviour. Garden City: New York.
- P. Brown & S. Levinson ,1987. /Politeness/: /Some Universals in
  Language Usage/. Cambridge: Cambridge University Press.
- Żurek, ”Teorie grzeczności językowej” (Eng. „The politeness
  theories”), [in:] Acta Universitatis Wratislavienis, 7 (17), 2008.
- Grabowska-Kiniczuk, "Wszystkie odcienie grzeczności”. Przemiany
  znaczeniowe pojęcia słownikowego od Lindego do Doroszewskiego, [[[https://rcin.org.pl/Content/56582/WA248_68692_P-I-2795_kuniczuk-wszystkie.pdf][access
  online]]].
- M. Marcjanik, /Grzeczność nasza i obca/, Warszawa 2005.
- R. Huszcza, /Honoryfikatywność. Gramatyka, pragmatyka,
  typologia rozdz. Etykieta językowa a honoryfikatywność/, Warszawa
  1996
- M. Marcjanik, /Polska grzeczność językowa/, Kielce 1997.
- /The Editors of Encyclopaedia Britannica. Student's t-test./
  Britannica. [[https://www.britannica.com/science/Students-t-test][https://www.britannica.com/science/Students-t-test]]
- Ronald L. Wasserstein (2016). /The ASA Statement on p-Values:
  Context, Process, and Purpose./ The American Statistician.
  [[https://doi.org/10.1080/00031305.2016.1154108][https://doi.org/10.1080/00031305.2016.1154108]]
