#+setupfile: ../_film.org
#+date: 272; 12025 H.E. 2230
* The Family Man
My first memory of seeing this film comes from college, when my mother
recommended me see this tale of Nicolas Cage finding out the life he had almost
grasped but had let go of with a decision that nobody can really fault him
for. The clips and the general inspiration for the film has been living
rent-free in my mind since then. As corny as it sounds, but that contrast of
Nicolas Cage achieving everything that a mere mortal could, he had only realized
how impoverished his life was when he saw the much boring but much more
fulfilling glimpse into the ``what could have been.''

I have been rather honest of how uncomfortable I am with the idyllic lifestyle
presented through the lens of the American dream. Even so, throughout the entire
duration of the movie, I get such a grin on my face seeing all the goofy,
wholesome, cliché, and hallmark-esque interactions played by Téa Leoni. There is
some inexplicable air of unbound innosence. They really don't make them like
they used to. /The Family Man/ has gotten a membership into my list of comfort
movies.

{{{five}}}
