= Sandy's fortunes 🥠
Sagindyk Urazayev <ctu@ku.edu>
About_LINK | Bookshelf_LINK | Fortunes_LINK | Home_LINK

== 322; 12020 H.E.

Don’t go around saying the world owes you a living. The world owes you
nothing. It was here first.

— Mark Twain

== 318; 12020 H.E.

The only thing we have to fear is fear itself.

— Franklin Delano Roosevelt

== 315; 12020 H.E.

Judge each day not by the harvest you reap, but by the seeds you plant.

— Robert Louis Stevenson (Found on the back of my red wine vinegar
bottle)

== 314; 12020 H.E.

The devil can cite Scripture for his purpose.

— William Shakespeare, “The Merchant of Venice”

== 313; 12020 H.E.

University politics are vicious precisely because the stakes are so
small.

— C. P. Snow (see "Sayre's law")

== 305; 12020 H.E.

It doesn't interest me what you do for a living. I want to know what you
ache for and if you dare to dream of meeting your heart's longing.

It doesn't interest me how old you are. I want to know if you will risk
looking like a fool for love, for your dream, for the adventure of being
alive.

— Oriah Mountain Dreamer

== 303; 12020 H.E.

Liberty lies in the hearts of men and women; when it dies there, no
constitution, no law, no court can save it; no constitution, no law, no
court can even do much to help it.

— Learned Hand, Spirit of Liberty

== 300; 12020 H.E.

For there are moments when one can neither think nor feel. And if one
can neither think nor feel, she thought, where is one?

— Virginia Woolf, "To the Lighthouse"

== 299; 12020 H.E.

Are we THERE yet?

Note: that is actually how I was taught Fundamental theorem of calculus

== 295; 12020 H.E.

When I reflect upon the number of disagreeable people who I know who
have gone to a better world, I am moved to lead a different life.

— Mark Twain, Pudd'nhead Wilson

== 292; 12020 H.E.

Q: How many lawyers does it take to change a light bulb?

A: Whereas the party of the first part, also known as "Lawyer", and the
party of the second part, also known as "Light Bulb", do hereby and
forthwith agree to a transaction wherein the party of the second part
shall be removed from the current position as a result of failure to
perform previously agreed upon duties, i.e., the lighting, elucidation,
and otherwise illumination of the area ranging from the front (north)
door, through the entryway, terminating at an area just inside the
primary living area, demarcated by the beginning of the carpet, any
spillover illumination being at the option of the party of the second
part and not required by the aforementioned agreement between the
parties.

The aforementioned removal transaction shall include, but not be limited
to, the following. The party of the first part shall, with or without
elevation at his option, by means of a chair, stepstool, ladder or any
other means of elevation, grasp the party of the second part and rotate
the party of the second part in a counter-clockwise direction, this
point being tendered non-negotiable. Upon reaching a point where the
party of the second part becomes fully detached from the receptacle, the
party of the first part shall have the option of disposing of the party
of the second part in a manner consistent with all relevant and
applicable local, state and federal statutes. Once separation and
disposal have been achieved, the party of the first part shall have the
option of beginning installation. Aforesaid installation shall occur in
a manner consistent with the reverse of the procedures described in step
one of this self-same document, being careful to note that the rotation
should occur in a clockwise direction, this point also being
non-negotiable. The above described steps may be performed, at the
option of the party of the first part, by any or all agents authorized
by him, the objective being to produce the most possible revenue for the
Partnership.

== 285; 12020 H.E.

Zounds! I was never so bethumped with words since I first called my
brother's father dad.

— William Shakespeare, "Kind John"

== 281; 12020 H.E.

In a mad world, only the mad are sane.

— Akira Kurosawa

== 280; 12020 H.E.

Ours [i.e., the Christian religion] is assuredly the most ridiculous,
the most absurd and the most bloody religion which has ever infected
this world. Your Majesty will do the human race an eternal service by
extirpating this infamous superstition, I do not say among the rabble,
who are not worthy of being enlightened and who are apt for every yoke;
I say among honest people, among men who think, among those who wish to
think. … My one regret in dying is that I cannot aid you in this noble
enterprise, the finest and most respectable which the human mind can
point out.

— Voltaire to Frederick II, 1767

== 278; 12020 H.E.

Go to Heaven for the climate, Hell for the company.

— Mark Twain

== 275; 12020 H.E.

Fate goes ever as fate must.

— Beowulf, 455

== 274; 12020 H.E.

Those who would give up essential Liberty, to purchase a little
temporary Safety, deserve neither Liberty nor Safety.

— Benjamin Franklin

== 273; 12020 H.E.

The meaning of life is that it ends

— Franz Kafka

== 272; 12020 H.E.

Thank goodness technology progressed to the point where we don't have to
deal with our issues privately

== 271; 12020 H.E.

All it takes for evil to succeed, is for good people to say - "It's a
business"

== 265; 12020 H.E.

There are no bad questions, only horrible answers

== 260; 12020 H.E.

Men learn to love the woman they are attracted to. Women learn to become
attracted to the man they fall in love with.

— Woody Allen

== 259; 12020 H.E.

Man plans, God laughs

== 257; 12020 H.E.

No good deed goes unpunished.

== 256; 12020 H.E.

There are no sides in this world, only players

== 249; 12020 H.E.

Nature abhors a vacuum.

— Aristotle

== 248; 12020 H.E.

A wise man can learn more from a foolish question than a fool can learn
from a wise answer.

— Bruce Lee

== 247; 12020 H.E.

Those who abjure violence can do so only because others are committing
violence on their behalf.

— George Orwell

== 241; 12020 H.E.

Misery is wasted on the miserable.

— _Louie_

== 238; 12020 H.E.

Almost nothing great has ever been done in the world except by the
genius and firmness of a single man combating the prejudices of the
multitude.

— Voltaire, correspondence with Catherine the Great

== 237; 12020 H.E.

Most people do not really want freedom, because freedom involves
responsibility, and most people are frightened of responsibility.

— Sigmund Freud, Civilization and Its Discontents

== 236; 12020 H.E.

Вот как нам писать. Пушкин приступает прямо к делу. Другой бы начал
описывать гостей, комнаты, а он вводит в действие сразу

— Л. Н. Толстой (запись в дневнике С. А. Толстой от 19 марта 1873).

== 232; 12020 H.E.

"Internally, Emacs still belives it’s a text program, and we pretend Xt
is a text terminal, and we pretend GTK is an Xt toolkit. It’s a fractal
of delusion."

— marai2 (Hackernews comments)

== 230; 12020 H.E.

Against stupidity the very gods; Themselves contend in vain.

— Friedrich Schiller

== 226; 12020 H.E.

Life is too important to be taken seriously.

— Oscar Wilde

== 223; 12020 H.E.

To live is the rarest thing in the world. Most people exist, that is
all.

— Oscar Wilde

== 222; 12020 H.E.

Be yourself; everyone else is already taken.

— Oscar Wilde

== 219; 12020 H.E.

Let us cultivate our garden.

— Candide

== 214; 12020 H.E.

Religion is like a blind man looking in a black room for a black cat
that isn't there, and finding it.

— Oscar Wilde

== 213; 12020 H.E.

In all the known history of Mankind, advances have been made primarily
in physical technology; in the capacity of handling the inanimate world
about Man. Control of self and society has been left to to chance or to
the vague gropings of intuitive ethical systems based on inspiration and
emotion. As a result no culture of greater stability than about
fifty-five percent has ever existed, and these only as the result of
great human misery.

— Isaac Asimov

== 212; 12020 H.E.

The true delight is in the finding out rather than in the knowing.

— Isaac Asimov

== 207; 12020 H.E.

Excessive bureaucracy is the start of the fall of any civilization

== 206; 12020 H.E.

Все счастливые семьи похожи друг на друга, каждая несчастливая семья
несчастлива по-своему.

— Leo Tolstoy

== 205; 12020 H.E.

It seems to me, Golan, that the advance of civilization is nothing but
an exercise in the limiting of privacy.

— Janov Pelorat, _Foundation’s Edge_

== 204; 12020 H.E.

Any sufficiently advanced technology is indistinguishable from magic.

— Arthur C. Clarke

== 203; 12020 H.E.

If this is the solution, I want my problem back.

— nosystemd.org

== 202; 12020 H.E.

Most people are other people. Their thoughts are someone else's
opinions, their lives a mimicry, their passions a quotation.

— Oscar Wilde

== 201; 12020 H.E.

Never let your sense of morals prevent you from doing what is right

— Isaac Asimov

== 199; 12020 H.E.

Those who can make you believe absurdities can make you commit
atrocities.

— Voltaire

== 197; 12020 H.E.

Violence is the last refuge of the incompetent.

— Isaac Asimov

== 196; 12020 H.E.

Committee, n.:

A group of men who individually can do nothing but as a group decide
that nothing can be done.

– Fred Allen

== Monday, July 6th, 2020

"When I picture it in my head I think of the early web as more of a
library. Over time it has transitioned into a shopping mall."

– chris_f (Hacker News comments)

== Saturday, July 4th, 2020

In each of us sleeps a genius… and his sleep gets deeper everyday.

== Tuesday, June 23, 2020

The galaxies hum the shape and form in their essence. That is their
secret.

The particles whisper of the nature of proper interactions. That is
their game.

And during a storm, in the forest, on the right night, it is no secret
that the leaves all sing of God.

– Exurb1a, _The Fifth Science_

== Tuesday, June 9, 2020

It is by the fortune of God that, in this country, we have three
benefits: freedom of speech, freedom of thought, and the wisdom never to
use either. – Mark Twain

== Wednesday, May 20, 2020

C++ is history repeated as tragedy. Java is history repeated as farce. –
Scott McKay
