* Sandy's fortunes 🥠
*** 248; 12020 H.E.

A wise man can learn more from a foolish question than a fool can learn from a wise answer.

— Bruce Lee

*** 247; 12020 H.E.
 
Those who abjure violence can do so only because others are committing violence on their behalf.

— George Orwell

*** 241; 12020 H.E.
 
Misery is wasted on the miserable. 

— /Louie/

*** 238; 12020 H.E.
 
Almost nothing great has ever been done in the world except by the genius and firmness of a single man combating the prejudices of the multitude.

— Voltaire, correspondence with Catherine the Great

*** 237; 12020 H.E.

Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.

— Sigmund Freud, Civilization and Its Discontents

*** 236; 12020 H.E.
 
    Вот как нам писать. Пушкин приступает прямо к делу. Другой бы начал
    описывать гостей, комнаты, а он вводит в действие сразу 

    — Л. Н. Толстой (запись в дневнике С. А. Толстой от 19 марта 1873).

*** 232; 12020 H.E.

    "Internally, Emacs still belives it’s a text program, and we pretend Xt is a
    text terminal, and we pretend GTK is an Xt toolkit. It’s a fractal of
    delusion."

    — marai2 (Hackernews comments)
    
*** 230; 12020 H.E.
 
    Against stupidity the very gods;
    Themselves contend in vain.

    — Friedrich Schiller

*** 226; 12020 H.E.
 
    Life is too important to be taken seriously.
    
    — Oscar Wilde

*** 223; 12020 H.E.
 
    To live is the rarest thing in the world. Most people exist, that is all.

    — Oscar Wilde

*** 222; 12020 H.E.

    Be yourself; everyone else is already taken.

    — Oscar Wilde

*** 219; 12020 H.E.
    
    Let us cultivate our garden. 
    
    — Candide

*** 214; 12020 H.E.
 
    Religion is like a blind man looking in a black room for a black cat that
    isn't there, and finding it. 

    — Oscar Wilde

*** 213; 12020 H.E.

    In all the known history of Mankind, advances have been made primarily in
    physical technology; in the capacity of handling the inanimate world about 
    Man. Control of self and society has been left to to chance or to the vague 
    gropings of intuitive ethical systems based on inspiration and emotion. As a 
    result no culture of greater stability than about fifty-five percent has
    ever existed, and these only as the result of great human misery. 

    — Isaac Asimov

*** 212; 12020 H.E.

    The true delight is in the finding out rather than in the knowing. 

    — Isaac Asimov

*** 207; 12020 H.E.
 
    Excessive bureaucracy is the start of the fall of any civilization

*** 206; 12020 H.E.
 
    Все счастливые семьи похожи друг на друга, каждая несчастливая семья
    несчастлива по-своему.

    — Leo Tolstoy

*** 205; 12020 H.E.

    It seems to me, Golan, that the advance of civilization is nothing but an
    exercise in the limiting of privacy.  

    — Janov Pelorat, /Foundation’s Edge/

*** 204; 12020 H.E.
 
    Any sufficiently advanced technology is indistinguishable from magic.
    
    — Arthur C. Clarke

*** 203; 12020 H.E.
 
    If this is the solution, I want my problem back.

    — nosystemd.org

*** 202; 12020 H.E.
 
    Most people are other people. Their thoughts are someone else's opinions, their
    lives a mimicry, their passions a quotation. 

    — Oscar Wilde

*** 201; 12020 H.E.
 
    Never let your sense of morals prevent you from doing what is right
    
    — Isaac Asimov
    
*** 199; 12020 H.E.
 
    Those who can make you believe absurdities can make you commit atrocities. 

    — Voltaire

*** 197; 12020 H.E.
 
    Violence is the last refuge of the incompetent.
    
    — Isaac Asimov
    
*** 196; 12020 H.E.

    
    Committee, n.:
    
    A group of men who individually can do nothing but as a group
    decide that nothing can be done.
    
    -- Fred Allen
    
*** Monday, July 6th, 2020

    "When I picture it in my head I think of the early web as more of a
    library. Over time it has transitioned into a shopping mall." 

    -- chris_f (Hacker News comments) 

*** Saturday, July 4th, 2020

    In each of us sleeps a genius... and his sleep gets deeper everyday.

*** Tuesday, June 23, 2020
    
    The galaxies hum the shape and form in their essence. That is their secret.

    The particles whisper of the nature of proper interactions. That is their
    game.

    And during a storm, in the forest, on the right night, it is no secret that
    the leaves all sing of God.
  
    -- Exurb1a, /The Fifth Science/

*** Tuesday, June 9, 2020

    It is by the fortune of God that, in this country, we have three benefits:
    freedom of speech, freedom of thought, and the wisdom never to use either.
    -- Mark Twain

*** Wednesday, May 20, 2020
    
    C++ is history repeated as tragedy. Java is history repeated as farce. 
    – Scott McKay
