* My randomness

- You know what I miracle it is to wake up? You can go to sleep and never wake
  up. It happens pretty often. So when you wake up and feel the sunshine on your
  eyelids, be grateful that you get to experience this beatiful world at least
  one more time. -- Me to my roommate on a Friday morning
- There are only two skills worth developing, empathy and faith. Empathy to
  support others and faith to support yourself.
- It's hard to explain, except by example, but it works. Things just happen in
  the right way, at the right time. At least they do when you let them, when you
  work with circumstances instead of saying, "This isn't supposed to be
  happening this way," and trying hard  to make it happen some other way. If
  you're in tune with The Way Things Work, then they work the way they need to,
  no matter what you may think about it at the time. -- /The Tao of Pooh/
- /What day is it?/, asked Pooh. /Why, it's Today!/, squeaked Piglet. /My
  favorite day/, said Pooh.
