= My randomness
Sagindyk Urazayev <ctu@ku.edu>
LinkedIn_LINK | GitHub_LINK | Resume_LINK | PGP Key_LINK | Home_LINK
:toc: left
:toc-title: Table of Adventures

* You know what I miracle it is to wake up? You can go to sleep and
never wake up. It happens pretty often. So when you wake up and feel the
sunshine on your eyelids, be grateful that you get to experience this
beatiful world at least one more time. – Me to my roommate on a Friday
morning
* There are only two skills worth developing, empathy and faith. Empathy
to support others and faith to support yourself.
* It's hard to explain, except by example, but it works. Things just
happen in the right way, at the right time. At least they do when you
let them, when you work with circumstances instead of saying, "This
isn't supposed to be happening this way," and trying hard to make it
happen some other way. If you're in tune with The Way Things Work, then
they work the way they need to, no matter what you may think about it at
the time. – _The Tao of Pooh_
* _What day is it?_, asked Pooh. _Why, it's Today!_, squeaked Piglet.
_My favorite day_, said Pooh.
* An Empty sort of mind is valuable for finding pearls and tails and
things because it can see what's in front of it. An Overstuffed mind is
unable to. While the Clear mind listens to a bird singing, the
Stuffed-Full-of-Knowledge-and-Cleverness mind wonders what kind of bird
is singing. Tho more Stuffed Up it is, the less it can hear through its
own ears and see through its own eyes.
