* Sandy's Fortunes 🧧
** 333; 12023 H.E.
 
``But man is not made for defeat,'' he said. ``A man can be destroyed but not defeated.''

― Ernest Hemingway, /The Old Man and the Sea/

** 331; 12023 H.E.
 
“You have never loved me. You have only thought it pleasant to be in love with me.”
― Henrik Ibsen, /A Doll's House/

** 330; 12023 H.E.
 
There are few of us who have not sometimes wakened before dawn, either after one of those dreamless nights that make us almost enamored of death, or one of those nights of horror and misshapen joy, when through the chambers of the brain sweep phantoms more terrible than reality itself, and instinct with that vivid life that lurks in all grotesques, and that lends to Gothic art its enduring vitality, this art being, one might fancy, especially the art of those who minds have been troubled with the malady of reverie. Gradually white fingers creep through the curtains, and they appear to tremble. In black, fantastic shapes, dumb shadows crawl into the corners of the room, and crouch there. Outside, there is the stirring of the birds among the leaves, or the sound of men going forth to their work, or the sigh and sob of the wind coming down from the hills and wandering round the silent house, as though it feared to wake the sleeper, and yet must needs call forth Sleep from her purple cave. Veil after veil of thin, dusky gauze is lifted, and by degrees the forms and colors of things are restored to them, and we watch the dawn remaking the world in its antique pattern. The wan mirrors get back their mimic life. The flameless tapers stand where we had left them, and beside them lies the half-cut book that we had been studying, or the wired flower that we had worn at the ball, or the letter we had been afraid to read, or that we had read too often. Nothing seems to us changed. Out of the unreal shadows of the night comes back the real life that we had known. We have to resume it where we had left off, and there steals over us a terrible sense of the necessity for the continuance of energy in the same wearisome round of stereotyped habits, or a wild longing, it may be, that our eyelids might open some morning upon a world that had been refashioned anew in the darkness for our pleasure, a world in which things would have fresh shapes and colors, and be changed, or have other secrets, a world in which the past would have little or no place, or survive, at any rate, in no conscious form of obligation or regret, the remembrance even of joy having its bitterness, and the memories of pleasure their pain.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.

``There is no such thing as a good influence, Mr. Gray. All influence is
immoral-immoral from the scientific point of view.''\
``Why?''\
``Because to influence a person is to give him one's own soul. He does not think
his natural thoughts, or burn with his natural passions. His virtues are not
real to him. His sins, if there are such things as sins, are borrowed. He
becomes an echo of some one else's music, an actor of a part that has not been
written for him. The aim of life is self-development. To realize one's nature
perfectly—that is what each of us is here for. People are afraid of themselves
nowadays. They have forgotten the highest of all duties, the duty that one owes
to one's self. Of course they are charitable. They feed the hungry and cloth the
beggar. But their own souls starve, and are naked. Courage has gone out of our
race. Perhaps we never really had it. The terror of society, which is the basis
of morals; the terror of God, which is the secret of religion—these are the two
things that govern us. And yet—''\
``And yet," continues Lord Henry, in his low, musical voice,"I believe that if
one man were to live out his life fully and completely, were to give form to
every feeling, expression to every thought, reality to every dream—I believe
that the world would gain such a fresh impulse of joy that we would forget all
the maladies of mediaevalism, and return to the Hellenic ideal—to something
finer, richer than the Hellenic ideal, it may be. But the bravest man among us
is afraid of himself. The mutilation of the savage has its tragic survival in
the self-denial that mars our lives. We are punished for our refusals. Every
impulse that we strive to strangle broods in the mind and poisons us. The body
sins once, and has done with its sins, for action is a mode of
purification. Nothing remains then but the recollection of a pleasure, or the
luxury of a regret. The only way to get rid of a temptation is to yield to
it. Resist it, and your soul grows sick with longing for the things it has
forbidden to itself, with desire for what its monstrous laws have made monstrous
and unlawful. It has been said that the great events of the world take place in
the brain. It is in the brain, and the brain only, that the great sins of the
world take place also. You, Mr. Gray, you yourself, with your rose-red youth and
your rose-white boyhood, you have had passions that have made you afraid,
thoughts that have filled you with terror, day-dreams and sleeping dreams whose
mere memory might stain your cheek with shame—''\
``Stop!'' faltered Dorian Gray, ``stop! you bewilder me. I don't know what to
say. There is some answer to you, but I cannot find it. Don't speak. Let me
think, or, rather, let me try not to think.''

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
``what brings you out so early? I thought you dandies never got up till two, and
were not visible till five.''

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
When a woman marries again, it is because she detested her first husband. When a
man marries again, it is because he adored his first wife. Women try their luck;
men risk theirs.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
She is very clever, too clever for a woman. She lacks the indefinable charm of
weakness.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
I love acting. It is so much more real than life.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
Men marry because they are tired; women, because they are curious: both are
disappointed.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
A man can be happy with any woman as long as he does not love her.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
Those who find ugly meanings in beautiful things are corrupt without being
charming. This is a fault. Those who find beautiful meanings in beautiful things
are the cultivated. For these there is hope. They are the elect to whom
beautiful things mean only Beauty. There is no such thing as a moral or an
immoral book. Books are well written, or badly written. That is all.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
Humanity takes itself too seriously. It is the world's original sin. If the
cave-man had known how to laugh, History would have been different.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
The only way to get rid of temptation is to yield to it.

― Oscar Wilde, /The Picture of Dorian Gray/

** 330; 12023 H.E.
 
She behaves as if she was beautiful. Most American women do. It is the secret of
their charm.

— Oscar Wilde, /The Picture of Dorian Gray/

** 326; 12023 H.E.
 
As a matter of fact, political obfuscation has tended to use many words rather
than few, long words rather than short, to extend rather than to reduce. Every
leader of inadequate education or limited intelligence hides behind exuberant
inebriation of loquacity.

— Isaac Asimov, /REVIEW OF 1984/

** 324; 12023 H.E.
 
``The surest way to become Tense, Awkward, and Confused is to develop a mind
that tries too hard - one that thinks too much.''

― Benjamin Hoff, The Tao of Pooh

** 316; 12023 H.E.
 
I Yam What I Yam

— /Popeye the Sailor/

** 308; 12023 H.E.

No star deviates from its path.

** 305; 12023 H.E.
 
My fortune cookie of “Pumpkin” today said, “Past experience: He who never makes mistakes never did anything that’s worthy.”

** 304; 12023 H.E.
 
To Let The World Be

** 294; 12023 H.E.

Childhood is the writer’s bank balance.

— Graham Greene

** 258; 12023 H.E.
 
I do not know myself and God forbid that I should.

— Johann Wolfgang von Goethe

** 248; 12023 H.E.
 
A baby is God's opinion that the world should go on.

— Carl Sandburg

** 246; 12023 H.E.

Life should not be a journey to the grave with the intention of arriving safely
in a pretty and well preserved body, but rather to skid in broadside in a cloud
of smoke, thoroughly used up, totally worn out, and loudly proclaiming "Wow!
What a Ride!

— Hunter S. Thompson

** 246; 12023 H.E.
 
You're not my type.  For that matter, you're not even my species!!!

** 238; 12023 H.E.
 
Everything takes longer, costs more, and is less useful.

--- Erwin Tomash

** 235; 12023 H.E.
 
The degree of civilization in a society can be judged by entering its prisons.

--- Fyodor Dostoyevsky

** 228; 12023 H.E.

``Consciousness of life is higher than life, knowledge of the laws of happiness
is higher than happiness''—that is what we must fight against!

--- /The Dream of a Ridiculous Man/

** 227; 12023 H.E.
 
Boring is good. Boring is stable. Boring means being able to focus on your work,
not on what’s different about Go.

--- Russ Cox, /Backward Compatibility, Go 1.21, and Go 2/

** 221; 12023 H.E.
 
Einstein argued that there must be simplified explanations of nature, because
God is not capricious or arbitrary.  No such faith comforts the software
engineer.

--- Fred Brooks, Jr.

** 218; 12023 H.E.
 
Death before dishonor.  But neither before breakfast.

** 215; 12023 H.E.
 
My father, a good man, told me, "Never lose your ignorance; you cannot
replace it."

--- Erich Maria Remarque

** 189; 12023 H.E.
 
If you bring a polygraph to a date, don't expect a second one.

— Ishigami, best girl, /Kaguya-sama/

** 186; 12023 H.E.
 
Okay, asking somebody how long they believed in Santa Claus is so stupid, you
can't even consider the topic suitable for idle conversation. But if you still
wanna know how long I believed in some old fat guy who wears a funky red suit, I
can tell you this: I've never believed in him, ever. The Santa that showed up at
my kindergarten Christmas festival, I knew he was fake. And I never saw mommy
kissing Santa or anything. But I have to say, that even as a little kid, I knew
better than to believe in some old man that only worked one day a year. Now,
having said that, it wasn't until I got older that I realized that aliens, time
travelers, ghosts, monsters, espers, the evil syndicates and the
anime/manga/fantasy flick heroes that fight said evil syndicates, were also
fake. Okay, I guess I always knew those things were bogus, I just didn't wanna
admit it. All I ever wanted was for an alien, time traveler, ghost, monster,
esper, evil syndicate, or the hero that fought them to just appear and say
"Hey". Unfortunately, reality is a hard road indeed. Yep, you gotta admit, the
laws of physics definitely puts a damper on things. I even stopped watching
those TV shows about aliens and ghosts and stuff. Aliens, time travelers,
espers; of course they don't exist, but a little part of me wishes that they
did. I guess I've grown up and realized I can think about those things and still
accept reality. But by the time I got out of junior high, I pretty much outgrew
that kind of stuff and I guess I got used to the idea of living in an ordinary
world. Just like that, I was in high school...that's when I met her.

— Kyon, /The Melancholy of Haruhi Suzumiya/

** 185; 12023 H.E.
 
Problems that cannot be solved do not exist in this world. 

— /The melancholy of Suzumiya Haruhi/

** 171; 12023 H.E.
 
There are still so many things I want to do.\
I want to decide my future for myself!\
I don't want others to decide it for me!\
Even if I died doing that, I'd have no regrets!\

— Tetsuro, /Galaxy Express 999/

** 143; 12023 H.E.
 
A shepherd dressed in his Sunday's finest still reeks of lamb.

— Gundham Tanaka

** 140; 12023 H.E.
 
I must not fear. Fear is the mind-killer. Fear is the little-death that brings
total obliteration. I will face my fear. I will permit it to pass over me and
through me. And when it has gone past I will turn the inner eye to see its
path. Where the fear has gone there will be nothing. Only I will remain.

— Frank Herbert

** 98; 12023 H.E.

There are three kinds of lies: lies, damned lies, and statistics

--- Mark Twain

** 91; 12023 H.E.
 
When the world zigs. Zag.

** 57; 12023 H.E.
 
When I was a boy of fourteen, my father was so ignorant I could hardly stand to
have the old man around. But when I got to be twenty-one, I was astonished at
how much the old man had learned in seven years.

--- Mark Twain, /probably/

** 50; 12023 H.E.

--- ``Now, I don't know if you're all
aware of this, but Ghibli films...
only air on NTV. Why is that?
Can you tell us?''\
--- ``We value friends, I guess.
I don't know if the term
"friends" is appropriate,
but at Ghibli we do value
human relationships.
It's not about just working
with market share leaders.'' (Shinsuke Nonaka)\
--- ``Here's an extreme example.
Only slightly exaggerated.
Okuda became our NTV contact.
Since then,
for the 20 years or so that
he's worked with Ghibli,
he has visited us every night.\
Never talked about work.
But we talked about
lots of different things,
which led to talking
about family, naturally.
That's what gave birth
to Spirited Away.\
When Okuda's daughter turned ten,
Miyazaki had a cabin
in the mountains,
and he invited them there.
So they spent some time there.
That experience is what motivated
Miyazaki to make Spirited Away.\
I'll say this,
based on my experience.
In your work, obviously,
you'll meet many people.
But ultimately, it's about
who you work with.
Only those who choose
the right people to work with
will be able to do
the work they want.''

--- Toshio Suzuki, /The Kingdom of Dreams and Madness/ 

** 50; 12023 H.E.

You know, sometimes I might think...
about the world ending or something.
I'd never say that to a child.
This is important.
Children are what keep me going.
Not any particular child,
children in general.
In December, we bring out the goats.
The kids remember them.
When they're gone, they notice.
Kids really remember things, you see.
Problems begin
the moment we're born.
We're born with
infinite possibilities,
only to give up on
one after another.
To choose one thing means
to give up on another.
That's inevitable.
But what can you do?
That's what it is to live.

--- Hayao Miyazaki, /The Kingdom of Dreams and Madness/

** 50; 12023 H.E.
 
--- ``You know, people who design
airplanes and machines...
No matter how much they believe
that what they do is good,
the winds of time eventually
turn them into tools
of industrial civilization.
It's never unscathed.
They're cursed dreams.
Animation, too.''\
--- ``Cursed dreams?'' (Mami Sunada)\
--- ``Today, all of humanity's dreams
are cursed somehow.
Beautiful yet cursed dreams.
I'm not even talking about
wanting to be rich or famous.
Screw that.
That's just hopeless.
What I mean is, how do we know
movies are even worthwhile?
If you really think about it,
is this not just some grand hobby?
Maybe there was a time when you could
make films that mattered, but now?
Most of our world is rubbish.
It's difficult.''

--- Hayao Miyazaki, /The Kingdom of Dreams and Madness/

** 30; 12023 H.E.
 
И жить торопится, и чувствовать спешит.

--- Вяземский, Пётр Андреевич

** 29; 12023 H.E.

Блажен, кто смолоду был молод,\
Блажен, кто вовремя созрел,\
Кто постепенно жизни холод\
С летами вытерпеть умел;\
Кто странным снам не предавался,\
Кто черни светской не чуждался,\
Кто в двадцать лет был франт иль хват,\
А в тридцать выгодно женат;\
Кто в пятьдесят освободился\
От частных и других долгов,\
Кто славы, денег и чинов\
Спокойно в очередь добился,\
О ком твердили целый век:\
N. N. прекрасный человек.\

--- Глава восьмая, X, /Евгений Онегин/

** 25; 12023 H.E.
 
Never forget, a believing heart is your magic.

--- Ursula Callistis

** 1; 12023 H.E.
 
If you ask me, only after one dies and comes back to life do they become a normal person!

--- Lalaco Godspeed

** 360; 12022 H.E.
 
What a fine weather today! Can’t choose whether to drink tea or to hang myself.

--- Anton Chekhov

** 358; 12022 H.E.
 
В жизни нет сюжетов, в ней все смешано — глубокое с мелким, великое с ничтожным, трагическое со смешным.

--- Антон Чехов

** 357; 12022 H.E.
 
Do silly things. Foolishness is a great deal more vital and healthy than our straining and striving after a meaningful life.

--- Anton Chekhov

** 356; 12022 H.E.
 
Everything is beautiful in this world…except that we think and do ourselves when we forget our human dignity and the higher aims of our existence.

--- Anton Chekhov

** 356; 12022 H.E.
 
Man is what he believes. 

--- Anton Chekhov

** 346; 12022 H.E.
 
Eat drink and be merry, for tomorrow they may make it illegal.

** 342; 12022 H.E.
 
People who are never satisfied with what surrounds them are jealous of others who can live and enjoy things for what they are.

** 338; 12022 H.E.
 
You know, God already made an apple, a tomato, rice. Those are perfect in themselves and we cannot improve them. The best we can do is strive toward that greatness.

** 338; 12022 H.E.
 
Someone asked me, "What are humanity's best inventions?" -- probably expecting
me to say something around the Internet or computers.

Come to think of it, I can imagine my life without tech and computers -- it
wouldn't be much of a problem, quite the opposite. Wouldn't that be nice. 

But things that I truly cannot imagine living without, which are essintial to
survival include: refrigerator, dish soap, white vinegar, penicillin, and anime. 

** 319; 12022 H.E.
 
[speaking of snow] It’s completely melted here now which is a shame but there’s value in an ephemeral beauty I suppose

--- Katie Zimmerman

** 317; 12022 H.E.
 

I was taking a nap tonight around six and somewhere deep down in the dream I was in, it hit me — “I was dreaming.” I felt my unconscious body laying and the mind actively burning calories and sugar giving me this more-vivid-than-life moving picture. I consciously decided to wake myself up by scaring myself with the most profound abstract sensation of fear I could think of. The wake didn’t come. Just for a moment, I was stuck in the nightmare of my own making. In that fleeting blip, I thought to myself, “Is this what Hell is?” The kingdom of self-made fears locked up with a key that was never to be found. It is up to you to make escape but it is never guaranteed.

** 316; 12022 H.E.
 
Ignore previous fortune.

** 314; 12022 H.E.
 
Due to a shortage of devoted followers, the production of great leaders has been discontinued.

** 311; 12022 H.E.
 
You can only drink kool aid if you make it yourself. You should not drink it if it’s made by someone else, brewed over time — you don’t know what went into it or who touched it and put what in there

--- Joseph Laycock

** 310; 12022 H.E.
 
“at the end of the day, rascal may not dream of bunny girl senpai, but dear lord I fucking do”

--- Jame, bestie

** 308; 12022 H.E.
 
It’s raining, MY GOD I love rain. I woke up today and felt this gloomy and more
melancholic vibe in the air. My bedroom is darker than usual. It’s chillier than
usual. The air smells like pure bliss. Time goes slower. Tiny notes of romance
are floating in the aura around. They’re so subtle that be sure to feel them
through or you’ll miss out. What a weather, what a morning. What a day! Did I
tell you it’s also going to rain for the rest of the day? It will! I love
this. I love this. Thank you. God’s in his Heaven; all is right with the
world. ``What day is it?'' asked Pooh. ``It's today,'' squeaked Piglet. ``My
favorite day,'' said Pooh.

** 305; 12022 H.E.
 
paycheck:\
 The weekly $5.27 that remains after deductions for federal
 withholding, state withholding, city withholding, FICA,
 medical/dental, long-term disability, unemployment insurance,
 Christmas Club, and payroll savings plan contributions.

** 303; 12022 H.E.
 
Love is an ideal thing, marriage a real thing; a confusion of the real with the ideal never goes unpunished.

--- Goethe

** 302; 12022 H.E.
 
The world really isn't any worse.  It's just that the news coverage is so much better.

** 298; 12022 H.E.
 
If you know exactly where you’re headed, it’s no fun at all.

--- Yukihira Soma

** 295; 12022 H.E.
 
Murder is always a mistake -- one should never do anything one cannot talk about after dinner.

--- Oscar Wilde, /The Picture of Dorian Gray/

** 294; 12022 H.E.
 
statistics, n.:\
A system for expressing your political prejudices in convincing scientific guise.

** 293; 12022 H.E.
 
``I love mankind,'' he said, ``but I find to my amazement that the more I love
mankind as a whole, the less I love man in particular.''

--- Fyodor Dostoyevsky, /The Brothers Karamazov/

** 290; 12022 H.E.
 
Beauty, n.: \ 
 The power by which a woman charms a lover and terrifies a husband.

--- Ambrose Bierce

** 288; 12022 H.E.
 
Excellent day for drinking heavily. Spike the office water cooler.

** 287; 12022 H.E.
 
Any fool can tell the truth, but it requires a man of sense to know
how to lie well.

--- Samuel Butler

** 285; 12022 H.E.
 
The universe is ruled by letting things take their course.  It cannot be
ruled by interfering.

--- Chinese proverb

** 283; 12022 H.E.
 
Love in action is a harsh and dreadful thing compared to love in dreams. 

--- Fyodor Dostoevsky

** 279; 12022 H.E.
 
Please remain calm, it's no use both of us being hysterical at the same time.

** 276; 12022 H.E.
 
I don't have any solution but I certainly admire the problem.

--- Ashleigh Brilliant

** 274; 12022 H.E.

Wasting time is an important part of living.

** 272; 12022 H.E.
 
There are three things men can do with women: love them, suffer for them,
or turn them into literature.

--- Stephen Stills

** 271; 12022 H.E.
 
God's in his heaven --\ All's right with the world!

** 269; 12022 H.E.
 
None of us have a complete grasp on the truth, and some extra statistics don't change that. 

--- Matthew Hayman

** 205; 12022 H.E.
 
The end will surely come. Only those who were able to face the truth that it will come to them will be able to find it. What it is that proves you're alive. I have found it, too.

--- Aegis, /Persona 3 the Movie 4: Winter of Rebirth/

** 192; 12022 H.E.
 
We must be idealistic realists. Pure realists without dreams are a dime a
dozen. Pure realists are the worst. I don't want our team to be like that.  

--- Hayao Miyazaki

** 145; 12022 H.E.
 
Only an unhappy person will ponder about the meaning of life and happiness. A happy person has no time nor needs for those cursed questions.

** 141; 12022 H.E.
 Reading may well be the only true magic. 

--- Alice Hoffman

** 122; 12022 H.E.
 
If God did not exist, it would be necessary to invent him.

--- Voltaire

** 101; 12022 H.E.
 
If you talk to a man in a language he understands, that goes to his head. If you talk to him in his own language, that goes to his heart.

--- Nelson Mandela

** 97; 12022 H.E.
 
*I live for Najimi*

** 87; 12022 H.E.
 
Sandy single handedly runs an intelligence network comparable of that to WW2 britain but the only intelligence he deals in is anime pics

--- Ethan

** 82; 12022 H.E.

It is no nation that we inhabit, but a language.\
Make no mistake; our native toungue is our true fatherland.

--- Emil Cioran

** 72; 12022 H.E.

Wahahahahaha! My name is Megumin, the number one mage of Axel! Come, you shall all become my experience points today!

--- Megumin, best girl

** 69; 12022 H.E.

*nice*

** 59; 12022 H.E.

I'm useless and a masochist inside

** 58; 12022 H.E.

Happy is the man who has broken the chains which hurt the mind, and has given up worrying once and for all.

Be patient and tough; one day this pain will be useful to you.

--- Ovid, /Metamorphoses/

** 51; 12022 H.E.

What I think, Sakuta-kun, is that life is here for us to become kinder. I live life every day hoping I was a slightly kinder person than I was the day before.

--- Shoko Makinohara

** 45; 12022 H.E.
 
Rumbling by SiM goes so hard

** 15; 12022 H.E.
 
My soldiers, rage!\
My soldiers, scream!\
My soldiers, fight!\

--- Erwin Smith, best commander

** 14; 12022 H.E.

SHINZO WO SASAGEYO

--- Erwin Smith

** 13; 12022 H.E.

Courage is not the absence of fear, it is acting in spite of it.

--- Mark Twain or Shakespeare

** 10; 12022 H.E.

I'm a gambling man

** 1; 12022 H.E.
 
The moment of truth.

** 357; 12021 H.E.
 
Easy times breed weak men.

--- Wesley Sportsman

** 351; 12021 H.E.
 
We seldom repent talking too little, but very often talking too much.

--- Jean de la Bruyere

** 349; 12021 H.E.
 

In 2021 I laughed 😂😂 I cried 😢😖 turned up 👆💃🏻💁‍♀️ turned down 👇🙅‍♀️ I loved 👩‍❤️‍👨👫👨‍🦰👩‍🦰👧 I lost trust 💔😩 I was betrayed 😒🔪 but most importantly I learned 😌

** 322; 12021 H.E.
 
*YOLO*

** 320; 12021 H.E.
 
A journey of a thousand miles must begin with a single step.

--- Lao Tzu

** 300; 12021 H.E.
 
Nature never hurries. Atom by atom, little by little she achieves her work.

--- Ralph Waldo Emerson

** 296; 12021 H.E.
 
We sometimes encounter people, even perfect strangers, who begin to interest us at first sight, somehow suddenly, all at once, before a word has been spoken.

--- Dostoevsky, /Crime and Punishment/

** 290; 12021 H.E.
 
In vain I have struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.

--- Mr. Darcy

** 290; 12021 H.E.
 
We all know him to be a proud, unpleasant sort of man; but this would be nothing if you really liked him.

--- Mr. Darcy

** 290; 12021 H.E.
 
You are too generous to trifle with me. If your feelings are still what they were last April, tell me so at once. My affections and wishes are unchanged; but one word from you will silence me on this subject for ever.

--- Mr. Darcy

** 290; 12021 H.E.
 
I have faults enough, but they are not, I hope, of understanding. My temper I dare not vouch for. It is, I believe, too little yielding— certainly too little for the convenience of the world. I cannot forget the follies and vices of other so soon as I ought, nor their offenses against myself. My feelings are not puffed about with every attempt to move them. My temper would perhaps be called resentful. My good opinion once lost, is lost forever.

--- Mr. Darcy

** 290; 12021 H.E.
 
She is tolerable, but not handsome enough to tempt me, and I am in no humor at present to give consequence to young ladies who are slighted by other men.

--- Mr. Darcy

** 289; 12021 H.E.
 
Better by far you should forget and smile than that you should remember
and be sad.

--- Christina Rossetti

** 287; 12021 H.E.
 
Congratulations are in order for Tom Reid.

He says he just found out he is the winner of the 2024 Psychic of the
Year award.

** 286; 12021 H.E.
 
He was so narrow-minded he could see through a keyhole with both eyes.

** 284; 12021 H.E.
 
We’re in no rush

--- Kate

** 283; 12021 H.E.
 
If you don't know what game you're playing, don't ask what the score is.

** 282; 12021 H.E.
 
When your work speaks for itself, don't interrupt.

--- Henry J. Kaiser

** 281; 12021 H.E.
 
The older I grow, the less important the comma becomes.  Let the reader
catch his own breath.

--- Elizabeth Clarkson Zwart

** 280; 12021 H.E.
 
Education is an admirable thing, but it is well to remember from time to
time that nothing that is worth knowing can be taught.

--- Oscar Wilde, "The Critic as Artist"

** 280; 12021 H.E.
 
Don't despair; your ideal lover is waiting for you around the corner.

** 277; 12021 H.E.
 
Millions long for immortality who do not know what to do with themselves on a
rainy Sunday afternoon.

--- Susan Ertz

** 275; 12021 H.E.
 
The chief danger in life is that you may take too many precautions.

--- Alfred Adler

** 274; 12021 H.E.
 
Not far from here, by a white sun, behind a green star, lived the
Steelypips, illustrious, industrious, and they hadn't a care: no spats in
their vats, no rules, no schools, no gloom, no evil influence of the
moon, no trouble from matter or antimatter -- for they had a machine, a
dream of a machine, with springs and gears and perfect in every respect.
And they lived with it, and on it, and under it, and inside it, for it
was all they had -- first they saved up all their atoms, then they put
them all together, and if one didn't fit, why they chipped at it a bit,
and everything was just fine ...

--- Stanislaw Lem, "Cyberiad"

** 272; 12021 H.E.

Всегда доходит до того крайнего предела, где каждая форма так таинственно уподобляется своей противоположности, что эта действительность всякому обыденному, привыкшему к среднему уровню взору представляется фантастической.

--- Стефан Цвейг о реализме Достоевского

** 271; 12021 H.E.
 
It is common sense to take a method and try it.  If it fails,
admit it frankly and try another.  But above all, try something.

--- Franklin D. Roosevelt

** 271; 12021 H.E.
 
Just to have it is enough.

** 267; 12021 H.E.
 
A lost ounce of gold may be found, a lost moment of time never.

** 266; 12021 H.E.
 
He who is known as an early riser need not get up until noon.

** 265; 12021 H.E.
 
We should be careful to get out of an experience only the wisdom that is
in it - and stay there, lest we be like the cat that sits down on a hot
stove-lid.  She will never sit down on a hot stove-lid again - and that
is well; but also she will never sit down on a cold one any more.

--- Mark Twain

** 263; 12021 H.E.
 
Rune's Rule:

If you don't care where you are, you ain't lost.

** 260; 12021 H.E.
 
I allow myself to be decadent

** 259; 12021 H.E.
 
Nonsense and beauty have close connections.

--- E.M. Forster

** 258; 12021 H.E.
 
skldfjkljklsR%^&(IXDRTYju187pkasdjbasdfbuil
h;asvgy8p 23r1vyui135 2
kmxsij90TYDFS$$b jkzxdjkl bjnk ;j nk;<[][;-==-<<<<<';[,
  [hjioasdvbnuio;buip^&(FTSD$%*VYUI:buio;sdf}[asdf']
    sdoihjfh(_YU*G&F^*CTY98y


Now look what you've gone and done!  You've broken it!

** 257; 12021 H.E.
 
Science and religion are in full accord but science and faith are in complete discord.

** 256; 12021 H.E.
 
Consider well the proportions of things.  It is better to be a young June-bug
than an old bird of paradise.

--- Mark Twain, "Pudd'nhead Wilson's Calendar"

** 255; 12021 H.E.

Я видел пьяниц с мудрыми глазами\
И падших женщин с ликом чистоты.\
Я знаю сильных, что взахлёб рыдали\
И слабых, что несут кресты.\

Не бойся вора в нищенском обличьи,\
И проклинать за мелочь, не спеши-\
Ты бойся тех, кто выглядит прилично,\
Вор с праведным лицом уносит часть души.\

Не обвиняй во всех грехах соседа,\
Интриг не строй и сплетен не плети!\
Воздастся добротой тебе за это,\
Когда споткнёшься на своём пути.\


Не осуждай за то, в чём не уверен;\
Не обещай, если решил солгать.\
Не проверяй, когда уже доверил!\
И не дари, планируя отнять.\

--- Серге́й Алекса́ндрович Есе́нин

** 254; 12021 H.E.
 
Of all men's miseries, the bitterest is this:
to know so much and have control over nothing.

--- Herodotus

** 253; 12021 H.E.
 
Ambition is a poor excuse for not having sense enough to be lazy.

--- Charlie McCarthy

** 251; 12021 H.E.
 
He who wonders discovers that this in itself is wonder.

--- M.C. Escher

** 250; 12021 H.E.
 
It isn't easy being a Friday kind of person in a Monday kind of world.

** 249; 12021 H.E.
 
Your happiness is intertwined with your outlook on life.

** 248; 12021 H.E.
 
A well-known friend is a treasure.

** 246; 12021 H.E.
 
The master programmer moves from program to program without fear.  No
change in management can harm him.  He will not be fired, even if the project
is canceled. Why is this?  He is filled with the Tao.

--- Geoffrey James, "The Tao of Programming"

** 245; 12021 H.E.
 
While any text editor can save your files, only Emacs can save your soul

** 243; 12021 H.E.
 
If you are afraid of loneliness, don't marry.

--- Anton Chekhov

** 242; 12021 H.E.
 
It is contrary to reasoning to say that there is a vacuum or space in
which there is absolutely nothing.

--- Descartes

** 241; 12021 H.E.
 
Clothes make the man.  Naked people have little or no influence on society.

--- Mark Twain

** 235; 12021 H.E.
 
Virtue does not always demand a heavy sacrifice -- only the willingness
to make it when necessary.

--- Frederick Dunn

** 233; 12021 H.E.
 
The ability to play chess is the sign of a gentleman. The ability to play chess well is the sign of a wasted life.

— Paul Morphy

** 228; 12021 H.E.
 
today, n.:

A nice place to visit, but you can't stay here for long.

** 226; 12021 H.E.
 
I have the simplest tastes. I am always satisfied with the best.

--- Oscar Wilde

** 201; 12021 H.E.
 
I love you and you are loved

--- Sandy

** 200; 12021 H.E.
 
Govern a great nation as you would cook a small fish.  Don't overdo it.

--- Lao Tzu

** 199; 12021 H.E.
 
A good name lost is seldom regained.  When character is gone,
all is gone, and one of the richest jewels of life is lost forever.

--- J. Hawes

** 198; 12021 H.E.
 
Жизнь, по сути, очень простая штука и человеку нужно приложить много усилий, чтобы её испортить.

--- Чехов

** 197; 12021 H.E.
 
Bizarreness is the essence of the exotic.

** 196; 12021 H.E.
 
Most of the fear that spoils our life comes from attacking difficulties
before we get to them.

--- Dr. Frank Crane

** 194; 12021 H.E.
 
You can't get very far in this world without your dossier being there first.

--- Arthur Miller

** 192; 12021 H.E.
 
He who knows, does not speak.  He who speaks, does not know.

--- Lao Tsu

** 191; 12021 H.E.
 
Documentation:\
 Instructions translated from Swedish by Japanese for English
 speaking persons.

** 190; 12021 H.E.
 
Someday somebody has got to decide whether the typewriter is the machine,
or the person who operates it.

** 188; 12021 H.E.
 
The hatred of relatives is the most violent.

--- Tacitus (c.55 - c.117)

** 187; 12021 H.E.
 
You can tell the ideals of a nation by its advertisements.

--- Norman Douglas

** 186; 12021 H.E.
 
Fare thee well, and if for ever,\
Still for ever, fare thee well.

--- Byron

** 186; 12021 H.E.
 
"Сознание жизни  выше жизни, знание  законов  счастья--выше счастья" -- вот с чем  бороться  надо! И буду.  Если  только все захотят, то сейчас все устроится.

--- Fyodor Dostoevsky, /The Dream of a Ridiculous Man/

** 184; 12021 H.E.
 
So many people are stuck living the same life because they think that is what they're supposed to do. But really, you're just completely free to do it. You are able to do it. And even if its a different and more difficult road to take, I believe you should do if it's going to make you happy.

--- Marzia Kjellberg

** 184; 12021 H.E.
 
One good turn usually gets most of the blanket.

** 182; 12021 H.E.
 
Some people cause happiness wherever they go; others, whenever they go.

** 179; 12021 H.E.
 
A master programmer passed a novice programmer one day.  The master
noted the novice's preoccupation with a hand-held computer game.  "Excuse me",
he said, "may I examine it?"

The novice bolted to attention and handed the device to the master.
"I see that the device claims to have three levels of play: Easy, Medium,
and Hard", said the master.  "Yet every such device has another level of play,
where the device seeks not to conquer the human, nor to be conquered by the
human."

"Pray, great master," implored the novice, "how does one find this
mysterious setting?"
 
The master dropped the device to the ground and crushed it under foot.
And suddenly the novice was enlightened. 

--- Geoffrey James, "The Tao of Programming"

** 178; 12021 H.E.
 
Братья, любовь — учительница, но нужно уметь ее приобрести, ибо она трудно приобретается, дорого покупается, долгою работой и через долгий срок, ибо не на мгновение лишь случайное надо любить, а на весь срок. А случайно-то и всяк полюбить может, и злодей полюбит.

--- Достоевский

** 176; 12021 H.E.
 
Your love is like a tidal wave, spinning over my head\
Drownin' me in your promises, better left unsaid\
You're the right kind of sinner to release my inner fantasy\
The invincible winner and you know that you were born to be\
You're a heartbreaker, dream maker, love taker\
Don't you mess around with me\
You're a heartbreaker, dream maker, love taker\
Don't you mess around, no, no, no\
Your love has set my soul on fire, burnin' out of control\
You taught me the ways of desire, now it's takin' its toll\
You're the right kind of sinner to release my inner fantasy\
The invincible winner and you know that you were born to be\

--- Для Лилюшы (Pat Benatar's "Heartbreaker")

** 175; 12021 H.E.
 
Knowledge without common sense is folly.

** 174; 12021 H.E.
 
The better part of valor is discretion.

--- William Shakespeare, "Henry IV"

** 173; 12021 H.E.
 
Art is the tree of life.  Science is the tree of death.

** 171; 12021 H.E.
 
I kissed my first girl and smoked my first cigarette on the same day.
I haven't had time for tobacco since.

--- Arturo Toscanini

** 169; 12021 H.E.
 
We are all in the gutter, but some of us are looking at the stars.

--- Oscar Wilde
** 167; 12021 H.E.
 
Forests precede civilizations and deserts follow them.

--- François-René de Chateaubriand

** 166; 12021 H.E.
 
Extreme fear can neither fight nor fly.

--- William Shakespeare

** 165; 12021 H.E.
 
Some people have a way about them that seems to say: "If I have
only one life to live, let me live it as a jerk."

** 164; 12021 H.E.
 
A real person has two reasons for doing anything ... a good reason and
the real reason.

** 163; 12021 H.E.
 
Two sure ways to tell a REALLY sexy man; the first is, he has a bad memory. I forget the second.

** 161; 12021 H.E.
 
When you're ready to give up the struggle, who can you surrender to?

** 160; 12021 H.E.
 
=life←{↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}=

** 159; 12021 H.E.
 
APL is a mistake, carried through to perfection. It is the language of the future for the programming techniques of the past: it creates a new generation of coding bums.

--- Edsger W. Dijkstra (May 1982), "How do we tell truths that might hurt?", SIGPLAN Notice 17 (5): pp. 13–15.

** 158; 12021 H.E.
 
Do not be afraid; our fate\
Cannot be taken from us; it is a gift.

--- Dante Alighieri

** 157; 12021 H.E.
 
Democracy means simply the bludgeoning of the people by the people for the people.

--- Oscar Wilde

** 156; 12021 H.E.
 
To do two things at once is to do neither.

--- Publilius Syrus

** 155; 12021 H.E.
 
And ever has it been known that love knows not its own depth until the
hour of separation.

--- Kahlil Gibran

** 154; 12021 H.E.
 
It's useless to try to hold some people to anything they say while they're
madly in love, drunk, or running for office.

** 153; 12021 H.E.
 
To stay young requires unceasing cultivation of the ability to unlearn
old falsehoods.

--- Lazarus Long, "Time Enough For Love"

** 152; 12021 H.E.
 
While there's life, there's hope.

--- Publius Terentius Afer (Terence)

** 151; 12021 H.E.
 
A mother takes twenty years to make a man of her boy, and another woman
makes a fool of him in twenty minutes.

--- Robert Frost

** 150; 12021 H.E.
 
Against stupidity the very gods Themselves contend in vain.

--- Friedrich von Schiller, "The Maid of Orleans", III, 6

** 149; 12021 H.E.
 
The perfect man is the true partner.  Not a bed partner nor a fun partner,
but a man who will shoulder burdens equally with [you] and possess that
quality of joy.

  -- Erica Jong

** 149; 12021 H.E.
 
There's no heavier burden than a great potential.

** 148; 12021 H.E.
 
My opinions may have changed, but not the fact that I am right.

** 147; 12021 H.E.
 
The knowledge that makes us cherish innocence makes innocence unattainable.

  -- Irving Howe

** 146; 12021 H.E.
 
Does a good farmer neglect a crop he has planted?\
Does a good teacher overlook even the most humble student?\
Does a good father allow a single child to starve?\
Does a good programmer refuse to maintain his code?\

--- Geoffrey James, "The Tao of Programming"

** 145; 12021 H.E.
 
Si j'avais encore la folie de croire au bonheur, je le chercherais dans l'habitude.

--- François-René de Chateaubriand

** 143; 12021 H.E.
 
Frankly, my dear, I don't give a damn!

--- Rhett Butler

** 142; 12021 H.E.
 
Your mode of life will be changed for the better because of new developments.

** 141; 12021 H.E.
 
The difference between art and science is that science is what we
understand well enough to explain to a computer.  Art is everything else.

  -- Donald Knuth, "Discover"

** 140; 12021 H.E.
 
The one charm of marriage is that it makes a life of deception a neccessity.

--- Oscar Wilde

** 139; 12021 H.E.
 
They said that of all the kings upon the earth\
He was the man most gracious and fair-minded,\
Kindest to his people and keenest to win fame.\

--- Beowulf, the last three lines in Seamus Heaney's translation

** 138; 12021 H.E.
 
Of course it's possible to love a human being if you don't know them too well.

  -- Charles Bukowski

** 137; 12021 H.E.
 
You don't have to explain something you never said.

  -- Calvin Coolidge

** 136; 12021 H.E.
 
The number of UNIX installations has grown to 10, with more expected.

 -- The Unix Programmer's Manual, 2nd Edition, June 1972

** 135; 12021 H.E.
 
One is not born a woman, one becomes one.

  -- Simone de Beauvoir

** 134; 12021 H.E.
 
Nothing is finished until the paperwork is done.

** 133; 12021 H.E.
 
incentive program, n.:\
 The system of long and short-term rewards that a corporation uses
 to motivate its people.  Still, despite all the experimentation with
 profit sharing, stock options, and the like, the most effective
 incentive program to date seems to be "Do a good job and you get to
 keep it."

** 132; 12021 H.E.
 
Testing can show the presense of bugs, but not their absence.

  -- Dijkstra

** 131; 12021 H.E.
 
Young men want to be faithful and are not; old men want to be faithless and
cannot.

  -- Oscar Wilde

** 130; 12021 H.E.
 
Добрых людей много, но аккуратных и дисциплинированных совсем, совсем мало

--- Чехов из письма к В. А. ПОССЕ 15 февраля 1900 г. Ялта.

** 129; 12021 H.E.
 
Смеются только над тем, что смешно или чего не понимают... Выбирай любое из двух. Второе, конечно, более лестно, но - увы! - для меня лично ты не составляешь загадки.

--- Чехов (1860 – 1904) из Письма брату Николаю Павловичу Чехову Март 1886 г. Москва

** 129; 12021 H.E.
 
Читателей следует избавлять от встречи с незрелыми писательскими опытами

--- Чехов

** 129; 12021 H.E.
 
Кстати сказать, и народные театры, и народная литература — все это глупость, все это народная карамель. Надо не Гоголя опускать до народа, а народ поднимать к Гоголю.

--- Чехов

** 129; 12021 H.E.
 
Eat drink and be merry, for tomorrow we diet.

** 127; 12021 H.E.
 
I can resist anything but temptation.

** 126; 12021 H.E.
 
God is really only another artist.  He invented the giraffe, the elephant
and the cat.  He has no real style, He just goes on trying other things.

  -- Pablo Picasso

** 124; 12021 H.E.
 
The universe seems neither benign nor hostile, merely indifferent.

  -- Sagan

** 123; 12021 H.E.
 
 The Hitchhiker's Guide to the Galaxy has a few things to say on
the subject of towels.

 Most importantly, a towel has immense psychological value.  For
some reason, if a non-hitchhiker discovers that a hitchhiker has his towel
with him, he will automatically assume that he is also in possession of a
toothbrush, washcloth, flask, gnat spray, space suit, etc., etc.  Furthermore,
the non-hitchhiker will then happily lend the hitchhiker any of these or
a dozen other items that he may have "lost".  After all, any man who can
hitch the length and breadth of the Galaxy, struggle against terrible odds,
win through and still know where his towel is, is clearly a man to be
reckoned with.

  -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

** 122; 12021 H.E.
 
An honest tale speeds best being plainly told.
  
--- William Shakespeare, "Henry VI"

** 121; 12021 H.E.
 
"God is a comedian playing to an audience too afraid to laugh."

--- Voltaire

** 119; 12021 H.E.
 
There is nothing stranger in a strange land than the stranger who comes to visit.

** 117; 12021 H.E.
 
Writing, to me, is simply thinking through my fingers.

--- Isaac Asimov

** 116; 12021 H.E.
 
Because we don't think about future generations, they will never forget us.

--- Henrik Tikkanen

** 115; 12021 H.E.
 
Let us read, and let us dance; these two amusements will never do any harm to the world.

― Voltaire

** 114; 12021 H.E.
 
Moderation in all things.
  
--- Publius Terentius Afer [Terence]

** 114; 12021 H.E.
 
The man who runs may fight again.
  
--- Menander

** 111; 12021 H.E.
 
The sum of the intelligence of the world is constant.  The population is, of course, growing.

** 110; 12021 H.E.
 
f u cn rd ths, u cn gt a gd jb n cmptr prgrmmng

** 109; 12021 H.E.
 
One often meets his destiny on the road he takes to avoid it.

— Master Oogway

** 108; 12021 H.E.
 
There are two ways of constructing a software design.  One way is to make
it so simple that there are obviously no deficiencies and the other is to
make it so complicated that there are no obvious deficiencies.
  -- C.A.R. Hoare

** 100; 12021 H.E.
 
Ever get the feeling that the world's on tape and one of the reels is missing?

  -- Rich Little

** 93; 12021 H.E.
 
Entropy isn't what it used to be.

** 84; 12021 H.E.
 
Entropy isn't what it used to be.

** 79; 12021 H.E.
 
Q: How many psychiatrists does it take to change a light bulb?

A: Only one, but it takes a long time, and the light bulb has
 to really want to change.

** 71; 12021 H.E.
 
Nothing matters very much, and few things matter at all.

--- Arthur Balfour

** 67; 12021 H.E.
 
Quality control, n.:

 Assuring that the quality of a product does not get out of hand
 and add to the cost of its manufacture or design.

** 54; 12021 H.E.
 
Don't be distracted by the what-if's, should-have's, and if-only's. The one thing you choose for yourself - that is the truth of your universe.

--- Kamina

** 42; 12021 H.E.
 
A true man never dies, even when he's killed. 

--- Kamina

** 33; 12021 H.E.

Нравственные поговорки бывают удивительно полезны в тех случаях, когда мы от себя мало что можем выдумать себе в оправдание.

** 31; 12021 H.E.

If you know pain and hardship, it’s easier to be kind to others.

--- Ryoji Kaji

** 30; 12021 H.E.
 
Anywhere can be paradise as long as you have the will to live. After all, you are alive, so you will always have the chance to be happy. As long as the Sun, the Moon, and the Earth exist, everything will be all right.

--- Yui Ikari

** 29; 12021 H.E.

Whether I live or die makes no great difference. In truth, death may be the only absolute freedom there is.

--- Kaworu Nagisa

** 25; 12021 H.E.
 
Who the hell do you think I am?!

--- Kamina

** 24; 12021 H.E.
 
The dreams of those who've fallen! The hopes of those who'll follow! Those two sets of dreams weave together into a double helix! Drilling a path towards tomorrow! And that's Tengen Toppa! That's Gurren Lagann!

--- Simon

** 23; 12021 H.E.
 
Believe in yourself. Not in the you who believes in me. Not the me who believes in you. Believe in the you who believes in yourself.

--- Kamina

** 21; 12021 H.E.

There once was a man who went to a computer trade show. Each day as he entered, the man told the guard at the door:
"I am a great thief, renowned for my feats of shoplifting. Be forewarned, for this trade show shall not escape unplundered."
This speech disturbed the guard greatly, because there were millions of dollars of computer equipment inside, so he watched the man carefully. But the man merely wandered from booth to booth, humming quietly to himself.

When the man left, the guard took him aside and searched his clothes, but nothing was to be found.

On the next day of the trade show, the man returned and chided the guard, saying: "I escaped with a vast booty yesterday, but today will be even better." So the guard watched him ever more closely, but to no avail.

On the final day of the trade show, the guard could restrain his curiosity no longer. "Sir Thief," he said, "I am so perplexed, I cannot live in peace. Please enlighten me. What is it that you are stealing?"

The man smiled. "I am stealing ideas," he said.

** 20; 12021 H.E.

Prince Wang's programmer was coding software. His fingers danced upon the keyboard. The program compiled without and error message, and the program ran like a gentle wind.

"Excellent!" the Prince exclaimed. "Your technique is faultless!"

"Technique?" said the programmer, turning from his terminal, "What I follow is Tao -- beyond all techniques! When I first began to program, I would see before me the whole problem in one mass. After three years, I no longer saw this mass. Instead, I used subroutines. But now I see nothing. My whole being exists in a formless void. My senses are idle. My spirit, free to work without a plan, follows its own instinct. In short, my program writes itself. True, sometimes there are difficult problems. I see them coming, I slow down, I watch silently. Then I change a single line of code and the difficulties vanish like puffs of idle smoke. I then compile the program. I sit still and let the joy of the work fill my being. I close my eyes for a moment and then log off."

Prince Wang said, "Would that all of my programmers were as wise!"

--- Geoffrey James, "The Tao of Programming"

** 17; 12021 H.E.
 

A truly great man will neither trample on a worm nor sneak to an emperor.

  -- B. Franklin

** 356; 12020 H.E.
 
TV is chewing gum for the eyes.

  -- Frank Lloyd Wright

** 342; 12020 H.E.
 
By studying the masters -- not their pupils.

— Niels Henrik Abel

** 341; 12020 H.E.
 
My name is Ozymandias, King of Kings;

Look on my Works, ye Mighty, and despair!

** 338; 12020 H.E.
 
The unexamined life is not worth living

--- Socrates

** 336; 12020 H.E.
 
The longest part of the journey is said to be the passing of the gate.

--- Marcus Terentius Varro

** 335; 12020 H.E.
 
``When you wake up in the morning, Pooh,'' said Piglet at last, ``what's the
first thing you say to yourserf?''\
``What's for breakfast?'' said Pooh. ``What do /you/ say, Piglet?''\
``I say, I wonder what's going to happen exciting /today/?'' said Piglet.\
Pooh nodded thoughtfully.\
``It's the same thing,'' he said.\

** 331; 12020 H.E.
 
Q: How many Harvard MBA's does it take to screw in a light bulb?

A: Just one.  He grasps it firmly and the universe revolves around him.

** 322; 12020 H.E.

Don’t go around saying the world owes you a living. The world owes you nothing. It was here first. 

— Mark Twain

** 318; 12020 H.E.
 
The only thing we have to fear is fear itself.

— Franklin Delano Roosevelt

** 315; 12020 H.E.

Judge each day not by the harvest you reap, but by the seeds you plant.

— Robert Louis Stevenson
(Found on the back of my red wine vinegar bottle)

** 314; 12020 H.E.
 
The devil can cite Scripture for his purpose.

— William Shakespeare, “The Merchant of Venice”

** 313; 12020 H.E.
 
University politics are vicious precisely because the stakes are so small.

— C. P. Snow (see "Sayre's law")

** 305; 12020 H.E.
 
It doesn't interest me what you do for a living. I want to know what you ache for and if you dare to dream of meeting your heart's longing.

It doesn't interest me how old you are. I want to know if you will risk looking like a fool for love, for your dream, for the adventure of being alive.

— Oriah Mountain Dreamer

** 303; 12020 H.E.

Liberty lies in the hearts of men and women; when it dies there, no constitution, no law, no court can save it; no constitution, no law, no court can even do much to help it.

— Learned Hand, Spirit of Liberty

** 300; 12020 H.E.

For there are moments when one can neither think nor feel.  And if one can
neither think nor feel, she thought, where is one?
 
— Virginia Woolf, "To the Lighthouse"

** 299; 12020 H.E.

Are we THERE yet?

Note: that is actually how I was taught Fundamental theorem of calculus

** 295; 12020 H.E.

When I reflect upon the number of disagreeable people who I know who have gone to a better world, I am moved to lead a different life.

— Mark Twain, Pudd'nhead Wilson

** 292; 12020 H.E.

Q:  How many lawyers does it take to change a light bulb?

A:  Whereas the party of the first part, also known as "Lawyer", and the
party of the second part, also known as "Light Bulb", do hereby and forthwith
agree to a transaction wherein the party of the second part shall be removed
from the current position as a result of failure to perform previously agreed
upon duties, i.e., the lighting, elucidation, and otherwise illumination of
the area ranging from the front (north) door, through the entryway, terminating
at an area just inside the primary living area, demarcated by the beginning of
the carpet, any spillover illumination being at the option of the party of the
second part and not required by the aforementioned agreement between the
parties.\
The aforementioned removal transaction shall include, but not be
limited to, the following.  The party of the first part shall, with or without
elevation at his option, by means of a chair, stepstool, ladder or any other
means of elevation, grasp the party of the second part and rotate the party
of the second part in a counter-clockwise direction, this point being tendered
non-negotiable.  Upon reaching a point where the party of the second part
becomes fully detached from the receptacle, the party of the first part shall
have the option of disposing of the party of the second part in a manner
consistent with all relevant and applicable local, state and federal statutes.
Once separation and disposal have been achieved, the party of the first part
shall have the option of beginning installation.  Aforesaid installation shall
occur in a manner consistent with the reverse of the procedures described in
step one of this self-same document, being careful to note that the rotation
should occur in a clockwise direction, this point also being non-negotiable.
The above described steps may be performed, at the option of the party of the
first part, by any or all agents authorized by him, the objective being to
produce the most possible revenue for the Partnership.

** 285; 12020 H.E.

Zounds!  I was never so bethumped with words
since I first called my brother's father dad.

— William Shakespeare, "Kind John"

** 281; 12020 H.E.

In a mad world, only the mad are sane.

— Akira Kurosawa

** 280; 12020 H.E.
 
Ours [i.e., the Christian religion] is assuredly the most ridiculous, the most absurd and the most bloody religion which has ever infected this world. Your Majesty will do the human race an eternal service by extirpating this infamous superstition, I do not say among the rabble, who are not worthy of being enlightened and who are apt for every yoke; I say among honest people, among men who think, among those who wish to think. ... My one regret in dying is that I cannot aid you in this noble enterprise, the finest and most respectable which the human mind can point out.

— Voltaire to Frederick II, 1767

** 278; 12020 H.E.
 
Go to Heaven for the climate, Hell for the company.

— Mark Twain

** 275; 12020 H.E.
 
Fate goes ever as fate must.

— Beowulf, 455

** 274; 12020 H.E.

Those who would give up essential Liberty, to purchase a little temporary Safety, deserve neither Liberty nor Safety.

— Benjamin Franklin

** 273; 12020 H.E.

The meaning of life is that it ends

— Franz Kafka

** 272; 12020 H.E.

Thank goodness technology progressed to the point where we don't have to deal with our issues privately

** 271; 12020 H.E.

All it takes for evil to succeed, is for good people to say - "It's a business"

** 265; 12020 H.E.
 
There are no bad questions, only horrible answers

** 260; 12020 H.E.

Men learn to love the woman they are attracted to. Women learn to become attracted to the man they fall in love with.

— Woody Allen

** 259; 12020 H.E.
 
Man plans, God laughs

** 257; 12020 H.E.

No good deed goes unpunished.

** 256; 12020 H.E.
 
There are no sides in this world, only players

** 249; 12020 H.E.

Nature abhors a vacuum.

— Aristotle

** 248; 12020 H.E.

A wise man can learn more from a foolish question than a fool can learn from a wise answer.

— Bruce Lee

** 247; 12020 H.E.
 
Those who abjure violence can do so only because others are committing violence on their behalf.

— George Orwell

** 241; 12020 H.E.
 
Misery is wasted on the miserable. 

— /Louie/

** 238; 12020 H.E.
 
Almost nothing great has ever been done in the world except by the genius and firmness of a single man combating the prejudices of the multitude.

— Voltaire, correspondence with Catherine the Great

** 237; 12020 H.E.

Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.

— Sigmund Freud, Civilization and Its Discontents

** 236; 12020 H.E.
 
    Вот как нам писать. Пушкин приступает прямо к делу. Другой бы начал
    описывать гостей, комнаты, а он вводит в действие сразу 

    — Л. Н. Толстой (запись в дневнике С. А. Толстой от 19 марта 1873).

** 232; 12020 H.E.

    "Internally, Emacs still belives it’s a text program, and we pretend Xt is a
    text terminal, and we pretend GTK is an Xt toolkit. It’s a fractal of
    delusion."

    — marai2 (Hackernews comments)
    
** 230; 12020 H.E.
 
    Against stupidity the very gods;
    Themselves contend in vain.

    — Friedrich Schiller

** 226; 12020 H.E.
 
    Life is too important to be taken seriously.
    
    — Oscar Wilde

** 223; 12020 H.E.
 
    To live is the rarest thing in the world. Most people exist, that is all.

    — Oscar Wilde

** 222; 12020 H.E.

    Be yourself; everyone else is already taken.

    — Oscar Wilde

** 219; 12020 H.E.
    
    Let us cultivate our garden. 
    
    — Candide

** 214; 12020 H.E.
 
    Religion is like a blind man looking in a black room for a black cat that
    isn't there, and finding it. 

    — Oscar Wilde

** 213; 12020 H.E.

    In all the known history of Mankind, advances have been made primarily in
    physical technology; in the capacity of handling the inanimate world about 
    Man. Control of self and society has been left to to chance or to the vague 
    gropings of intuitive ethical systems based on inspiration and emotion. As a 
    result no culture of greater stability than about fifty-five percent has
    ever existed, and these only as the result of great human misery. 

    — Isaac Asimov

** 212; 12020 H.E.

    The true delight is in the finding out rather than in the knowing. 

    — Isaac Asimov

** 207; 12020 H.E.
 
    Excessive bureaucracy is the start of the fall of any civilization

** 206; 12020 H.E.
 
    Все счастливые семьи похожи друг на друга, каждая несчастливая семья
    несчастлива по-своему.

    — Leo Tolstoy

** 205; 12020 H.E.

    It seems to me, Golan, that the advance of civilization is nothing but an
    exercise in the limiting of privacy.  

    — Janov Pelorat, /Foundation’s Edge/

** 204; 12020 H.E.
 
    Any sufficiently advanced technology is indistinguishable from magic.
    
    — Arthur C. Clarke

** 203; 12020 H.E.
 
    If this is the solution, I want my problem back.

    — nosystemd.org

** 202; 12020 H.E.
 
    Most people are other people. Their thoughts are someone else's opinions, their
    lives a mimicry, their passions a quotation. 

    — Oscar Wilde

** 201; 12020 H.E.
 
    Never let your sense of morals prevent you from doing what is right
    
    — Isaac Asimov
    
** 199; 12020 H.E.
 
    Those who can make you believe absurdities can make you commit atrocities. 

    — Voltaire

** 197; 12020 H.E.
 
    Violence is the last refuge of the incompetent.
    
    — Isaac Asimov
    
** 196; 12020 H.E.

    
    Committee, n.:
    
    A group of men who individually can do nothing but as a group
    decide that nothing can be done.
    
    -- Fred Allen
    
** Monday, July 6th, 2020

    "When I picture it in my head I think of the early web as more of a
    library. Over time it has transitioned into a shopping mall." 

    -- chris_f (Hacker News comments) 

** Saturday, July 4th, 2020

    In each of us sleeps a genius... and his sleep gets deeper everyday.

** Tuesday, June 23, 2020
    
    The galaxies hum the shape and form in their essence. That is their secret.\
    The particles whisper of the nature of proper interactions. That is their
    game.\
    And during a storm, in the forest, on the right night, it is no secret that
    the leaves all sing of God.\

    -- Exurb1a, /The Fifth Science/

** Tuesday, June 9, 2020

    It is by the fortune of God that, in this country, we have three benefits:
    freedom of speech, freedom of thought, and the wisdom never to use either.
    -- Mark Twain

** Wednesday, May 20, 2020
    
    C++ is history repeated as tragedy. Java is history repeated as farce. 
    – Scott McKay
