* Quote of the week ☁️

  Some quotes are regular and some are not

*** 201; 12020 H.E.
 
Never let your sense of morals prevent you from doing what is right

— Isaac Asimov

*** 199; 12020 H.E.
 
Those who can make you believe absurdities can make you commit atrocities. 

— Voltaire

*** 197; 12020 H.E.
 
Violence is the last refuge of the incompetent.

— Isaac Asimov

*** 196; 12020 H.E.

 
Committee, n.:

  A group of men who individually can do nothing but as a group
  decide that nothing can be done.
  
-- Fred Allen

*** Monday, July 6th, 2020

    "When I picture it in my head I think of the early web as more of a
    library. Over time it has transitioned into a shopping mall." 

    -- chris_f (Hacker News comments) 

*** Saturday, July 4th, 2020

    In each of us sleeps a genius... and his sleep gets deeper everyday.

*** Tuesday, June 23, 2020
    
    The galaxies hum the shape and form in their essence. That is their secret.

    The particles whisper of the nature of proper interactions. That is their
    game.

    And during a storm, in the forest, on the right night, it is no secret that
    the leaves all sing of God.
  
    -- Exurb1a, /The Fifth Science/

*** Tuesday, June 9, 2020

    It is by the fortune of God that, in this country, we have three benefits:
    freedom of speech, freedom of thought, and the wisdom never to use either.
    -- Mark Twain

*** Wednesday, May 20, 2020
    
    C++ is history repeated as tragedy. Java is history repeated as farce. – Scott
    McKay
