= Sandy's fortunes 🥠
Sagindyk Urazayev <ctu@ku.edu>
About_LINK | Bookshelf_LINK | Fortunes_LINK | Home_LINK
:nofooter:
:experimental:

== 281; 12021 H.E.

The older I grow, the less important the comma becomes. Let the reader
catch his own breath.

– Elizabeth Clarkson Zwart

== 280; 12021 H.E.

Education is an admirable thing, but it is well to remember from time to
time that nothing that is worth knowing can be taught.

– Oscar Wilde, "The Critic as Artist"

== 280; 12021 H.E.

Don't despair; your ideal lover is waiting for you around the corner.

== 277; 12021 H.E.

Millions long for immortality who do not know what to do with themselves
on a rainy Sunday afternoon.

– Susan Ertz

== 275; 12021 H.E.

The chief danger in life is that you may take too many precautions.

– Alfred Adler

== 274; 12021 H.E.

Not far from here, by a white sun, behind a green star, lived the
Steelypips, illustrious, industrious, and they hadn't a care: no spats
in their vats, no rules, no schools, no gloom, no evil influence of the
moon, no trouble from matter or antimatter – for they had a machine, a
dream of a machine, with springs and gears and perfect in every respect.
And they lived with it, and on it, and under it, and inside it, for it
was all they had – first they saved up all their atoms, then they put
them all together, and if one didn't fit, why they chipped at it a bit,
and everything was just fine …

– Stanislaw Lem, "Cyberiad"

== 272; 12021 H.E.

Всегда доходит до того крайнего предела, где каждая форма так
таинственно уподобляется своей противоположности, что эта
действительность всякому обыденному, привыкшему к среднему уровню взору
представляется фантастической.

– Стефан Цвейг о реализме Достоевского

== 271; 12021 H.E.

It is common sense to take a method and try it. If it fails, admit it
frankly and try another. But above all, try something.

– Franklin D. Roosevelt

== 271; 12021 H.E.

Just to have it is enough.

== 267; 12021 H.E.

A lost ounce of gold may be found, a lost moment of time never.

== 266; 12021 H.E.

He who is known as an early riser need not get up until noon.

== 265; 12021 H.E.

We should be careful to get out of an experience only the wisdom that is
in it - and stay there, lest we be like the cat that sits down on a hot
stove-lid. She will never sit down on a hot stove-lid again - and that
is well; but also she will never sit down on a cold one any more.

– Mark Twain

== 263; 12021 H.E.

Rune's Rule:

If you don't care where you are, you ain't lost.

== 260; 12021 H.E.

I allow myself to be decadent

== 259; 12021 H.E.

Nonsense and beauty have close connections.

– E.M. Forster

== 258; 12021 H.E.

skldfjkljklsR%^&(IXDRTYju187pkasdjbasdfbuil h;asvgy8p 23r1vyui135 2
kmxsij90TYDFS$$b jkzxdjkl bjnk ;j nk;<[][;-==-<<<<<';[,
[hjioasdvbnuio;buip^&(FTSD$%*VYUI:buio;sdf}[asdf']
sdoihjfh(_YU*G&F^*^CTY98y

Now look what you've gone and done! You've broken it!

== 257; 12021 H.E.

Science and religion are in full accord but science and faith are in
complete discord.

== 256; 12021 H.E.

Consider well the proportions of things. It is better to be a young
June-bug than an old bird of paradise.

– Mark Twain, "Pudd'nhead Wilson's Calendar"

== 255; 12021 H.E.

Я видел пьяниц с мудрыми глазами

И падших женщин с ликом чистоты.

Я знаю сильных, что взахлёб рыдали

И слабых, что несут кресты.

Не бойся вора в нищенском обличьи,

И проклинать за мелочь, не спеши-

Ты бойся тех, кто выглядит прилично,

Вор с праведным лицом уносит часть души.

Не обвиняй во всех грехах соседа,

Интриг не строй и сплетен не плети!

Воздастся добротой тебе за это,

Когда споткнёшься на своём пути.

Не осуждай за то, в чём не уверен;

Не обещай, если решил солгать.

Не проверяй, когда уже доверил!

И не дари, планируя отнять.

– Серге́й Алекса́ндрович Есе́нин

== 254; 12021 H.E.

Of all men's miseries, the bitterest is this: to know so much and have
control over nothing.

– Herodotus

== 253; 12021 H.E.

Ambition is a poor excuse for not having sense enough to be lazy.

– Charlie McCarthy

== 251; 12021 H.E.

He who wonders discovers that this in itself is wonder.

– M.C. Escher

== 250; 12021 H.E.

It isn't easy being a Friday kind of person in a Monday kind of world.

== 249; 12021 H.E.

Your happiness is intertwined with your outlook on life.

== 248; 12021 H.E.

A well-known friend is a treasure.

== 246; 12021 H.E.

The master programmer moves from program to program without fear. No
change in management can harm him. He will not be fired, even if the
project is canceled. Why is this? He is filled with the Tao.

– Geoffrey James, "The Tao of Programming"

== 245; 12021 H.E.

While any text editor can save your files, only Emacs can save your soul

== 243; 12021 H.E.

If you are afraid of loneliness, don't marry.

– Anton Chekhov

== 242; 12021 H.E.

It is contrary to reasoning to say that there is a vacuum or space in
which there is absolutely nothing.

– Descartes

== 241; 12021 H.E.

Clothes make the man. Naked people have little or no influence on
society.

– Mark Twain

== 235; 12021 H.E.

Virtue does not always demand a heavy sacrifice – only the willingness
to make it when necessary.

– Frederick Dunn

== 233; 12021 H.E.

The ability to play chess is the sign of a gentleman. The ability to
play chess well is the sign of a wasted life.

— Paul Morphy

== 228; 12021 H.E.

today, n.:

A nice place to visit, but you can't stay here for long.

== 226; 12021 H.E.

I have the simplest tastes. I am always satisfied with the best.

– Oscar Wilde

== 201; 12021 H.E.

I love you and you are loved

– Sandy

== 200; 12021 H.E.

Govern a great nation as you would cook a small fish. Don't overdo it.

– Lao Tzu

== 199; 12021 H.E.

A good name lost is seldom regained. When character is gone, all is
gone, and one of the richest jewels of life is lost forever.

– J. Hawes

== 198; 12021 H.E.

Жизнь, по сути, очень простая штука и человеку нужно приложить много
усилий, чтобы её испортить.

– Чехов

== 197; 12021 H.E.

Bizarreness is the essence of the exotic.

== 196; 12021 H.E.

Most of the fear that spoils our life comes from attacking difficulties
before we get to them.

– Dr. Frank Crane

== 194; 12021 H.E.

You can't get very far in this world without your dossier being there
first.

– Arthur Miller

== 192; 12021 H.E.

He who knows, does not speak. He who speaks, does not know.

– Lao Tsu

== 191; 12021 H.E.

Documentation:

Instructions translated from Swedish by Japanese for English speaking
persons.

== 190; 12021 H.E.

Someday somebody has got to decide whether the typewriter is the
machine, or the person who operates it.

== 188; 12021 H.E.

The hatred of relatives is the most violent.

– Tacitus (c.55 - c.117)

== 187; 12021 H.E.

You can tell the ideals of a nation by its advertisements.

– Norman Douglas

== 186; 12021 H.E.

Fare thee well, and if for ever,

Still for ever, fare thee well.

– Byron

== 186; 12021 H.E.

"Сознание жизни выше жизни, знание законов счастья–выше счастья" – вот с
чем бороться надо! И буду. Если только все захотят, то сейчас все
устроится.

– Fyodor Dostoevsky, _The Dream of a Ridiculous Man_

== 184; 12021 H.E.

So many people are stuck living the same life because they think that is
what they're supposed to do. But really, you're just completely free to
do it. You are able to do it. And even if its a different and more
difficult road to take, I believe you should do if it's going to make
you happy.

– Marzia Kjellberg

== 184; 12021 H.E.

One good turn usually gets most of the blanket.

== 182; 12021 H.E.

Some people cause happiness wherever they go; others, whenever they go.

== 179; 12021 H.E.

A master programmer passed a novice programmer one day. The master noted
the novice's preoccupation with a hand-held computer game. "Excuse me",
he said, "may I examine it?"

The novice bolted to attention and handed the device to the master. "I
see that the device claims to have three levels of play: Easy, Medium,
and Hard", said the master. "Yet every such device has another level of
play, where the device seeks not to conquer the human, nor to be
conquered by the human."

"Pray, great master," implored the novice, "how does one find this
mysterious setting?"

The master dropped the device to the ground and crushed it under foot.
And suddenly the novice was enlightened.

– Geoffrey James, "The Tao of Programming"

== 178; 12021 H.E.

Братья, любовь — учительница, но нужно уметь ее приобрести, ибо она
трудно приобретается, дорого покупается, долгою работой и через долгий
срок, ибо не на мгновение лишь случайное надо любить, а на весь срок.
А случайно-то и всяк полюбить может, и злодей полюбит.

– Достоевский

== 176; 12021 H.E.

Your love is like a tidal wave, spinning over my head

Drownin' me in your promises, better left unsaid

You're the right kind of sinner to release my inner fantasy

The invincible winner and you know that you were born to be

You're a heartbreaker, dream maker, love taker

Don't you mess around with me

You're a heartbreaker, dream maker, love taker

Don't you mess around, no, no, no

Your love has set my soul on fire, burnin' out of control

You taught me the ways of desire, now it's takin' its toll

You're the right kind of sinner to release my inner fantasy

The invincible winner and you know that you were born to be

– Для Лилюшы (Pat Benatar's "Heartbreaker")

== 175; 12021 H.E.

Knowledge without common sense is folly.

== 174; 12021 H.E.

The better part of valor is discretion.

– William Shakespeare, "Henry IV"

== 173; 12021 H.E.

Art is the tree of life. Science is the tree of death.

== 171; 12021 H.E.

I kissed my first girl and smoked my first cigarette on the same day. I
haven't had time for tobacco since.

– Arturo Toscanini

== 169; 12021 H.E.

We are all in the gutter, but some of us are looking at the stars.

– Oscar Wilde

== 167; 12021 H.E.

Forests precede civilizations and deserts follow them.

– François-René de Chateaubriand

== 166; 12021 H.E.

Extreme fear can neither fight nor fly.

– William Shakespeare

== 165; 12021 H.E.

Some people have a way about them that seems to say: "If I have only one
life to live, let me live it as a jerk."

== 164; 12021 H.E.

A real person has two reasons for doing anything … a good reason and the
real reason.

== 163; 12021 H.E.

Two sure ways to tell a REALLY sexy man; the first is, he has a bad
memory. I forget the second.

== 161; 12021 H.E.

When you're ready to give up the struggle, who can you surrender to?

== 160; 12021 H.E.

`life←{↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}`

== 159; 12021 H.E.

APL is a mistake, carried through to perfection. It is the language of
the future for the programming techniques of the past: it creates a new
generation of coding bums.

– Edsger W. Dijkstra (May 1982), "How do we tell truths that might
hurt?", SIGPLAN Notice 17 (5): pp. 13–15.

== 158; 12021 H.E.

Do not be afraid; our fate

Cannot be taken from us; it is a gift.

– Dante Alighieri

== 157; 12021 H.E.

Democracy means simply the bludgeoning of the people by the people for
the people.

– Oscar Wilde

== 156; 12021 H.E.

To do two things at once is to do neither.

– Publilius Syrus

== 155; 12021 H.E.

And ever has it been known that love knows not its own depth until the
hour of separation.

– Kahlil Gibran

== 154; 12021 H.E.

It's useless to try to hold some people to anything they say while
they're madly in love, drunk, or running for office.

== 153; 12021 H.E.

To stay young requires unceasing cultivation of the ability to unlearn
old falsehoods.

– Lazarus Long, "Time Enough For Love"

== 152; 12021 H.E.

While there's life, there's hope.

– Publius Terentius Afer (Terence)

== 151; 12021 H.E.

A mother takes twenty years to make a man of her boy, and another woman
makes a fool of him in twenty minutes.

– Robert Frost

== 150; 12021 H.E.

Against stupidity the very gods Themselves contend in vain.

– Friedrich von Schiller, "The Maid of Orleans", III, 6

== 149; 12021 H.E.

The perfect man is the true partner. Not a bed partner nor a fun
partner, but a man who will shoulder burdens equally with [you] and
possess that quality of joy.

– Erica Jong

== 149; 12021 H.E.

There's no heavier burden than a great potential.

== 148; 12021 H.E.

My opinions may have changed, but not the fact that I am right.

== 147; 12021 H.E.

The knowledge that makes us cherish innocence makes innocence
unattainable.

– Irving Howe

== 146; 12021 H.E.

Does a good farmer neglect a crop he has planted?

Does a good teacher overlook even the most humble student?

Does a good father allow a single child to starve?

Does a good programmer refuse to maintain his code?

– Geoffrey James, "The Tao of Programming"

== 145; 12021 H.E.

Si j'avais encore la folie de croire au bonheur, je le chercherais dans
l'habitude.

– François-René de Chateaubriand

== 143; 12021 H.E.

Frankly, my dear, I don't give a damn!

– Rhett Butler

== 142; 12021 H.E.

Your mode of life will be changed for the better because of new
developments.

== 141; 12021 H.E.

The difference between art and science is that science is what we
understand well enough to explain to a computer. Art is everything else.

– Donald Knuth, "Discover"

== 140; 12021 H.E.

The one charm of marriage is that it makes a life of deception a
neccessity.

– Oscar Wilde

== 139; 12021 H.E.

They said that of all the kings upon the earth

He was the man most gracious and fair-minded,

Kindest to his people and keenest to win fame.

– Beowulf, the last three lines in Seamus Heaney's translation

== 138; 12021 H.E.

Of course it's possible to love a human being if you don't know them too
well.

– Charles Bukowski

== 137; 12021 H.E.

You don't have to explain something you never said.

– Calvin Coolidge

== 136; 12021 H.E.

The number of UNIX installations has grown to 10, with more expected.

– The Unix Programmer's Manual, 2nd Edition, June 1972

== 135; 12021 H.E.

One is not born a woman, one becomes one.

– Simone de Beauvoir

== 134; 12021 H.E.

Nothing is finished until the paperwork is done.

== 133; 12021 H.E.

incentive program, n.:

The system of long and short-term rewards that a corporation uses to
motivate its people. Still, despite all the experimentation with profit
sharing, stock options, and the like, the most effective incentive
program to date seems to be "Do a good job and you get to keep it."

== 132; 12021 H.E.

Testing can show the presense of bugs, but not their absence.

– Dijkstra

== 131; 12021 H.E.

Young men want to be faithful and are not; old men want to be faithless
and cannot.

– Oscar Wilde

== 130; 12021 H.E.

Добрых людей много, но аккуратных и дисциплинированных совсем, совсем
мало

– Чехов из письма к В. А. ПОССЕ 15 февраля 1900 г. Ялта.

== 129; 12021 H.E.

Смеются только над тем, что смешно или чего не понимают… Выбирай любое
из двух. Второе, конечно, более лестно, но - увы! - для меня лично ты не
составляешь загадки.

– Чехов (1860 – 1904) из Письма брату Николаю Павловичу Чехову Март 1886
г. Москва

== 129; 12021 H.E.

Читателей следует избавлять от встречи с незрелыми писательскими опытами

– Чехов

== 129; 12021 H.E.

Кстати сказать, и народные театры, и народная литература — все это
глупость, все это народная карамель. Надо не Гоголя опускать до народа,
а народ поднимать к Гоголю.

– Чехов

== 129; 12021 H.E.

Eat drink and be merry, for tomorrow we diet.

== 127; 12021 H.E.

I can resist anything but temptation.

== 126; 12021 H.E.

God is really only another artist. He invented the giraffe, the elephant
and the cat. He has no real style, He just goes on trying other things.

– Pablo Picasso

== 124; 12021 H.E.

The universe seems neither benign nor hostile, merely indifferent.

– Sagan

== 123; 12021 H.E.

The Hitchhiker's Guide to the Galaxy has a few things to say on the
subject of towels.

Most importantly, a towel has immense psychological value. For some
reason, if a non-hitchhiker discovers that a hitchhiker has his towel
with him, he will automatically assume that he is also in possession of
a toothbrush, washcloth, flask, gnat spray, space suit, etc., etc.
Furthermore, the non-hitchhiker will then happily lend the hitchhiker
any of these or a dozen other items that he may have "lost". After all,
any man who can hitch the length and breadth of the Galaxy, struggle
against terrible odds, win through and still know where his towel is, is
clearly a man to be reckoned with.

– Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

== 122; 12021 H.E.

An honest tale speeds best being plainly told.

– William Shakespeare, "Henry VI"

== 121; 12021 H.E.

"God is a comedian playing to an audience too afraid to laugh."

— Voltaire

== 119; 12021 H.E.

There is nothing stranger in a strange land than the stranger who comes
to visit.

== 117; 12021 H.E.

Writing, to me, is simply thinking through my fingers.

– Isaac Asimov

== 116; 12021 H.E.

Because we don't think about future generations, they will never forget
us.

– Henrik Tikkanen

== 115; 12021 H.E.

Let us read, and let us dance; these two amusements will never do any
harm to the world.

― Voltaire

== 114; 12021 H.E.

Moderation in all things.

– Publius Terentius Afer [Terence]

== 114; 12021 H.E.

The man who runs may fight again.

– Menander

== 111; 12021 H.E.

The sum of the intelligence of the world is constant. The population is,
of course, growing.

== 110; 12021 H.E.

f u cn rd ths, u cn gt a gd jb n cmptr prgrmmng

== 109; 12021 H.E.

One often meets his destiny on the road he takes to avoid it.

— Master Oogway

== 108; 12021 H.E.

There are two ways of constructing a software design. One way is to make
it so simple that there are obviously no deficiencies and the other is
to make it so complicated that there are no obvious deficiencies. –
C.A.R. Hoare

== 100; 12021 H.E.

Ever get the feeling that the world's on tape and one of the reels is
missing?

– Rich Little

== 93; 12021 H.E.

Entropy isn't what it used to be.

== 84; 12021 H.E.

Entropy isn't what it used to be.

== 79; 12021 H.E.

Q: How many psychiatrists does it take to change a light bulb?

A: Only one, but it takes a long time, and the light bulb has to really
want to change.

== 71; 12021 H.E.

Nothing matters very much, and few things matter at all.

– Arthur Balfour

== 67; 12021 H.E.

Quality control, n.:

Assuring that the quality of a product does not get out of hand and add
to the cost of its manufacture or design.

== 54; 12021 H.E.

Don't be distracted by the what-if's, should-have's, and if-only's. The
one thing you choose for yourself - that is the truth of your universe.

– Kamina

== 42; 12021 H.E.

A true man never dies, even when he's killed.

– Kamina

== 33; 12021 H.E.

Нравственные поговорки бывают удивительно полезны в тех случаях, когда
мы от себя мало что можем выдумать себе в оправдание.

== 31; 12021 H.E.

If you know pain and hardship, it’s easier to be kind to others.

– Ryoji Kaji

== 30; 12021 H.E.

Anywhere can be paradise as long as you have the will to live. After
all, you are alive, so you will always have the chance to be happy. As
long as the Sun, the Moon, and the Earth exist, everything will be all
right.

– Yui Ikari

== 29; 12021 H.E.

Whether I live or die makes no great difference. In truth, death may be
the only absolute freedom there is.

– Kaworu Nagisa

== 25; 12021 H.E.

Who the hell do you think I am?!

– Kamina

== 24; 12021 H.E.

The dreams of those who've fallen! The hopes of those who'll follow!
Those two sets of dreams weave together into a double helix! Drilling a
path towards tomorrow! And that's Tengen Toppa! That's Gurren Lagann!

– Simon

== 23; 12021 H.E.

Believe in yourself. Not in the you who believes in me. Not the me who
believes in you. Believe in the you who believes in yourself.

– Kamina

== 21; 12021 H.E.

There once was a man who went to a computer trade show. Each day as he
entered, the man told the guard at the door: "I am a great thief,
renowned for my feats of shoplifting. Be forewarned, for this trade show
shall not escape unplundered." This speech disturbed the guard greatly,
because there were millions of dollars of computer equipment inside, so
he watched the man carefully. But the man merely wandered from booth to
booth, humming quietly to himself.

When the man left, the guard took him aside and searched his clothes,
but nothing was to be found.

On the next day of the trade show, the man returned and chided the
guard, saying: "I escaped with a vast booty yesterday, but today will be
even better." So the guard watched him ever more closely, but to no
avail.

On the final day of the trade show, the guard could restrain his
curiosity no longer. "Sir Thief," he said, "I am so perplexed, I cannot
live in peace. Please enlighten me. What is it that you are stealing?"

The man smiled. "I am stealing ideas," he said.

== 20; 12021 H.E.

Prince Wang's programmer was coding software. His fingers danced upon
the keyboard. The program compiled without and error message, and the
program ran like a gentle wind.

"Excellent!" the Prince exclaimed. "Your technique is faultless!"

"Technique?" said the programmer, turning from his terminal, "What I
follow is Tao – beyond all techniques! When I first began to program, I
would see before me the whole problem in one mass. After three years, I
no longer saw this mass. Instead, I used subroutines. But now I see
nothing. My whole being exists in a formless void. My senses are idle.
My spirit, free to work without a plan, follows its own instinct. In
short, my program writes itself. True, sometimes there are difficult
problems. I see them coming, I slow down, I watch silently. Then I
change a single line of code and the difficulties vanish like puffs of
idle smoke. I then compile the program. I sit still and let the joy of
the work fill my being. I close my eyes for a moment and then log off."

Prince Wang said, "Would that all of my programmers were as wise!"

– Geoffrey James, "The Tao of Programming"

== 17; 12021 H.E.

A truly great man will neither trample on a worm nor sneak to an
emperor.

– B. Franklin

== 356; 12020 H.E.

TV is chewing gum for the eyes.

– Frank Lloyd Wright

== 342; 12020 H.E.

By studying the masters – not their pupils.

— Niels Henrik Abel

== 341; 12020 H.E.

My name is Ozymandias, King of Kings;

Look on my Works, ye Mighty, and despair!

== 338; 12020 H.E.

The unexamined life is not worth living

– Socrates

== 336; 12020 H.E.

The longest part of the journey is said to be the passing of the gate.

– Marcus Terentius Varro

== 335; 12020 H.E.

"When you wake up in the morning, Pooh," said Piglet at last, "what's
the first thing you say to yourserf?"

"What's for breakfast?" said Pooh. "What do _you_ say, Piglet?"

"I say, I wonder what's going to happen exciting _today_?" said Piglet.

Pooh nodded thoughtfully.

"It's the same thing," he said.

== 331; 12020 H.E.

Q: How many Harvard MBA's does it take to screw in a light bulb?

A: Just one. He grasps it firmly and the universe revolves around him.

== 322; 12020 H.E.

Don’t go around saying the world owes you a living. The world owes you
nothing. It was here first.

— Mark Twain

== 318; 12020 H.E.

The only thing we have to fear is fear itself.

— Franklin Delano Roosevelt

== 315; 12020 H.E.

Judge each day not by the harvest you reap, but by the seeds you plant.

— Robert Louis Stevenson (Found on the back of my red wine vinegar
bottle)

== 314; 12020 H.E.

The devil can cite Scripture for his purpose.

— William Shakespeare, “The Merchant of Venice”

== 313; 12020 H.E.

University politics are vicious precisely because the stakes are so
small.

— C. P. Snow (see "Sayre's law")

== 305; 12020 H.E.

It doesn't interest me what you do for a living. I want to know what you
ache for and if you dare to dream of meeting your heart's longing.

It doesn't interest me how old you are. I want to know if you will risk
looking like a fool for love, for your dream, for the adventure of being
alive.

— Oriah Mountain Dreamer

== 303; 12020 H.E.

Liberty lies in the hearts of men and women; when it dies there, no
constitution, no law, no court can save it; no constitution, no law, no
court can even do much to help it.

— Learned Hand, Spirit of Liberty

== 300; 12020 H.E.

For there are moments when one can neither think nor feel. And if one
can neither think nor feel, she thought, where is one?

— Virginia Woolf, "To the Lighthouse"

== 299; 12020 H.E.

Are we THERE yet?

Note: that is actually how I was taught Fundamental theorem of calculus

== 295; 12020 H.E.

When I reflect upon the number of disagreeable people who I know who
have gone to a better world, I am moved to lead a different life.

— Mark Twain, Pudd'nhead Wilson

== 292; 12020 H.E.

Q: How many lawyers does it take to change a light bulb?

A: Whereas the party of the first part, also known as "Lawyer", and the
party of the second part, also known as "Light Bulb", do hereby and
forthwith agree to a transaction wherein the party of the second part
shall be removed from the current position as a result of failure to
perform previously agreed upon duties, i.e., the lighting, elucidation,
and otherwise illumination of the area ranging from the front (north)
door, through the entryway, terminating at an area just inside the
primary living area, demarcated by the beginning of the carpet, any
spillover illumination being at the option of the party of the second
part and not required by the aforementioned agreement between the
parties.

The aforementioned removal transaction shall include, but not be limited
to, the following. The party of the first part shall, with or without
elevation at his option, by means of a chair, stepstool, ladder or any
other means of elevation, grasp the party of the second part and rotate
the party of the second part in a counter-clockwise direction, this
point being tendered non-negotiable. Upon reaching a point where the
party of the second part becomes fully detached from the receptacle, the
party of the first part shall have the option of disposing of the party
of the second part in a manner consistent with all relevant and
applicable local, state and federal statutes. Once separation and
disposal have been achieved, the party of the first part shall have the
option of beginning installation. Aforesaid installation shall occur in
a manner consistent with the reverse of the procedures described in step
one of this self-same document, being careful to note that the rotation
should occur in a clockwise direction, this point also being
non-negotiable. The above described steps may be performed, at the
option of the party of the first part, by any or all agents authorized
by him, the objective being to produce the most possible revenue for the
Partnership.

== 285; 12020 H.E.

Zounds! I was never so bethumped with words since I first called my
brother's father dad.

— William Shakespeare, "Kind John"

== 281; 12020 H.E.

In a mad world, only the mad are sane.

— Akira Kurosawa

== 280; 12020 H.E.

Ours [i.e., the Christian religion] is assuredly the most ridiculous,
the most absurd and the most bloody religion which has ever infected
this world. Your Majesty will do the human race an eternal service by
extirpating this infamous superstition, I do not say among the rabble,
who are not worthy of being enlightened and who are apt for every yoke;
I say among honest people, among men who think, among those who wish to
think. … My one regret in dying is that I cannot aid you in this noble
enterprise, the finest and most respectable which the human mind can
point out.

— Voltaire to Frederick II, 1767

== 278; 12020 H.E.

Go to Heaven for the climate, Hell for the company.

— Mark Twain

== 275; 12020 H.E.

Fate goes ever as fate must.

— Beowulf, 455

== 274; 12020 H.E.

Those who would give up essential Liberty, to purchase a little
temporary Safety, deserve neither Liberty nor Safety.

— Benjamin Franklin

== 273; 12020 H.E.

The meaning of life is that it ends

— Franz Kafka

== 272; 12020 H.E.

Thank goodness technology progressed to the point where we don't have to
deal with our issues privately

== 271; 12020 H.E.

All it takes for evil to succeed, is for good people to say - "It's a
business"

== 265; 12020 H.E.

There are no bad questions, only horrible answers

== 260; 12020 H.E.

Men learn to love the woman they are attracted to. Women learn to become
attracted to the man they fall in love with.

— Woody Allen

== 259; 12020 H.E.

Man plans, God laughs

== 257; 12020 H.E.

No good deed goes unpunished.

== 256; 12020 H.E.

There are no sides in this world, only players

== 249; 12020 H.E.

Nature abhors a vacuum.

— Aristotle

== 248; 12020 H.E.

A wise man can learn more from a foolish question than a fool can learn
from a wise answer.

— Bruce Lee

== 247; 12020 H.E.

Those who abjure violence can do so only because others are committing
violence on their behalf.

— George Orwell

== 241; 12020 H.E.

Misery is wasted on the miserable.

— _Louie_

== 238; 12020 H.E.

Almost nothing great has ever been done in the world except by the
genius and firmness of a single man combating the prejudices of the
multitude.

— Voltaire, correspondence with Catherine the Great

== 237; 12020 H.E.

Most people do not really want freedom, because freedom involves
responsibility, and most people are frightened of responsibility.

— Sigmund Freud, Civilization and Its Discontents

== 236; 12020 H.E.

Вот как нам писать. Пушкин приступает прямо к делу. Другой бы начал
описывать гостей, комнаты, а он вводит в действие сразу

— Л. Н. Толстой (запись в дневнике С. А. Толстой от 19 марта 1873).

== 232; 12020 H.E.

"Internally, Emacs still belives it’s a text program, and we pretend Xt
is a text terminal, and we pretend GTK is an Xt toolkit. It’s a fractal
of delusion."

— marai2 (Hackernews comments)

== 230; 12020 H.E.

Against stupidity the very gods; Themselves contend in vain.

— Friedrich Schiller

== 226; 12020 H.E.

Life is too important to be taken seriously.

— Oscar Wilde

== 223; 12020 H.E.

To live is the rarest thing in the world. Most people exist, that is
all.

— Oscar Wilde

== 222; 12020 H.E.

Be yourself; everyone else is already taken.

— Oscar Wilde

== 219; 12020 H.E.

Let us cultivate our garden.

— Candide

== 214; 12020 H.E.

Religion is like a blind man looking in a black room for a black cat
that isn't there, and finding it.

— Oscar Wilde

== 213; 12020 H.E.

In all the known history of Mankind, advances have been made primarily
in physical technology; in the capacity of handling the inanimate world
about Man. Control of self and society has been left to to chance or to
the vague gropings of intuitive ethical systems based on inspiration and
emotion. As a result no culture of greater stability than about
fifty-five percent has ever existed, and these only as the result of
great human misery.

— Isaac Asimov

== 212; 12020 H.E.

The true delight is in the finding out rather than in the knowing.

— Isaac Asimov

== 207; 12020 H.E.

Excessive bureaucracy is the start of the fall of any civilization

== 206; 12020 H.E.

Все счастливые семьи похожи друг на друга, каждая несчастливая семья
несчастлива по-своему.

— Leo Tolstoy

== 205; 12020 H.E.

It seems to me, Golan, that the advance of civilization is nothing but
an exercise in the limiting of privacy.

— Janov Pelorat, _Foundation’s Edge_

== 204; 12020 H.E.

Any sufficiently advanced technology is indistinguishable from magic.

— Arthur C. Clarke

== 203; 12020 H.E.

If this is the solution, I want my problem back.

— nosystemd.org

== 202; 12020 H.E.

Most people are other people. Their thoughts are someone else's
opinions, their lives a mimicry, their passions a quotation.

— Oscar Wilde

== 201; 12020 H.E.

Never let your sense of morals prevent you from doing what is right

— Isaac Asimov

== 199; 12020 H.E.

Those who can make you believe absurdities can make you commit
atrocities.

— Voltaire

== 197; 12020 H.E.

Violence is the last refuge of the incompetent.

— Isaac Asimov

== 196; 12020 H.E.

Committee, n.:

A group of men who individually can do nothing but as a group decide
that nothing can be done.

– Fred Allen

== Monday, July 6th, 2020

"When I picture it in my head I think of the early web as more of a
library. Over time it has transitioned into a shopping mall."

– chris_f (Hacker News comments)

== Saturday, July 4th, 2020

In each of us sleeps a genius… and his sleep gets deeper everyday.

== Tuesday, June 23, 2020

The galaxies hum the shape and form in their essence. That is their
secret.

The particles whisper of the nature of proper interactions. That is
their game.

And during a storm, in the forest, on the right night, it is no secret
that the leaves all sing of God.

– Exurb1a, _The Fifth Science_

== Tuesday, June 9, 2020

It is by the fortune of God that, in this country, we have three
benefits: freedom of speech, freedom of thought, and the wisdom never to
use either. – Mark Twain

== Wednesday, May 20, 2020

C++ is history repeated as tragedy. Java is history repeated as farce. –
Scott McKay
