#+setupfile: ../_film.org
#+date: 144; 12025 H.E. 2150
* A Taxing Woman
Going through Juzo Itami's filmography in an almost random-like order offers one
of the more jarring experiences I have had with any other director's
portfolios. The one anchor that is impossible to remove from any of his films,
to the point where it would not be a moving picture made by Juzo Itami---Nobuko
Miyamoto starring as the central character, as the heroine of the story, the
star that constantly steals the show. One cannot forget the recurring acting
staff that pops in and out of his movies at a regular cadence.

First we followed Nobuko Miyamoto as Tampopo in /Tampopo/, the ramen chef of a
struggling joint, then followed her into the world of supermarkets in
/Supermarket Woman/, where the decade plus passed since the former film had taken
a visible toll on all the lovable and recognizable faces. In this installment,
which is the third one for me, we follow the intricacies of the Japanese tax
system---where inspectors and tax investigators go and find missing tax dollars
like the country would go wholly bankrupt without every single collected yen.

Where I first enjoyed the Western-like story of /Tampopo/ with its odd vignettes
and truly unique in its setting of choice of /Supermarket Woman/, this
installment, fresh out of the oven right after the success of /Tampopo/ had left
me not too impressed with what it had to say; and even with all the exciting tax
evasion procedurals, seeing our shining ramen knight in armor Goro from /Tampopo/
playing probably one of the most polar-opposites roles to what was before---the
entire picture from its start to its end felt flat and uninspiring.

It is this unfortunate state, where the scenes themselves look and sound funny
in my head, but if I really try to think about it as a whole creature and
connect the pieces or simply recall what the whole story looked like, felt
like---I'm having some real trouble getting my mind to weave the thread or even
have my heart whisper on what it thought. Not because there was anything
controversial, but because it feels apathetic with the consequence of having
nothing to say.

{{{three}}}
