* The awkward moment of me being naked at a conference

NOTE: This was a dream of mine.

I can't be late. I can't be late. I cannot be late. Donald Knuth himself is
coming to the presentation tonight; I want to see him and all the other special
guests we are having. Jame and Ethan should already be there. Hopefully it
doesn't start too soon.

Alright, I'm here. Let me see... Wow, this is a /lot/ of people. Oh, there they
are. I see Donald Knuth sitting right behind us, many other names that I can't
recognize or see well. Should be starting soo...

*WHAT*; I'm not wearing any pants. It's not like I'm fully naked, but I only have
underwear on. Bright green underwear with flowers on it. /This isn't even my
underwear/. What the fuck. How did I enter here with no one noticing? I swear I
remember how I walked in.

Jame is wearing something of a long sweatshirt. Maybe I could just pull an
ancient Roman and tie it around my waist, so I have something of a kilt,
something to cover the bright acid green panties (not even boxers?) that I'm
wearing right now in the middle of a tech conference.

``Hey, listen, Jame,'' I said quietly not to interrupt anything going on around
us. ``Could you loan me your sweatshirt? Promise I'll give it back when we're
out of here.'' I think he noticed that I'm not wearing any paints.

ALl of the sudden, he exclaimed, *``YOU WERE GOATED AND NOW PANTLESS!''* Well,
you don't have to yell that out loud. Wait, why did you yell that out loud? The
whole audience of hundreds of people can hear you.

*``THIS IS SO FUCKING FUNNY LOL LMAO MONKAW''*, he said so loud that I thought I
would go deaf because of the sheer fucking embarassment.

Suddenly, a woman to Jame's left and a man behind him stood up; they quickly
escorted him out of the hall. All I saw in that moment was Ethan's face of pure
shock or joy. I couldn't pinpoint which one it was exactly.

I can't stay here any longer. I'm pantless, naked, and afraid.

``Yo, Ethan, let's dip,'' I said in a lower voice than Jame did.

``Yeah, let's go.''

I was walking down the hallway, still just in my underwear. Time to leave. I
opened the door, it's freezing cold. Is it winter again? The roads are all
snowy; it's hailing.

To my right I see Ethan carrying Jame on his back. I wonder why. Jame definitely
doesn't look too happy. I think I saw him being kinda grumpy in the hallway when
we were leaving.

Huh, was the conference here in Burge Union? That's not too far away from
Towers. I just need to cross the road.

I fell. I'm in the middle of the crosswalk on my fours and I can't stand
up. It's freezing. I'm starting to lose any kind of sensations from my limbs and
fingers. This isn't good.

Okay, by some miracle I found my way into Towers on my floor.

Why are my drawers outside? They're just on the floor right outside of the
apartment door. Why are the drawers open? Who are those girls ravaging through
it?

``Hi, I don't really like my clothes and drawers be all open in public,'' I said
in a midst of a pure confusion.

``Oh, don't worry, we can go through it together,'' the cute girl with
interesting tattoos said to me.

Thinking of it, why do we need to go through me clothes?

I asked for her name, it was May or Maya. Probably May.

It's late and I'm cold. I entered the apartment, entered my bedroom.

Huh, it's morning? We are national champions now. Classes are not cancelled?
