* The Ideal of Love in /Brothers Karamazov/

NOTE: This was written for my literature major capstone. The submission was a
PDF file, which can be [[The Ideal of Love in Brothers Karamazov.pdf][found here]].

What does it mean to love someone? This is the question I asked myself many
times over my own life with its tried and failed attempts at love. Fatefully,
one summer, I discovered /Brothers Karamazov/ by Fyodor Dostoevsky, which
reinvented the many ways I used to perceive what life has to offer. Standing
here, I realize what a transitional experience it has been for many people who
have had the pleasure and struggle to enter Dostoevsky’s mind in what has been
acclaimed as one of the supreme achievements in world literature. One of the
essential factors in this moral transformation is discussing the true nature of
love. I am interested in researching the following question – “What is the ideal
of love for Dostoevsky in /Brothers Karamazov/?”

There are multiple ways of approaching this question. The classical path would
be following a qualitative analysis, reasoning about the love itself and its
upbringing throughout the novel. The following paper will attempt a new, fused
approach of combining qualitative analysis with quantitative pieces of
evidence. To support our findings in this research, I have built a custom corpus
that will perform all the necessary data retrieval and text processing.  

#+drop_cap
We designed and implemented a bespoke corpus – Katya to perform such text
analyses. Katya is a free and open-source language corpus. She can retrieve and
ingest any form of text and promptly execute unique algorithms, producing
exciting results to perform deeper analysis further. One of the algorithms we
wrote in the framework of Katya is called “word relation analysis.” Provided a
single word or a theme, Katya will go through each occurrence and count the
number of times other keywords appear within the target’s context. This is
incredibly useful, as it provides us with a quantitative view of how closely or
loosely topics appear in relationships with each other. More details on
accessing Katya and interacting with its features can be found on her
development webpage. [fn:: The development webpage of Katya on GitHub
([[https://github.com/thecsw/katya-dev][https://github.com/thecsw/katya-dev]]). Accessed on May 5, 2022] 

As the research question outlined, we are primarily interested in the topic of
love and what is its true nature for Dostoevsky. Providing Katya with the whole
text of /Brothers Karamazov/ and later requesting all the relations associated
with the word “любовь” (“love”), we find that the most frequently occurring term
is “деятельный” (“active”). We find that there are precisely fourteen such
occurrences within the novel. Other frequent keywords include: “сердце”
(“heart”) with 12, “человечество” (“humanity”) with 8, “подвиг” (“feat”) with 5,
“загореться” (“to burn with love”) with 4, and “гордость” (“pride”) with 4. We
will mainly focus on the “active” keyword, as it occurs more than any other term
and is not trivial, like “heart.” We can infer from the data that Dostoevsky
includes “love” and “active” close to each other. This provides us with an
intriguing development to our main question, which we can extend further by
exploring a newly revealed connection; specifically, “What is ‘Деятельная
Любовь’ (‘Active Love’)?” 

To tackle this question, let us understand what is defined by “love.” It is an
elusive term that is perceived differently in an uncountably unique number of
ways. Merriam-Webster defines love as “strong affection for another arising out
of kinship or personal ties,” “attraction based on sexual desire,” or “warm
attachment, enthusiasm, or devotion.” [fn:: Merriam-Webster definition of “love”
([[https://www.merriam-webster.com/dictionary/love][https://www.merriam-webster.com/dictionary/love]]). Accessed on May 5, 2022]
Notice that nowhere in those definitions do we see a hint to action or
performance of love. The most common understanding of love is purely defined
through the lens of one’s affection and adoration, which means more experiencing
feelings rather than taking action toward another person, an inanimate object,
or God.  

#+drop_cap
Love, in this standard definition, is a subjective feeling. To deepen our
understanding of such a feeling in this framework, I would like to outline my
sense of love. Allow me to start from a contrarian take. Many find love to be
the mere combustion of hormones and chemical elements in one’s brain, resulting
in human emotions. I find this explanation utterly dull and uninspired, as it is
spoiled by the tree of death, known as science. This view of it robs us of any
more profound craving and yearning for learning about the true nature of what it
means to love someone. There must be a higher purpose; it must have a noble
origin; I would even dare say a divine source. Love is what propelled humanity
into civilization and got us through the darkest times of humanity’s history and
each individual’s life story. Love inspired us to pursue greatness, discover
fine arts, and produce the most extraordinary pieces of literature, art, and
music that transcend the limits of time and inspire many generations that
follow. In our world, our Universe, there is nothing purer than
Love. Dostoevsky, for the most part, sees it a little differently. He creates a
distinction between two types of love: the passionate, romantic type, which
finds its roots in lust; and the one we could call his ideal – “деятельная
любовь” (“active love”). I will explore how do they differ and does romantic
love have to be “деятельная” (“active”)? 

Dostoevsky’s works are packed to the brim with passion and burning
love. Everything is happening in the heat of the moment, at the peak of intense
desire. He captures the Dionysian nature of life. His love is purely Dionysian,
driven by fiery volcanic-like explosions and the innate lust of the human soul’s
core. The path a man walks on is isomorphic to the one of
suffering. Dostoevsky’s characters’ feelings know no bounds nor laws. Only in
this state can one understand the actual depth of the human soul. As we explored
the standard definitions above, love is affection; it’s meant to be romantic,
connect people, and lead them to better lives. However, Fyodor Mikhailovich sees
love as a necessary instrument to uncover one’s path littered with
tragedies. Interestingly enough, this is how Dostoevsky views the first type of
love we mentioned above, the love born out of lust. [fn:: /Язык
Ф.М. Достоевского : идиоглоссарий, тезаурус, эйдос : Монография./ Москва :
ЛЕКСРУС, 2015.]

#+drop_cap
When it is meant to bring people together, he sees it as dividing them. In his
works, we see the tormenting parts of love, the parts we tend to ignore or gloss
over in our lives, as it would be too much to bear for one person. Dostoevsky
brings those issues to an open discussion. Passionate love doesn’t bridge the
gap; it only deepens and widens the canyon of discord. [fn:: /Русский Эрос, или
Философия любви в России./ Vladimir Solovyev, 1991.] Ultimately, loving
someone means destining your demise. We must recognize that this is not the
ideal of love. It is truly fascinating that there exists one kind of love that
Dostoevsky describes as a positive rather than a destructive force of human
nature - “Деятельная Любовь” (“Active Love”). Let us now return to the data
retrieved from Katya and explore Dostoevsky’s idea of “Деятельная Любовь” and
how it compares to modern ideals of love. 

A couple of the fourteen occurrences of “деятельный” appear in a passage from
Book II, Chapter IV – “Маловерная Дама” (“A Lady of Little Faith”). In this
chapter, we have Lise’s mother visiting Father Zosima. He is the Elder and
spiritual advisor in the town monastery. He is revered and admired amongst the
townspeople for his well-known prophetic and healing abilities, which is why the
lady visits Zosima. She wishes to thank the Elder for healing her daughter,
Lise, who hadn’t had night fevers ever since their last visit not too long
ago. Naturally, the conversation develops into the mother asking Zosima for a
piece of advice regarding the pain and suffering worries that have occupied her
mind – the loss of faith or the lack of it. She is in a complete state of
crisis, as the ideas of pure nothingness following the life and the mystery of
what the future holds are proving to be something truly terrifying to one’s
heart. 

#+begin_quote
“Ну что, думаю, я всю жизнь верила — умру, и вдруг ничего нет, и только
«вырастет лопух на могиле», как прочитала я у одного писателя. Это ужасно! Чем,
чем возвратить веру? […] Это убийственно, убийственно!” (Dostoevsky, /Brothers
Karamazov/)
#+end_quote

In a genuinely fascinating fashion of Dostoevsky’s writing, Father Zosima
acknowledges the killing nature of such a crisis. One cannot prove the existence
of God or demonstrate the opposite, but what one can do is make sure of his
being for themselves. Following Zosima’s reply to The Lady of Little Faith, we
find that the only way to do so is through “опытом деятельной любви” (“the
experience of active love”).

#+begin_quote
“— Опытом деятельной любви. Постарайтесь любить ваших ближних деятельно и
неустанно. По мере того как будете преуспевать в любви, будете убеждаться и в
бытии бога, и в бессмертии души вашей. Если же дойдете до полного самоотвержения
в любви к ближнему, тогда уж несомненно уверуете, и никакое сомнение даже и не
возможет зайти в вашу душу. Это испытано, это точно.” (Dostoevsky, /Brothers
Karamazov/)
#+end_quote

Notice that Dostoevsky’s intent with Father Zosima was to portray the Orthodox
Church and its beliefs as a positive social and spiritual ideal. Through the
words of Zosima, Fyodor Mikhailovich not only defines love but also the meaning
of life through the experience of loving the ones who are dear to you and,
additionally, proving said love by acting. This action, driven by passion, must
be constant and increasingly successful in its undertakings. From a cynical
point of view, it takes relatively small or no effort for one to confess their
love to another person or humanity.

I can say I love someone without harboring loving feelings for that person. It
doesn’t necessarily imply a malicious attempt of misleading, yet it would
indicate how impoverished my soul is to make such a baseless proclamation. Let’s
put my soul aside. Unfortunately, because it is easy to say things without
meaning, many get deceived by their “love” or someone else’s. This kind of
“love” will assuredly grant everyone involved with a passport straight to the
miserable ending that awaits.  In /Brothers Karamazov/, Grushenka expresses her
intense feelings to Fyodor Pavlovich Karamazov, driving all the characters to
their limits throughout the novel. It resolves only for Grushenka to realize
that Dmitri is the one she truly loves. It made me wonder whether this was love
or merely a tragic manifestation of lust. If it were the latter, what would make
it “active”?

It must be in its name; an action makes love active. In Dostoevsky’s view, for
love and affection to be true, they should be backed up by acts with a purpose
to do good for the loved person, even if sacrifices have to be made; selfless
intentions should drive actions. What is precisely meant by an action? One of
the significant ways one can show affection for another is through material or
financial means. This would include gifts, presents, and money. It is no secret
that this is one of the most popular ways of expressing feelings towards
another. While I think it is an essential part of acting on love, such as being
able to part with material holdings to help another, it does not make up for the
whole “acting on love” narrative.

Monetary advances can help in many circumstances, but they do not give the soul
a sense of fulfillment that many hope it does. Those financially driven actions
cannot wholly acquire the ideal of love that Dostoevsky is discussing. Recall
that Fyodor Karamazov, with all his gifts and money, prepared out of “love” for
Grushenka so she would have nothing else to worry about financially, which was
the very reason for his very own death. What he thought was his passion for
Agrafena Alexandrovna Svetlova could be seen as a salacity moved forward by
emotional lacerations. If financial motives are not the core of “active love,”
something else must serve as its foundation.

#+drop_cap
The idea of loving and being loved is lovely to our psyche. Love is not limited
to just interpersonal situations; it expands and scales to humanity and all
people. One can argue how they love people and are ready to abandon everything
they know and all the comforts to sacrifice themselves for the greater good. It
sounds romantic and noble, something one can fulfill their purpose in life
with. We must ask them and conclude whether they are ready to make those
sacrifices, put money where their mouth is, or is it just a hollowed-out talk so
they can feel good about themselves. The Lady with Little Faith expresses a
similar desire to leave her daughter, join sisters of mercy, and care for
suffering martyrs.

#+begin_quote
“— Деятельной любви? […] Видите, я так люблю человечество, что, верите ли,
мечтаю иногда бросить всё, всё, что имею, оставить Lise и идти в сестры
милосердия. […] Я бы перевязывала и обмывала собственными руками, я была бы
сиделкой у этих страдальцев, я готова целовать эти язвы...” (Dostoevsky,
/Brothers Karamazov/)
#+end_quote

It is interesting to explore what is stopping us from pursuing such virtuous
dreams? On my account, it is the gratitude I will receive or its absence. Doing
great deeds is good, primarily when we get acknowledged for them. This sense of
others being grateful for our noble undertakings and virtuous causes is ever so
sweeter when it comes to us immediately. Others must promptly recognize the
efforts that I have put into utilitarian goals. Even though I acted and claimed
that my love for people inspired it, is it the kind of love that Dostoevsky can
see as an example of good? The resolution I find is that he would not. Even
though I acted on my passion, it was not selfless nor pure. Such struggles are
wrongly fueled by the much darker and selfish motivations for fame and pay. No
true love can be born in those conditions. If love is not proven by monetary
means or finances, where do we find the balance, the golden center between
apathy and Dostoevskian “надрывы” (“strains”)?

I observe it can be found within the internal discipline. For Dostoevsky, the
ideal form of love cannot be found or bought. The proper form must be brought up
from within, disciplined, and nurtured. It results from hard work, mistakes, and
experience of living. Love is not unique to good people or the ones who deserve
it. Even villains and less virtuous people can experience love, even for a
moment. However, the ideal of love for Dostoevsky is not of a fleeting moment
but a product of wearing and prolonged work. It cannot be bought nor easily
acquired, as it borders and later evolves into the end-bringing debauchery. One
of the primary reasons why Fyodor Mikhailovich’s characters are so entrancing is
because they all live through the most turbulent, unbalanced, and raw form of
love. Unhinged by societal standards and breakers, they experience the depths of
both happiness and misery. Love and Lust. Heaven and Hell. Only Alyosha is shown
to be able to love actively; if he falls in love, his very next instinct of his
would be to help them by setting a clear goal in mind.

In his novel, Fyodor Mikhailovich created an image of a “doer,” which contrasts
with a “dreamer” that Dostoevsky has frequently employed in his previous
works. Compared to “Crime and Punishment” and “Demons,” he presents us with a
possessor of “деятельной любви.” [fn:: Накамура К. /Словарь персонажей
произведений Ф. М. Достоевского./ — СПб.: Гиперион, 2011.] He doesn’t have the
desire to become famous, nor does he have the experience of a long life. He does
have the strength and wisdom to love people and respond to their trust. He
understands their tragedies and allows them to seep through him; this is how he
shows his active love. For our discussion of love, Alyosha is the question and
the answer. He manifests and exercises the “active love” that Dostoevsky sees as
the ideal. He describes in the novel,

#+begin_quote
“В этой путанице можно было совсем потеряться, а сердце Алёши не могло выносить
неизвестности, потому что характер любви его был всегда деятельный. Любить
пассивно он не мог; возлюбив, он тотчас же принимался и помогать.” (Dostoevsky,
/Brothers Karamazov/)
#+end_quote

#+drop_cap
One of the prime examples is Alyosha’s relationship with his father, Fyodor
Karamazov. His father is far from an example of a good father. Where all of his
sons have rejected him as their father or attempted to disown him, Alyosha was
the only one capable enough and wise enough to accept his father for who he is
while also serving as his guide out of the Hell on Earth Fyodor created for
himself. This is seen at the beginning of the novel when Alyosha says – “Не злой
Вы человек, а исковерканный,” which shows Dostoevsky’s idea that outward evil or
immorality we see in a person does not mean the complete disintegration of their
identity. Because Alyosha can still love his father after everything he made his
sons and everyone around him go through, Dostoevsky shows that even someone like
that could still be loved. This love is not primarily built by affection,
fondness, or lust; it is spawned by acceptance and a great deal of
understanding.

Another excellent example of “active love” is Alyosha’s relationship with his
brother Dmitri. This happens during one of the final scenes of the novel. After
the trial had concluded and found Mitya guilty of murdering his father, Ivan
tried to find any possible ways to break Dmitri out of serving his
sentence. However, Alyosha told his brother that even if he didn’t commit the
crime physically, he needed to bear the cross for his past actions and
wrongdoings. It might seem paradoxical why Alyosha encourages his brother to
live through the consequences of his conviction; however, this hurts Alyosha as
much, if not even more. Ivan’s plan and a possible breakout might do more harm
and worsen Dmitri’s future state. Alyosha proves his “деятельная любовь” with
his sacrifice of committing his brother to prison, yet understanding this is the
better path for Dmitri.

Those are examples of familial love. This asks us if Dostoevsky sees a way for
romantic love between partners to exist within the scope of an “active love?”
Yes, he does. As we saw, Alyosha possesses the ability to “любить деятельно,”
which also applies to his romantic relationship with Lise. When our characters
are in the deepest corners of their personal tragedies, when their stories find
themselves in painful isolation, Alyosha and Father Zosima have the affirmation
of life and liberty from captivity. They are the ones to bring peace to the
sufferings of others. When Lise was at her crisis moment, when she “полюбила
беспорядок,” Alyosha was ready to give his all and everything for Lise’s
wellbeing. Where one “loving” would give up on their partner if anything so
close happened, Alyosha, in all his wisdom, understands and acts upon his love,
which makes it active.

/Brothers Karamazov/ taught me the importance of proving my love, as it is the
holder of truth - “And now these three remain: faith, hope and love. But the
greatest of these is love” (Corinthians 13:13). It is easy to say and confess
feelings but staying true to yourself and being sincere with your own feelings
is an ordeal that very few can overcome. With the heroes of our story, we
realize it has to be this way.

#+begin_quote
“Братья, любовь — учительница, но нужно уметь ее приобрести, ибо она трудно
приобретается, дорого покупается, долгою работой и через долгий срок, ибо не на
мгновение лишь случайное надо любить, а на весь срок. А случайно-то и всяк
полюбить может, и злодей полюбит.” (Dostoevsky, /Brothers Karamazov/)
#+end_quote
