= Счастье маленького человека 🧥
Sagindyk Urazayev <ctu ku edu>
About_LINK | Bookshelf_LINK | Fortunes_LINK | Home_LINK
:toc: left
:toc-title: Table of Adventures ⛵
:nofooter:
:experimental:

In the Spring of 2021, I took one of the best courses ever! This was
RUSS 712, a graduate class in Russian Literature. We read all the
beautiful short stories by such masters like Pushkin (Blizzard), Gogol
(The Overcoat) Tolstoy (Blizzard), Chekhov (The Lady with the Dog),
Dostoevsky (The Dream of a Ridiculous Man), and dozens more. We would
progress ourselves into modern times, so starting from 19th century and
ending up somewhere in 2010s.

As a final project for the course, we had to make a 15-minute recorded
video of us talking in TED-talk style about a research topic of our
choice. My choice was called Счастье маленького человека (Little Man's
Happiness), where I contemplated about what does it mean for a fallen
man to be happy, basing on works of Gogol, "The Overcoat", and
Dostoevsky, "The Dream of a Ridiculous Man". The video itself is in
Russian. Sorry, I just couldn't bring myself to record an English
version after doing close to 50 full takes of my talk.

At least you get to see a moving picture of me! Haha

-> https://youtu.be/dtVUzEh7Ddo[Go to the recorded presentation]
