* It's all one 🍞

287; 12022 H.E.

I ask myself what is evil and good. What separates those two? Across
generations of poetry, thoughts, and religion, those two have been at each other
for as long as time can remember. We always imagine evil working as a
corrupting force on people -- bringing their fall upon them. All in a while, the
forces of good are actively battling those Machiavellian-like creatures. It's
all exciting, almost like an action movie, where you can side with one or the
other and root for them. What a narrow-minded way of thinking this is.

In actuality, those scary creatures we like to root against are simply mirrors
of our own darker selves. Good and evil are not great opposing
powers in a constant state of war -- they are two sides of the same
coin. Simply put, it's all one. We need both of them. One without the other
impoverishes our souls. When all is good with nothing in between, we lose the
taste of life. This is the complicated nature of man, which would ruin Heaven
when it gets boring. On the contrary, all evil is caricature-esque and
impossible when there is no good to define or oppose it.

#+drop_cap
Our hearts have both greatness and misery in them. Those two existing
next to each other fulfill us as humans and push us to evolve -- in one way or
the other. The fact of that is not bad or good. It is us. We are defined by the
complex universe that is our soul. Many ask, why do bad things happen to good
people? How can God permit such disasters to occur to his Children?

/Book of Job/ is the classical route for thinking about why God permits evil. The
great forces of all we think we know are on it together. A man’s downfall or
ascendance is brought in by the same power that lets humanity go 
through the spiral-like ladder of life. To be even more pedantic, there might
not even be good or evil -- it all just is.

#+begin_quote
While Eyeore frets... \
...and Piglet hesitates \
...and Rabbit calculates \
...and Owl pontificates \
...Pooh just /is/. \
(Benjamin Hoff, /The Tao of Pooh/)
#+end_quote

I bet it's great to wake up in the morning and pick a side you're
on. ``Everything that's not on my side is my foe; therefore, I shall go against
them.'' It probably takes a great deal of humility and intense vulnerability in
one's beliefs to understand the combative nature of thinking we've been taught
to live with. If that is living. Maybe just existing and having something
or someone to blame for your misfortunes. ``Oh, it's the devil's doings.''

#+begin_quote
I am poor, but... I won’t say very honest, but... it’s an axiom generally
accepted in society that I am a fallen angel. I certainly can’t conceive how I
can ever have been an angel. If I ever was, it must have been so long ago that
there’s no harm in forgetting it. Now I only prize the reputation of being a
gentlemanly person and live as I can, trying to make myself agreeable. I love
men genuinely, I’ve been greatly calumniated! [...]
/Satan sum et nihil humanum a me alienum puto./[fn:: I am Satan, and deem nothing
human alien to me.] \
(Dostoevsky, /Brothers Karamazov/)
#+end_quote

It reminds me of /Brothers Karamazov/, which in many ways, is the foundational text of
my life. What I have been before and after are two separate ways. I
digress. In the story, Ivan is intellectually brilliant, an atheist with a
dictum, ``if there is no God, everything is lawful'' that defines the novel’s
motif. In arguments with his younger brother, Alyosha, who never 
received a formal education, a novice in the local Orthodox monastery -- Ivan
completely overwhelms him with great points against the existence of God. 
Alyosha is overwhelmed to the end of a complete loss in countering or coming
back at his brother. Still, in all of this, Alyosha is the better man.

#+drop_cap
Let us live freely. Break down the chains of the mind and the traps of the
brain. Liberate ourselves from forced fears and dreads. We do not live in good
or bad times; they are. We live daily, and how we perceive them is wholly
reliant on our emotions and consciousness. At whatever moment of life we find
ourselves in, let us be in it and accept what we have. The universe is ruled by
letting things take their course. It cannot be ruled by interfering.
