#+setupfile: ../00_film_skipthis.org
#+date: 365; 12024 H.E. 2247
* Chungking Express
Exquisitely shot and directed film built on vibes and loneliness. Pure
cinema. Having watched [[https://sandyuraz.com/drama/in-the-mood-for-love/][/In the Mood for Love/]] for the tenth+ time---I wanted to
experience Wong Kar-Wai's earlier works and wow this was a pleasant ride. No
wonder how it could confuse and puzzle the audiences at first glance. Beyond
shallow reasons like having the two (almost) disconnected stories, the core
challenge---as I see it--- comes in appreciating the film for what it is, rather
than what it is not.

This brings up a topic that I love dearly---the age-old discussion of ``form''
vs ``content.'' I have written about this distinction plenty enough before
([[https://sandyuraz.com/blogs/against-interpretation][https://sandyuraz.com/blogs/against-interpretation]])---the gist comes to the
modern desire of desecrating works of art by ``analyzing'' and ``interpreting''
them into something else, something unintended nor desired; all of this, rather
than enjoying them exactly for what they are in the form and shape presented to
us. /Chungking Express/ is a perfect case study just for that.

Simply put, it's pure vibes. It's erotic. It's exhilarating. It's
scandalous. It's unapologetic. It's impish. It's daft. It's relentless. It's to
capture that very special feeling of loneliness. That excruciatingly embarassing,
suppressed, shameful, lustfully fulfilling, utterly hopeless rollercoaster of
emotions if missing someone, breaking up with them---living in delusions of you
two possibly coming back together---against any rational and most probably a
good reason on why you split up in the first place---this film captures it
all. Something that we won't tell anybody, not even to ourselves---but we will
do it, and do it again, and live it.

It's a bit of a shame that I don't actually like /California Dreamin'/, I prefer
their /Dream A Little Dream Of Me/---this wouldn't have any effect on my enjoyment
of the movie as a whole, though. Big fan of what Wong Kar-Wai is doing here. Big
fan of practically founding the shoegaze genre here. Big fan of inventing the
archetype of a pixie dream girl. Similar to his later work, the /magnum opus/ of
his career---I'll have to watch /Chungking Express/ a number of times to really
warm up to it and see if my heart can welcome it with open arms. Rewatchability
on this is insane. God, I love Hong Kong of that era and I'm low-key obsessed
with Kowloon Walled City and the Chungking Mansions (the building) is the
closest we will get to the glory and the allure of old Hong Kong.
