* Compress images with PCA  🎱
MATH 596: Computational Data Science by [[https://erikvv.ku.edu][Erik S. Van Vleck]] was quite a
trip. The philosophy of the course was "sink-or-swim", which means that you
either succeed in the class and what's expected or you just fail it
completely. Never have I ever gone through a more brutal multivariate
statistics crash course. I must admit that I met some wonderful people there
that I never would have had a chance to make an acquaintance with, if it
weren't for this class.

Our first small project was applying [[https://en.wikipedia.org/wiki/Principal_component_analysis][Principal Component Analysis (PCA)]] to
some old or new problems. I liked the theory and wanted to see how well I can
compress images, therefore extracting the most important (principal, haha)
components of a data set and present an approximation of it by only using a
fraction of the original set. I did in in python, I recommend running
=lenna.py= if you're curious to see how it works.

-> [[https://git.sr.ht/~thecsw/lenna/tree][Go to the PCA image compression code files]]
