#+date: 40; 12023 H.E.
* Lucifer 😈

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/CLg][The tail]]
- [[https://photos.sandyuraz.com/oFX][Top view]]
- [[https://photos.sandyuraz.com/ZeA][From the back]]
#+end_gallery

Helltaker by [[https://twitter.com/vanripperart][vanripper]] was my gateway anime. I /was/ [[https://sandyuraz.com/blogs/anime/][into anime]] way before when I
was still a boy, but this absolute-masterpiece-of-an-indie-game was *my*
renaissance. In the final year of university, during one of the tough times when
I struggled finding commitment and courage within me on what I wanted to do when
so many things changed in my life too quick for me to catch up -- those sharply
dressed demon girls and the man who wants to have them in his harem by going to
hell was what saved me and let me take my mind off to something exciting and
new.

How could I not be grateful? Helltaker has a very special place in my
heart. I've got this Lucifer figure, I have two figures for Justice (one is an
acrylic stand and the other is the new neondroid [pictures are yet to come]),
imported and shipped from Japan Helltaker artbooks and doujinshi. You can even
find in my [[https://sandyuraz.com/blogs/wrapped/][Wrapped 2021]] that /Vitality/ by Mittsies ranked at the very top of my
all-time listens and still lingers there even two years later.

[[https://open.spotify.com/track/4i0oGvIIrkoTLNCYJWnMvh][Vitality]]
