#+setupfile: ../00_film_skipthis.org
#+date: 111; 12025 H.E. 2150
* Tokyo-ga

My family saw this right after we finished ``Paris, Texas'' and as we all like Wim
Wenders' films—Japan is also a cool topic—see this little treat on the Criterion
Channel? What a treat it was indeed.

Visually as impressive as ``Paris, Texas,'' though only recorded on his handheld
camera, it has one of the topics of utmost interest to me—Yasujirō Ozu. I have
known stories and the history of Setsuko Hara, but getting more of a glimpse
into the peculiarities of Ozu's style, such as using a very specific camera
height with 50mm—incredibly inspiring and eye opening towards his famous works.

Nobody I know today pays this much attention to the very fundamentals of what
makes a film a film; of what makes a family tragedy so tragic; of the smallest,
most subtle, and inconsequential bits of reality that make us human. I aspire to
be this dedicated to the tradecraft, vision, and intuition. Though we have left
Ozu's world a long time ago. The jump scare with Werner Herzog had only proven
that more.

Maybe one day I should get into making plastic food, looks fun. I really can't
stop thinking about the colors; about the bloom; about the boy tugging his
mother's coat in the train station. Ozu's world shines through the cracks if we
look hard enough and tune our hearts to feel these fragile yet time-enduring
strings. Man. What a visual and an education treat.

{{{four}}}
