{{{film}}}
#+date: 49; 12026 H.E. 0337
* Innocents Abroad
Only after my first Les Blank experience in [[https://sandyuraz.com/drama/garlic/][/Garlic Is as Good as Ten Mothers/]],
I know I wanted more. He has this magical ability to both poke fun at something
but do it with such an open heart that it stays right on the fine line of being
wholesome, yet witty and satirical, and this is of course, the Americans'
adventures through Europe---with all the modern conveniences of life, like
traveling through a dozen countries in just under two weeks---with /maybe/ a day
per country according to my rough estimates!

Back then, in the 90s, it might have been the new fashion, I wouldn't know,
since I wasn't even a thought back then, but, seeing where we are now, even if
culturally, it's a questionable way to /really/ experience a place, but one thing
for sure and that is the commercial success of it, because it's
everywhere---ranging from the same ``Across-the-Europe'' whiplash to the lavish
/Royal Carribean Cruises/ taking its guests from one exotic location to another in
literally, a blink of an eye!

I'm of two competing minds on this. Emotionally, as someone who grew up and
spent most of his life in Europe and Asia, the idea of swinging by in dozen
countries, each rich with its history, food, and people, and then simply
``moving on'' to the next, without a real space to experience, think, or even
think about the place that is getting smaller in the back window of the
only-accelerating bus, it robs the traveler of the energy and the magic of being
/somewhere else/ that is not /what you know/ nor /where you know/.

One of my fondest memories is having a random long layover in Frankfurt, it must
have been more than sever or eight hours, so, we decided to just leave the
airport and go to the old downtown that my sister recommended to me. It's not
that we went to any particular place or had a plan of spots to visit in mind. We
simply sat in this one big square with locals and tourists alike, ordered a pint
of beer each, and that was it. Read some books. Drew something on a piece of
paper. Took a picture of two. Existing in that spot for all these hours, built
this connection to the city I've never been before and having only seen 0.001%
of it---it may be less than that---I'm excited to go back and get to know it a
little more.

Similarly how in the film, /Innocents Abroad/, they had the museum coordinator who
lambasted about tourists back in the day would spend /days/ seeing great works of
art, which was barely enough to scratch the surface, and now, having only maybe
a couple of hours of non-stop you-need-to-catch-up style of a toure, is there
really a point to doing this or is it better not do it all if one can't do it
right? What more important things are there in life, to the human psyche, to the
mind and the soul, than experiencing and /feeling/ all the great works of the
great people that came before us and all we have today standing on their
shoulders?

Les Blank could bring it full circle. The tourists after having returned from
their whiplash of an adventure, briefcases full of polaroids and SD cards hot
from all the images, they would start reliving the memories---now that they have
the time and space to do so---where the time spent /over there/ seems to be
stronger through remembering it after the fact than the actual feeling in the
moment of being /over there/. I wouldn't know which one is better. One that lasts
a few moments or forever in memories? They aren't mutually exclusive, of course,
but that seems to be the appeal. Especially, the biggest one, being the
convenience of having the entire trip planned and the financial aspect of it
covered through agent discounts, etc.

Maybe one day I should try one of those agency programs, could be fun---it
possibly could serve as a series of sneak peeks into places to some time later
visit for the sake of the place itself.

{{{four}}}
