* Eva TV ending is great! ☁️

189; 12023 H.E.

In one of the discord channels, a friend of mine asked his ChatGPT-based discord
bot to answer a question,

#+begin_quote
%talk can you give me 5 more anime with bad endings without spoilers?
#+end_quote

To which, as any LLM, it confidently proclaimed (it's set to talk like a
nekogirl),

#+begin_quote
"Neon Genesis Evangelion" - Personally, I enjoy this one's thought-provoking
ending! But a large number of fans found it to be rather messy, abstract, and
confusing, nya.
#+end_quote

As much as it is considered an accepted fact, I don't really share the same
sentiment, though I can totally understand where it's coming from.

#+begin_quote
people that hated the last two episodes are fucking lame
#+end_quote

Some would say,

#+begin_quote
But it was a shitty ending
#+end_quote

Here goes my quick reply, =verbatim=.

-----

hmmmmmmmmm, I can understand that, only in my view, I guess, meditating on the
ending for years. I came to agree that it is indeed a very good ending and the
film is as well. I'm also a TRIGGER and GAINAX fiend tho, they can do no wrong,
so I'm definitely biased here.

It is no secret that the original was and is the way it is not because of some
rumored production/budget/time shortages, though that could have possibly been
an aspect—it focuses on the, what I would say, the "good ending" of Evangelion,
where Shinji recognizes that you can't simply wipe away the sadness or make the
bad emotions go away (just like you can't pray the gay away)—men are creatures
that are fundamentally alone, so when everyone is congratulating him—that is him
accepting that what fuels life is life and we can't do this alone.

I love both the TV ending and EoE. They are the same, yet so different. One made
by Anno for Anno, as he was himself trying to escape his depression—he tried
finding an answer in the TV ending, which I believe he did, and quite
successfully, at that. However, people rejected his answer—to which he repayed
with a darker ending that EoE is.

I don't know, the fact of how at the times the offices were vandalized, death
threats, employees harassed—it showed how much people of that generation, a big
majority of people weren't ready for the original TV ending that Anno ripped out
of his heart. Maybe this only reinforces his point? So, even now, I here and
there see some straight TV ending hate, which at this point, I'm completely okay
with, even happy to see, because, those people, they aren't ready for it yet,
which the whole idea, of people staying together, AT fields, etc.—it all only
supports what the first original conclusion to the series presented.


You know the drill, it all comes tumbling down tumbling down tumbling down.
Loneliness is fundamental, such are human relationships. There is no one without
the other.

God Bless Evangelion

-----

One of my favorite posters is in the living room,

#+attr_darkness: image
[[https://photos.sandyuraz.com/MoN][THE FATE OF DESTRUCTION IS ALSO THE JOY OF REBIRTH]]
