{{{film}}}
#+date: 88; 12025 H.E. 2250
* Days of Being Wild

Days of Being Wild is where you can see WKW polishing and finding the style that
we would come to adore and love in Chunking Express and later in his absolute
and undisputed magnum opus, In the Mood for Love. My partner said it well, ``Wong
Kar-wai is great at building the asymptote of love, desire, and loss.'' There is
something to be said of the constant ``what ifs'' going through every character's
mind. The never ending desire for what cannot be; for someone who is not there.

At face value, the story is straightforward—we have Yuddy, a 1960s Hong Kong
playboy looking for his real mother is creating loose connections with women
that get hopelessly attached to the man that will never reciprocate their
feelings nor marry them and he knows himself perfectly well, which makes Yuddy
that much of an interesting persona to watch and follow. Cannot imagine a better
fit than the wonderful late Leslie Cheung.

However, the beauty of it all is beneath the surface. It's in these scenes where
we are always harrowingly alone and stuck with the characters of the
story. There is seldom nobody else but us and them. No buffer in form of other
actors, music, or something to take the edge off. Just us and them. Them, their
emotions, their feelings, their longing, their loneliness, their anguish, their
confidence, their demons, and us.

In my first watch, Days of Being Wild is still getting there. It's not as dreamy
or stylistically eye-popping as Chunking Express is. It's not as impossibly
subtle and ethereal in quality as In the Mood for Love is. All the ingredients
are there. This is the root, the source of how it started. Leslie Cheung, Maggie
Cheung, and at the very end, Tony Leung in the sequel that never came to
be. This film requires some patience and courage to let WKW's sense of
melancholy envelop you.

It's hard in the modern days though. As it was tough to respond to these more
subtle notes when the film first came out in the 90s, it's even tougher now,
when we become so numb by focusing solely on the content and interpretation of
it all—where we should invest more of our time, energy, and focus on the form of
it—the erotics of art. Looking forward to seeing this many times more.

{{{four}}}
