* I don't like /some/ people 😤

38; 12023 H.E.

I don't like three kinds of people, which boils some of my general views pretty
succinctly: people who cheat, people who have a knack for doing wretched things,
and finally, people who are on purpose annoyingly loud or inconsiderate of
others. Some might even say I have high expectations of people or harshly judge
them. It surprises me even further that staying decent human beings isn't
considered common sense anymore. Still, something to be debated and celebrated
as an outstanding achievement or an impossible task, especially with how popular
(and dangerous) the fetishization of mental health problems and depression has
become.  

Those who cheat rationally cannot be trusted. To ask a naive rhetorical
question, what can you do with people you don't trust? Sure, if you are some
sort of a movie protagonist or read the first page of some game theory textbook
-- you would try to take advantage of that by playing clever "nobody trusts no
one" mind games. However, let's talk about something that matters. (This
argument talks more about cheating, betrayals, and stabs in the back; as you
know, ``white lies make the world go round'').

How can you trust a friend or a romantic partner if you have no faith in them?
Or them in you? What productive or worthwhile connection can be built on such a
flaky foundation? We are talking about serious commitments, such as having kids,
who, I remind you, are whole human beings. They can't be rolled back as a
mistake if parents somewhat later realize they never loved each other or the
trust has been broken sometime before, and instead of ending it there, they
decide to bring new people into the world. There you have every childhood
trauma, longings for closures, divorces appearing en masse.

Those who are okay with lying to you or cheating on you with disregard for your
well-being and emotions, ``Oh it's fiiiineee; You're overreacting; It's not such
a big deal'' don't deserve an easy ``clean slate'' and none of it if they have
done such a betrayal while consciously knowing they're hurting you. Those people
are not worth a dime in my eyes. Your friends, family members, and partners --
doesn't matter. Those affected need to sit down together and find the best path
of parting ways and ending that relationship, such that there is new space for
forming better, more fulfilling bonds.

The above could be considered a subset of doing something wretched, as cheating
might be a prime example of them. No wonder Leo Tolstoy's finest novel is wholly
dedicated to a story of an unfaithful marriage. We need to understand what
``wretched'' means in this context. The definition I use here is more of an old
one, meaning something ``lacking worth, poor in beauty, something close to
misery''. Wretched, mind you, is not too far away from the beauty of this
world. For example, one can drink alcohol responsibly, for taste, so to speak,
in /class/. However, others could start drowning themselves in it to forget their
lives or because they have nothing better to do. Fundamentally, it's the same
act of consuming alcohol, but for different purposes, resulting in wildly
antithetical perceptions.

Anything of beauty, like cooking, sex, smoking, and loving, has an ugly bastard
twin of making bad food (therefore wasting it), animal-like carnality,
chain-smoking, and lusting. All these grustlers and hustlers out there give us
honest workaholics a bad name. However, I also understand the cataclysmic
contrast of life, as Anton Chekhov notes,

#+begin_quote
There are no plots in life; everything is mixed in it - the deep
with the small, the great with the insignificant, the tragic with the
funny.
#+end_quote 

We need the lowly, the tragical, and the ugly to bring out the high comedy and
beauty. However, this does not mean we can sit squarely on our rear ends,
crossing our hands and giving up on doing anything else about it. As anything
has the potential to reach extremes on either side of the spectrum, we should
always strive to be better and strive to find the balance between the two, such
that we are pleased to be ourselves for ourselves and for the ones we love. We
now come to the following kind.

``People who are on purpose annoyingly loud or inconsiderate of others.'' This
one is more of a comedic relief, as, for example, I hate when people chew loudly
when they're in companies of others. And no, they don't have the ``absolute''
freedom to do whatever they want in public or in the presence of others. Freedom
is of utmost importance to our individual selves /and/ society, such that it
requires a delicate balance to actually be called ``freedom.'' Allowing anyone
to do it at any time will result in debauchery and many taking their desires
(some fatal) to their extremities. *This is not freedom.*

Respecting the basic foundation of general etiquette when conversing with others
or enjoying their presence signifies mutual respect. Respect between people for
each other's time, personal spaces, and information we consume from the world on
a day-to-day basis. If you can't help but snore loud and your someone special
finds it annoying, this imperfection is uniquely yours, making you perfect for
them with their flaws, such that you come to a mutual compromise -- that is
good.

Ultimately, we are all simply human beings trying to live our lives the best we
can, trying to make ends meet, care for whom we love, and find love if we allow
ourselves to be seen in return. Treating each other with dignity and pride, as
we wish to be treated in return, goes a long way.
