* Setting up an emacs server 😈

May 8th, 2020

Booting up emacs can be a challenging task for your terminal emulator and the
rock that you tricked into thinking. This is a quick guide with some pointers on
speeding up your emacs interactions 100x. No joke.

** Emacs daemon
Starting the emacs daeman cannot be even simpler, just type this in your
favorite shell

#+BEGIN_SRC sh
% emacs --daemon
#+END_SRC

It should build all your .el config scripts and boot up your own emacs server.

** Emacsclient
Now to access and open your emacs daemon, just type in 

#+BEGIN_SRC sh
% emacsclient -nw
#+END_SRC

/I really prefer terminal client/ and you're done! Notice that the load was almost
instantaneous. Instead of loading your whole emacs config, it just redraws the
screen.

** Killing daemon
Who doesn't want to slaughter a daemon in cold blood? That's a rhetorical
question. =emaclient= can execute a kill command for the daemon

#+BEGIN_SRC sh
% emacsclient -e "(kill-emacs)"
#+END_SRC

** Shell aliases
=emacsclient= can get old real quick. I like adding super simple aliases for
faster opening

- *bash* - put =alias em = "emacsclient -nw"= in =~/.bashrc=
- *fish* - put =alias em = "emacsclient -nw"= in =~/.config/fish/config.fish=

** Systemd daemon
You can also set emacs daemon to start automatically by adding systemctl
symlinks. More information on [[https://www.emacswiki.org/emacs/EmacsAsDaemon][emacswiki]].
