* Man with a Movie Camera 🎥

87; 12022 H.E.

Lights are dimming down, small chair creaks are getting ever louder in a quieter
classroom, the small light illuminating through an ajar door is sent back to the
void when the small wooden doorstop is kicked away. Intensifying orchestral
music is starting to play with the intro credits of /Man With A Movie Camera/
by Dziga Vertov. After finishing the film, everyone knew they felt something and
had ideas regarding it. One thing is for sure, it hasn't left anyone
indifferent.

#+begin_center
The film /Man with a Movie Camera/ represents \
AN EXPERIMENTATION IN THE CINEMATIC COMMUNICATION \
WITHOUT THE USE OF INTERTITLES \
WITHOUT THE HELP OF A SCENARIO \
WITHOUT THE HELP OF THEATRE \
#+end_center

/Man With A Movie Camera/ is almost a silent movie with incredibly fast-paced
editing and the unique decision regarding its actors and plot, there is
none. Let us traverse through different dimensions of what Dziga Vertov,
originally David Abelevich Kaufman wanted us to experience through his work,
and decide whether the experimental film stands the test of time with its
ideas.

It is almost a silent film because if there is no audible dialogue, we are
still greeted by an accompanying soundtrack that shifts and changes depending on
current scenes. Interestingly enough, silent film directors usually would write
the score, which will be played with every screening. However, Vertov only gave
directions for the soundtrack, resulting in the movie accumulating over
twenty different accompanying scores, each contributing slightly differently.

I watched the film with the musical accompaniment performed by The Alloy
Orchestra did a terrific job of keeping the tension up throughout the
whole screening. The instruments, pitch, and speed would all change depending on
the environment that camera is in or what the camera is currently looking
at. Parts with us following a fire truck hauling across town are aided by sirens
playing in the background with beating drums, which seem to never get tired.

The second important feature of the film to notice is the apparent lack of a
traditional narrative script, possibly a complete absence of it. Rarely this is
done, as what we end up with is a movie with no central characters that develop
or follow some overarching story that we are supposed to follow and care
about. In a similar logical way, one would even dare to claim that /Man With A/
/Movie Camera/ is devoid of any meaning, primarily because it doesn't have a plot
for us to consciously follow. I would disagree.

What we have in front of us is a film with no actors, but that fact alone
doesn't hinder or cripple the effect Dziga Vertov made on us. The absence of a
traditional cast allows the movie to follow everyday people in their routine
lives. From early morning until late night Soviet citizens are shown at work and
play, actively being involved with the bustling urban lifestyle. It is
different from a classical narrative structure, as we end up with more of a
symphony-like development, where each scene is a whole story of its own.

This closes in tightly with what I believe to be one of the most important and
defining features of /Man With A Movie Camera/ and that is its use of a hidden
camera, which allows us to witness the actuality of a modern life, where modern
is defined by the standard of the 1920s. Silent movies of a similar era produced by
the likes of Sergei Eisenstein and Lev Kuleshov are meticulously
choreographed, where both attempt to force strong emotions with a
propaganda-like purpose of affecting the masses in a very specific way.

I personally dislike propaganda or works of art that aims at making me or one of
the audience members think and feel in a given way, which would be beneficial
to them. Dziga Vertov takes a very interesting approach, as there is no grande
moralizing or lecturing tone in his film. It is simply a collection of
real-world footage with real regular people in it. This merely serves as a
manifestation of his own views on cinema, which is fully cinematic. Vertov
accomplishes at making it real, a literal unplayed film.

This cinematic nature of it with an incredible editing and montage job done by
Elizaveta Svilova allows us to formulate our own understanding of the film. This
ambiguity in its meaning, for many a complete lack thereof, gives us the freedom
and liberty in creating our meaning and attributing it to the movie. With the
range of activities and work shown through the work's fast cutting, everyone can
find a role that they could relate to in one way or another. I even had a
physical sensation when watching people at the beach washing medical mud off
their skins. When I was a child, my family went on a trip, which I hold very
dear to me, where we tried the "mud cleaning" technique. 

A good question that was raised after the screening was - "Is this propaganda?
Do you feel you would like to pack your bags and go live in the Soviet
Union?". As I mentioned, I don't see it as propaganda, yet I would claim that
the work is pro-Soviet. There is an important difference between those
two. Propaganda aims at affecting your mind, in many ways forcibly implanting
strong emotions towards a subject. Vertov strove to showcase a futuristic city
that would serve as a commentary on the ideals of a Soviet citizen while
granting us the freedom to decide our emotions regarding it. 

Considering that it still would be possible, did I feel like packing my
belongings and leaving for good? I would not say so for two reasons. I adore the
work ethic and optimism that was shown through the film, where a lady would be
doing a tedious manual task of wrapping up tobacco packages, while still
talking and presumably laughing at some jokes throughout her work. However, I do
not feel I personally share many of the Soviet ideals shown in the movie, but
they do have my respect. The second reason is that we are mostly presented with the
active urban life, but an overwhelming majority of the Soviet population used to
live in more rural areas, where I would imagine the lifestyle was very
different.

After an epilepsy-inducing final scene, the end credits simply read *KINEC*
(*END*). I started applauding because I felt this is what /Man With A Movie Camera/
deserves. There was no doubt in my mind that Vertov showed the infinite
possibilities of what cinema can be. You just have to let the camera do the
talking.

---

This review for [[https://en.wikipedia.org/wiki/Man_with_a_Movie_Camera][/Man with a Movie Camera/]] was written for graduate film course
on Soviet Cinema. Original can be found [[./slav723_paper1.pdf][here]].

---
