#+setupfile: ../00_film_skipthis.org
#+date: 111; 12025 H.E. 2130
* Paris, Texas

I could not get the pictures, the composition, the cinematography out of my
head. The first third of the film, the story of finding the brother long-lost in
the middle of nowhere called deep magnetic American West. Simply, stunning. I
couldn't stop taking mental notes with each frame unfolding, something so
magical about it and the entire mystery that was driving the prologue of the
story.

The second third lagged in terms of pace and the mystique that was built up
before. Of course, it's as life goes, captured as is, but I found myself at
difficulty of staying awake throughout it or caring as much as I did when the
images first started rolling. All that was stuck with me after the movie
completed its third act were the gorgeous shots in the "entertainment house"—I
don't know what you would call it—but the story itself was not as voluminous or
provoking as I initially thought it would be.

It may have not been the right time or place for me in terms of the content of
the film, but the form of it—that's something I kept thinking about ever since I
witnessed the absolute commitment to urban and country landscape
composition. The experience and atmosphere have drawn me on a technical level,
but haven't pierced me on the emotional plane. Let me come back to it some time
later.

{{{three}}}
