* Build a cheap self-driving car 🚗

In the Fall of 2020 I was enrolled in EECS 388: Embedded Systems. It's an
introduction course into lower level things, such as RISC-V, Computer
Architecture, CPU scheduling, and other fun stuff. The course itself was
accompanied by a lab section, where we wrote some C+Assembly to control UART
signals, some lights, etc.
   
The final project for the class was us building a self-driving car that uses
a pre-trained neural network for recognizing tracks on the ground that it
reads from its camera. The car itself uses Raspberry Pi as a main board
computer, HiFive micro-controller for the wheels connected via UART to the
Pi.

We built up extensions to the final project, I worked with KayLee Mitchell on
building a car that can be controlled from any browser-capable device via a
webpage and some quick interfaces hooked up onto our little car. It was a fun
farewell to this course. The link below has a webpage written by me by the
request of our Instructor to document some selected final projects.

-> [[https://sandyuraz.com/eecs388_projects/][Go to the selected finals webpage]]

(above is the backup, original should be [[https://eecs388.ku.edu/388Fa2020_selected_final][available here]])   
