#+date: 18; 12023 H.E.
* Houshou Marine 🏴‍☠️

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/sHZ][Up close]]
- [[https://photos.sandyuraz.com/ZXG][Left view]]
- [[https://photos.sandyuraz.com/mce][Top right]]
#+end_gallery

#+begin_gallery
- [[https://photos.sandyuraz.com/hOR][Eva from left]] :flex 45
- [[https://photos.sandyuraz.com/Nov][Eva from right]] :flex 45
#+end_gallery

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/EhO][Full height]]
- [[https://photos.sandyuraz.com/VEx][my bt]]
- [[https://photos.sandyuraz.com/hRO][Back]]
#+end_gallery

I never got into vtubers -- never became my vibe or something I crave for. Not
to say that I am not addicted to watching streams and keeping myself from
becoming a parasocial andy. However, I have some emotional feelings toward
Houshou Marine. It might have been all the [[https://twitter.com/pomesaurus][Twitter]] [[https://twitter.com/CowBow_kun/media][artists]] that have treasure
troves worth of Senchou's paintings, [[https://youtu.be/LBBtSimQD20][quick witted jokes]], [[https://youtu.be/_VIeV_LZXHM][banger]] [[https://youtu.be/e7VK3pne8N4][songs]], or the
great model/outfit she has.

Oooh! This Hoshou Marine figure might be the best one I own from [[https://www.goodsmileus.com/product/pop-up-parade-houshou-marine-7622][POP UP
PARADE]]. The clothing, sculpting, and how free she motion feels on her -- all
top notch. Often, figures suffer from unrealistic body proportions (which are
still lovely to look at). However, having one resembling a regular human's body
(especially with its sweet imperfections) reveals a person's vulnerability or
character, which makes it so endearing.

[[https://open.spotify.com/track/7gl0IJpIHu1TtNT4hNiv9H?si=0bb28c0d9f024c97][Ahoy!!]]
