#+date: 355; 12022 H.E.
* Rem Summer RELAX 🍦

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/pJS][Frontal "She got that laid-back feel that I strive to have one day"]]
- [[https://photos.sandyuraz.com/bwi][Rem one "I never realized how similar Rem and Rei look here. EVEN THEIR
  NAMES!!"]]
#+end_gallery

#+begin_gallery 
- [[https://photos.sandyuraz.com/kzL][The gang "Rem and the gang (they are yet to come!!)"]] :flex 90
#+end_gallery

#+begin_gallery :num 2
- [[https://photos.sandyuraz.com/UZu][wife]] :flex 45
#+end_gallery

I don't remember, but this figure must have been my first. It's so
clear to me.

On a bright Saturday, I went downtown to one of the gaming stores. Having just
gone through the magic of Re:Zero, I found myself in a state of trance.

I never thought of getting a figure until I saw her. I wasn’t sure whether I
Should I get it or not, I have definitely felt something within me.

I didn’t buy it and went back home. A day or two later, I found myself thinking
about it too much, which showed that this chance should not be toyed with. 

I sprinted downtown after classes, and there she was. *The last one.* How could I have
known the path I was about to take myself on.
