* Managing ⏱ without grinding

81; 12022 H.E.

A tutee of mine asked me today, ``Sandy, how do you manage time?''. ``Just like
in general?'' I asked in return to clarify. I think it's about assignments and
juggling school time with life. ``Yeah, like homework and stuff. I had to do my
chemistry lab, but this was my first time submitting it late.'' Ah, I see.  

I am not a hardworking man. All the trends with following a billionaire's
routine, such as waking up at four in the morning, intensive treadmill or
running for an hour, cold shower, black coffee, positive affirmations, writing
down your goals for the day, etc. I loathe it. This is no life. With a schedule
like that, you are turning yourself into a machine. How do you squeeze a soul in
there? No, no. Life is to be lived.  

#+drop_cap
Seize the moment! Do you want to watch a movie? Go watch a movie. Want to hang
out with your friends? Go hang out with your friends. Want to enjoy an anime? Go
and enjoy an anime. Want to take a nap or sleep? Hit the bed and enter the world
of dreams. ``But Sandy, we have to do stuff, like school and assignments!'' Of
course, we have to do them and we will!  

I observe that the best way of doing so is being able to hype yourself up. You
need to do a chemistry lab due Thursday night, assuming it takes 3 to 4 hours to
complete, block off your Thursday evening, concentrate on it and do it. What if
you finished earlier? Maybe I can get a head start on that thing I have to
do... *nope*.  

Our brains can't switch from one intensive task to another in an instant. It
needs time to adjust and prepare itself for whatever activity is coming up. Some
would say, /getting into the zone/. Planning ahead of time allows you to set up
the mood required for optimal task performance and enjoy what you are doing in
the moment.  

#+drop_cap
Us trying to put out all the fires all the time. Filling our availability with
upcoming tasks (when it may not be their turn yet) hollows us out and leaves
nothing but frustration of not getting a task done because of a tired brain and,
therefore, poor execution. If all cylinders aren't firing, *you will grind* and
that is no fun. One thing at a time. Quality over quantity. 

But what about that gap that we have if we finish something earlier? Well, my
dear friend, /hallelujah/. This is your free time now, blocked off for something
that has been done. Go and do something for yourself, rest up, relax. *Do not*
worry about future tasks and things to do. Their time will come. Right now, just
live.
