{{{film}}}
#+date: 300; 12024 H.E. 1138
* Ikiru

It doesn't really get more perfect and contained than this. A Dostoevskian-style
narrative of a life so busy, dull, and boring that it is functionally no
different from being dead. A bureaucrat surrounded by fellow bureaucrats,
grinded out by their daily minutia, and finally hollowed out into a living
carcass—devoid of any purpose or meaning behind it all. Not that it is the most
important facet of life, but there is nothing else there either.

Harrowingly raw, it reminded me of Dostoevsky's short story, /A Bad Business/,
where even if the weight of Mr. Watanabe's life coming to its end paved the way
for his one last project, one last defiance of the life he has lived so
far—people around can be fascinated, revering his actions, making oaths left and
right on how they themselves will lead a life in service to the people, leaving
their old ways behind; where nevertheless, everything will come back to its
usual routine, to its usual mundane existence, as prescribed.

The idea of not recalling anything of joy or of value for the past thirty years
of one's life terrifies me. Nothing to hold on to. Not even kids, their
achievements, their lives bring joy—worst of all—when those feelings are
reciprocated by the children as well. This might be Akira Kurosawa's finest
piece of work. I am a fan of his famous earlier and later works, but this one,
it strikes a certain kind of note that I'm all in for. The intersection of a
Japanese setting, Western inspiration, Classic Russian Literature delivery, and
a Universal message.

Ikiru was relevant when it was made. It was relevant a decade later. It is
relevant today. It will be relevant for generations to come. Everyone has to
live a life. The question is, ``how do you live?''

{{{five}}}
