#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: L'Hôpital's rule
#+date: 5; 12021 H.E.
#+author: Sandy Urazayev
#+email: ctu@ku.edu
#+language: en
* Quick recap
  
  *Limit of a function* is a fundamental concept in calculus and analysis
  concerning the behavior of that function near a particular input.

  Examples:
  - $\lim_{x \to 2} x = 2$
  - $\lim_{x \to 5} (x-1) = 4$
  - $\lim_{x \to 0} x^2 = 0$
  - $\lim_{x \to 0} \sin(x) = 0$

* Fact
  Limit of a fraction of two functions equals to the fraction of limits of those
  two functions.

  \begin{equation*}
    \lim_{x \to a} \frac{f(x)}{g(x)} = \frac{\lim_{x \to a}f(x)}{\lim_{x \to a}g(x)}
  \end{equation*}

  Examples:
  - $\lim_{x \to 3} \frac{x-1}{x+2} = \frac{\lim_{x \to 3}(x-1)}{\lim_{x \to
    3}(x+2)} = \frac{2}{5}$

* Motivation
  What if our limit of functions is undefined? In essence, what if our final
  fraction is $\frac{0}{0}$ or $\frac{\infty}{\infty}$?

  Examples:
  - $\lim_{x \to 0} \frac{\sin(x)}{x} = \frac{\lim_{x \to 0} \sin(x)}{\lim_{x \to 0} x} = \frac{0}{0}$
  - $\lim_{x \to \infty} \frac{x}{e^x} = \frac{\lim_{x \to \infty} x}{\lim_{x
    \to \infty} e^x} = \frac{\infty}{\infty}$

* Definition
  Let $f$ and $g$ be both differentiable (derivatives $f'$ and $g'$ exist and
  are defined), if $\lim_{x \to a} f(x) = \lim_{x \to a} g(x) = 0$ or $\pm \infty$
  for all $x$ in the domain with $x \neq a$, then

  \begin{equation*}
    \lim_{x \to a} \frac{f(x)}{g(x)} = \lim_{x \to a} \frac{f'(x)}{g'(x)}
  \end{equation*}
  
* Worked examples
  Recall some examples from Motivation

  \begin{align*}
          \lim_{x \to 0} \frac{\sin(x)}{x}
           & = \lim_{x \to 0} \frac{(\sin(x))'}{(x)'} \\
           & = \lim_{x \to 0} \frac{\cos(x)}{1}       \\
           & = \lim_{x \to 0} \cos(x) = 1
  \end{align*}

  This means that as $x$ gets infinitely small, $\sin(x)$ and $x$ tend to have
  the same value! 

* Extra example
  Our second example from motivation

  \begin{align*}
          \lim_{x \to \infty} \frac{x}{e^x}
           & = \lim_{x \to \infty} \frac{(x)'}{(e^x)'} \\
           & = \lim_{x \to \infty} \frac{1}{e^x}       \\
           & = \frac{1}{\lim_{x \to \infty} e^x} = 0
  \end{align*}

  So as $x$ gets infinitely large, $e^x$ is getting larger much quicker than $x$
  does! 
