* We were once friends. What happened to us? Part II

‘Sergey, dear, how was your flight in? How is your family?’ her sweet motherly
tone only softened over the years since I've last seen them.

‘The flight in was good, no turbulence, and clear skies. The family is doing good. I
must say they tell me how they miss living here. Especially the food!’ I tried
to be a little cheerful, but not too much. Did I overdo it?

‘Ah, I'm glad your family is safe. Gregory and I are very happy to see you. He
would often talk about what you did together in school and how close you were,’
I could still hear the grief in her voice when she mentions him, but it's not the
the grief you would sense from a mother who just lost her son.

It has some kind of acceptance, I would even dare to say closure. It's already
been a month. Is that really enough time to come at peace with it?

‘Ah, those were the times... We were still young and all we cared about is doing
that English homework. We had to read so much, I remember how much he loved the
books our teacher chose for us that semester,’ and he really did.

He was the best student in our small class. There were only five-- no, four of
us. One guy got kicked out of school for flipping off our principal. I would
always take the easy way out, read the first five pages and the last ones. The
rest? ahh, I'll fill it in from what I've read and ask him to give me a run down.

‘He was always so excited after coming back from school to tell us how his day
went... Ah! Where are my manners? Sergey, can I bring you some tea?,’ she
rushingly stood up as she was getting ready to start a marathon all the way to
the kitchen couple of feet away.

‘If that's okay, could I get some black tea?’ It would be rude of me to decline
it, especially since she is en-route to start the kettle.

‘Of course, Gregory! Talk to our guest a little bit, I'll be right back. I want
to get those cookies Marta brought the other day, you know, the fig and
strawberry ones,’ she said hurriedly.

‘Those do sound delicious. Thank you, Mrs. Keller!’

‘Oh, come on, Sergey, just call me Anna,’ I couldn't recognize whether she said
it seriously or jokingly. She looked a little distressed. Is this all because of
me mentioning him? Is it really okay for me to be here? I don't want to open
any wounds that are already trying to heal. I don't know, it's been such a long
ti--

‘Sergey,’ I heard a man's voice to my left. So full of sorrow and pain, it was
unmistakable. If she is trying to stay hopeful and struggling, I can't imagine
what her husband must be going through. How do I talk to him? Do I talk to him
like a man to man? Probably not, too much of an age gap. Do I talk to him like
his late son's best friend? But I was not that friend.

‘Sergey, thank you. As a father, who is still grieving his first son, I want to
thank you for being his friend. He always looked up to you. He was never meant
to be a soldier, thanks to your support, he was able to go through it. Even if
my boy never wanted to be there, he wanted to meet with his old friends. Forgive
him if he became more reserved, that's just what the army does to a young
boy. Curse this war. Sergey, please go see him. He would like that.’

‘I will, Mr. Keller,’ what else could I say? Did I say enough? Was my response
proper? What do you say in a situation like this?

‘Sugar or no sugar, Sergey?’ a loud voice was coming from the kitchen
accompanied by a familiar whistling kettle.

‘No sugar, please! Thank you!’ I hope she heard me.

Mr. Keller shifted the topic of our conversation. He always seemed more of a
stoic man from what I've heard about him, ‘Is work good?’

‘Work is good, there is this big project I've been working on for a client for
the past couple of months. Looks like we are getting close to finishing it
sometime soon.’

‘That's good. Work is good. Your parents must be proud of you. Don't forget
about family! That's important too,’ he said caringly as if he was talking to
his son like a father, who really wants to see his grandkids one day. 

‘Of course, thank you. I hope your work is going well,’ I said trying to sound
like an adult. If I remember correctly, he worked as a lawyer in some
international organization... amnesty?

‘Thank you for asking. I took a sabbatical, so I could spend more time with Anna
and her side of the family--’ he was saying as he got interrupted by an
approaching voice

‘I got the tea and sweet for us!’

‘It looks amazing, Mrs. Kell-- Anna!’

‘Now you get the hang of it!’

The rest of my visit to their house was pretty brief, we chatted, had some tea,
enjoyed delicious snacks and sweets their Marta brought over. It feels as if the
atmosphere in the house changed a little. They asked me about my travels, some
anecdotes and jokes were shared over the table. It feels they just wanted to see
me, an old friend of their beloved son.

I thanked both of them as I was leaving. It's getting pretty late. Better start
heading home.  

That was better than I expected. What did I actually expect? Wailing while we
all hold each other's hands? Probably not, I expected it to be something as
exchanging grievances and collecting our memories about him. 

But no, I saw how grief-stricken they were, but they just simply didn't want to
show it in front of me. Out of solidarity? Out of pride? No, they just
understand that life must go on. 

Did they know that we were out of touch for such a long time? I would assume so,
but is it true that he still talked about our time such a long time ago? Did he
not have any other friends? Should I have talked to him more?

What am I even thinking?! Don't speak ill of the dead, Sergey.

The answers to those questions don't matter anymore. It's just too late to
ponder about this. The living must keep on living, and the dead should be given
peace. I will never be able to find answers to those questions or what he
actually thought of us throughout all the years.

I know this and always will. He was a great man. He was a great friend. I missed
him ever since. I still do. The time is irreversible. I hope I was a good friend
to you as much as you were to me. Goodbye, Dmitri. Thank you.

---

This story was written as [[./report8.pdf][Individual Report VIII]] for my Computer Science thesis.

---
