#+setupfile: ../00_film_skipthis.org
#+date: 209; 12025 H.E.
* Sexy Beast
Scrolling through the home page of my Criterion Channel, /Sexy Beast/ was not my
top pick---far from it, really. I did everything in my power to avoid picking
this movie for our evening watch. Not that there was much that I could do, but
offering two other films and spinning the three of them in an online wheel of
fortune and /Sexy Beast/ beating the two, I thought to myself, ``Gods themselves
must be speaking,'' and I should already accept for what the world wants.

Switching between the two modes of enjoying it and barely staying awake---/Sexy
Beast/ was a good mix of posh brit humor with a few jabbers here and there; some
pretty cool shots and ideas thrown around in the runtime; however, some of the
moments were so egregiously off-putting---I'm thinking of the last underground
scene with the scary dude---it soured the whole experience that if it weren't
for me writing this short blurb two or three weeks after the fact---I would have
given it a single star for its poor taste.

It fits though that this is the 69th entry in the drama section. *nice.*

{{{two}}}
