#+options: preview-generate:t
#+date: 14; 12024 H.E.
* Against Interpretation 🤔

I have finally come around to reading Susan Sontag's ``Against Interpretation'';
and ``I was never so bethumped with words since I first called my brother’s
father dad.'' (William Shakespeare, /Kind John/) Beautiful essay. I'm yet on the
track to read the whole collection of essays included in this book, but I simply
wanted to share that everything Susan Sontag described---also some other essays
I've read---it resonated so strongly with me.

Just the way she puts it, ``In most modern instances, interpretation amounts to
the philistine refusal to leave the work of art alone.'' It should be reminded
that this essay went on print in 1964. Exactly sixty years after of what she saw
of our ``culture based on excess, on overproduction; the result is a steady loss
of sharpness in our sensory experiences'' rings more true and urgent than ever
before.

In the past, you needed to have an editor, or at the very least, some individual
with the rights to a printing press---so they can spread your thoughts around
the general populace. Today, all you need is a web outlet; be it a blog (like
this one), a YouTube channel, a TikTok profile (ew), or anything really---you
can now go and start calling yourself a ``critic.''

With the rise of all the essay YT channels, all those ``critics'' have meddled
with, desecrated, and devalued the works of art they are reviewing by constantly
bombarding it with unending waves of interpretation. ``This X part means...'' or
``actually, thi is a beautiful symbolism meaning...''---or as the joke goes,
``Why is the door blue?''

What Susan Sontag (S.S.) rightfully describes as a separation of ``form'' and
``content'' of any work of art, we have become primarily preoccupied with the
``content'' part of it; finding meaning, ripping out parts to translate and
transpose it onto some lesser terms that would make us tame those works of
art that make people uncomfortable, when presented in their original form.

Some thoughts of the surrounding media becoming more reactionary, sensually
stifling, and intellectually flattering---so many films, books, shows, and all
sorts of media get attacked by hordes of interpreter armies, who are, by S.S., 
``indicates dissatisfaction (conscious or unconscious) with the work, a wish to
replace it by something else.''

The position I have here is not that all interpretation is superfluous and we
should stop trying to interpret works in any way, period; but we should stop
constantly digging behind the text, pushing forward some of our own biases,
ideals, and ``hidden meanings'' we found as some sort of a divine revelation,
which we in our grace are bestowing upon everyone else, who did not or could not
see what's underneath. (think of how crazy people go for the Evangelion
symbolism)

Every piece of creativity that someone makes doesn't have to have some deeper
intellectual meaning, ``finding'' which makes some feel much smarter than they
really are (sounds patronizing, I know). Art is a medicine, a remedy for the
senses, which have been dulled with the constant overstimulation of what is the
reality of modern circumstances. I'm happy with more abstract art and similar
movements, which treat art as a form of self-expression. In many ways, an active
opposition to being interpreted by devoiding themselves of content, thus only
leaving their form.

There is nothing revolutionary in interpreting high works of art; nor is there
anything new in layering meaning on several levels, so one experiences a work of
art on those levels. We are better---I hope so, at the very least---to focus
more now on the ``form'' of art---what it actually is, rather what we want it to
be.

By no means am I a clean either. Nor do I intend to put a hypocritical assertion
here of ``do what I say but not what I do.'' Myself, I'm trying to be pretty
careful, sometimes, to even paralyzing effect, when formulating my thoughts on
something. To avoid going on tangents spawned by the work, which do not mean
that is the work itself. It is paramount to stay focused on what is in front of
us.

This doesn't impoverish our ``analysis'' or the enjoyment of the work
itself. Somehow, maybe from Plato's mimetic theory, we never really had the
right tools to describe art in a more sensual and soul-like way. Most of our
words and analysis has always been driven by intellect and Freudian-level
vocabulary.


I don't really know what the right solution is, if there is one at all. The
innocence can definitely never be recovered, but I like to believe it only makes
us more fine-tuned towards the goal of showing something for what it is, rather
than what it means. Paying a closer attention to the ``form'' of something,
rather than putting all of our eggs in the ``content'' basket. Brilliantly put
by Susan Sontag again,

#+begin_quote
In place of a hermeneutics we need an erotics of art. 
#+end_quote
