{{{film}}}
#+date: 29; 12026 H.E. 2147
* Escape from New York
I wouldn't have expected to see the modern-day /Skid Row/ and /Tenderloin/ presented
as this absolute Hell on Earth in a fictional Manhattan, which is really just
the average experience of walking down in any large-ish city in the US. The only
difference is that I am not hot and jacked and masculine as Kurt Russell, but
also badass in a way that is relatable?

Whenever we go and see modern ``action'' movies, think of anything with Chris
Evans, or /Avengers/ or Hugh Jackman, or any jacked-to-the-tits actors, it's hard
to take them seriously, because they are just soooo beefed up on diets, maybe
some pills, exercise routines for the movie, and dehydrated right before the
shoot so the muscles really get to shine even under all the makeup they get.

Kurt Russell though, sorry, Snake Plissken, is one bad ass motherfucker. Just a
dude, sure, in the military, but straight out of a prison, so not in the
greatest shape possible, but that's okay, since he doesn't need all of that to
/be/ Snake Plissken that everybody had heard about. He's going to save the
president, whatever message that carries later on, but he's going to do it.

This film is gritty; feels like you are in close quarters combat because
everything is so in your face, the streets, the noises, and blinded, with the
camera almost exclusively focusing on immediate surrounding---adding the whole
air of being stuck in this environment that does not welcome you, does not want
you, but you very well might end up here in the world of /Escape from New York/.

{{{three}}}
