* We were once friends. What happened to us?

Come to think of it, it's been a while since we talked. All the way from high
school. Am I to blame for it or just the circumstances of the time? My family
always lived in the area temporarily, we knew that I will have to go wherever my
family does. It's not like we haven't tried to keep in touch and call each other
whenever I was in the area, but... The feeling was different. We were best
friends in school, talking for hours and no end every day. I left for university
and he got drafted into the army.

I visited in, we called each other. However, with each of my visits and our
long-anticipated calls, when he gets access to a cellular phone or a
little time away from the training camp, we would even go and meet together
somewhere in the city! Walk around, talk about the past, how cool everything was
and about the stuff we used to do together. But I notice now, we never talked
about the present or the future.

His demeanor changed, not in a good way and in no way in a bad one. He became
more reserved. He would always maintain a composure, as in he would be called by
his drill sergeant any moment. He would /even tell me/ not to talk too loud in a cafe
we were sitting at. It was him, my best friend, my only friend I had for years,
but at the same time, a man that I don't know, whose conversations I can't
relate to as if we are from different planets now.

`Oh, Sergey! Finally, you came in. I'm sorry I kept you waiting outside like
this', a medium-loud but cheerful voice called for me from the house.

`Good afternoon, Mrs. Keller! Please, there is nothing to be sorry for. I came
in just recently. I want to express my sincere condolences to you and your
family. I couldn't believe it. I'm sorry I couldn't come any sooner, I had to...',
my thoughts were running way past my articulative skills.

`Sergey, he would have been glad that you visited us. Please, come in, she said
in a caring, motherly tone that briefly hase overcomes with deep sorrow. 

While I was studying, I got the news from a mutual friend of ours. In the worst
places of all. On LinkedIn. I rarely ever open that toxic professionalism
website. I got a message from an old classmate that we haven't spoken ever since
our high school graduation ceremony. It started with condolences, which alarmed
and puzzled me at the moment.

It continued to read that she expresses her regrets that we haven't spoken in
a while. That he was what is called KIA or Killed In Action during the war. I
initially didn't know whom she was talking about. She wrote his name there, but I
feel my mind didn't want to see his name so close to that military
statement. She said he died a hero, living a soldier's life.

He never wanted to be a soldier. He was the smartest guy in our class. The only
one I felt like someone could understand me, a funny, quirky, and odd
foreigner. We were applying to the same universities, he got into some, but
couldn't pursue further studies and college because of his military duty to the
country. He never even worked out or went to the gym.

We would laugh and play, talk about the latest cool things, like Flutter, which made
GUIs super easy, that you could even use it with different languages with their
bindings. I was learning Go at the time, which made me obsessed with all the
libraries it had to offer. I told him I will be a manager, manage people, and make 
lots of money, while simply delegating everything to my team.

He'd tell me that there is more to leadership than just delegating. It is about
knowing your team's strengths and weaknesses. Your own as well. It is having a
constant channel of communication between everyone and that the manager is
largely responsible for the spirit of the group. He was the one, who made me
want to have more friends. To look a week ahead and plan new exciting things to
do, like a manager would work with his team on keeping up with deadlines and
making sure everyone is comfortable in their spot. 

He never wanted to be drafted. He never wanted to be a soldier. He never wanted to
die as a hero for his country. He was just a skinny, smart, and talented guy,
who I always felt was meant for something bigger. Something that can be shared
and treasured between both of us. What happened to him? What happened to me?
What happened to us?

/To be continued.../

---

This story was written as [[./report7.pdf][Individual Report VII]] for my Computer Science thesis.

---
