* Secure and cheap smart homes ðŸ 
In the Spring of 2021, I was taking [[http://www.ittc.ku.edu/~fli/][Professor Li]]'s EECS 700: IoT Security,
which was a fantastic course over some basic and more advanced aspects of
Internet of Things and their security considerations. We had a semester-long
final project for the class. My beautiful partner, Anissa Khan and I built
and documented a securite model of a smart home. Below is the abstract from
our paper and related links.

*Abstract --* The Internet of Things (IoT) has become more prevalent in our
everyday lives through the use of smart home devices. As such, the security
of smart home systems has become of paramount importance. In this study, we
design and implement a simplified smart home model that is meant to serve as
a testbed for a wide range of smart home systems. Once implemented we perform
a security analysis of the whole system and put security controls in
place. In doing so, we demonstrate ways in which the general IoT smart home
system can be secured.

-> [[https://github.com/thecsw/sandissa-dev/blob/master/sandissa.pdf][Go to the project's final paper]]
