#+date: 157; 12020 H.E.
* My 30-day song challenge 🎵🤘

** The insta story

With my new [[https://www.instagram.com/sandy_uraz/][insta]], I decided to do my first song challenge where I have to put a
new song every day, which matches that day's description. Here we go!

Also, here is the [[https://www.instagram.com/stories/highlights/17848385216106957/][original story reel]] (instagrame is *gone*).

NOTE: It can take a hot second to load all the embeds! Some songs are not
available (???), though the track IDs are all correctly entered. I will also add
the name of the song in the text so you can see what it was

*** Day 1: A song you like with a color in the title
/Blue Moon/ by Frank Sinatra

{{{spotify_embed(blue-moon-1999-remastered.toml)}}}

*** Day 2: A song you like with a number in the title
/One More Time/ by Daft Punk (💌)

{{{spotify_embed(one-more-time.toml)}}}

*** Day 3: A song that reminds you of summertime
/Bullets/ by Archive

{{{spotify_embed(bullets.toml)}}}

*** Day 4: A song that reminds you of someone you'd rather forget
/Thrift Shop/ by Macklemore & Ryan Lewis

{{{spotify_embed(thrift-shop-feat-wanz.toml)}}}

*** Day 5: A song that needs to be played loud
/Sway/ by Michael Bublé

{{{spotify_embed(sway.toml)}}}

*** Day 6: A song that makes you want to dance
/Rebel Yell/ by Billy Idol

{{{spotify_embed(rebel-yell.toml)}}}

*** Day 7: A song to drive to
/Nightcall/ by Kavinsky

{{{spotify_embed(nightcall.toml)}}}

*** Day 8: A song about drugs or alcohol
/Sex & Candy/ by Marcy Playground

{{{spotify_embed(sex-candy.toml)}}}

*** Day 9: A song that makes you happy
/Feel/ by Robbie Williams

{{{spotify_embed(feel.toml)}}}

*** Day 10: A song that makes you sad
/Por una Cabeza/ by Horacio Rivera

{{{spotify_embed(por-una-cabeza.toml)}}}

*** Day 11: A song you never get tired of
/Living in the Shadows/ by Matthew Perryman Jones

{{{spotify_embed(living-in-the-shadows.toml)}}}

*** Day 12: A song from your preteen years
/Stayin' Alive/ by Bee Gees

{{{spotify_embed(stayin-alive.toml)}}}

*** Day 13: A song you like from the 70s
/Mr. Blue Sky/ by Electric Light Orchestra

{{{spotify_embed(mr-blue-sky.toml)}}}

*** Day 14: A song you'd love to be played at your wedding
/Unchained Melody/ by The Righteous Brothers

{{{spotify_embed(unchained-melody.toml)}}}

*** Day 15: A song you like that's a cover by another artist
/Amish Paradise/ by "Weird Al" Yankovic

{{{spotify_embed(amish-paradise-parody-of-gangsta-s-paradise-by-coolio.toml)}}}

*** Day 16: A song that's a classic favorite
/Girl, You'll Be a Woman Soon/ by Urge Overkill (real shame this one is
unavailable, please listen to it if you can find a chance)

{{{spotify_embed(girl-you-ll-be-a-woman-soon.toml)}}}

*** Day 17: A song you'd sing a duet with someone on karaoke
/Let's Ride Into the Sunset Together/ written by Tony Vice and Jerry
Burnham, and performed by the Lost Weekend Western Swing Band, with vocals
by Don Burnham and Patty Kistner.

{{{spotify_embed(let-s-ride-into-the-sunset-together.toml)}}}

*** Day 18: A song from the year you were born
/Gimme More/ by Britney Spears (I really thought this was from 2000, it's
actually from 2007)

{{{spotify_embed(gimme-more.toml)}}}

*** Day 19: A song that makes you think about life
/Within/ by Daft Punk

{{{spotify_embed(within.toml)}}}

*** Day 20: A song that has many meanings to you
/Digital Love/ by Daft Punk

{{{spotify_embed(digital-love-radio-edit.toml)}}}

*** Day 21: A song you like a person's name in the title
/With Every Heartbeat/

{{{spotify_embed(with-every-heartbeat-tong-and-spoon-wonderland-remix.toml)}}}

*** Day 22: A song that moves you forward
/Perfect Day/ by Lou Reed

{{{spotify_embed(perfect-day.toml)}}}

*** Day 23: A song you think everbody should listen to
/Supreme/ by Robbie Williams

{{{spotify_embed(supreme.toml)}}}

*** Day 24: A song by a band you wish were still together
/Money, Money, Money/ by ABBA

{{{spotify_embed(money-money-money.toml)}}}

*** Day 25: A song you like by an artist no longer living
/They Don't Care About Us/ by Michael Jackson

{{{spotify_embed(they-don-t-care-about-us.toml)}}}

*** Day 26: A song that makes you want to fall in love
/Something About Us/ by Daft Punk

{{{spotify_embed(something-about-us.toml)}}}

*** Day 27: A song that breaks you heart
/Por una Cabeza/ by Horacio Rivera

{{{spotify_embed(por-una-cabeza.toml)}}}

*** Day 28: A song by an artist whose voice you love
Straight-up missed this one. Oh well

*** Day 29: A song you remember from your childhood
Really couldn't come up with this one. Wasn't much of a music listener back
in the ol' days ¯\\_(ツ)_/¯

*** Day 30: A song that reminds you of yourself
/Veridis Quo/ by Daft Punk

{{{spotify_embed(veridis-quo.toml)}}}
