* About 🤔
  
  My name is Sagindyk, everybody just calls me Sandy. Currently, I am a
  Computer Science undergraduate student at [[https://ku.edu][University of Kansas]]
  I am a huge fan of =*UNIX*= philosophy and =Linux= tools in
  general. Wield the power of the terminal with =awk=, =sed=, and =grep=!
  I have interests in cyber-security, DevOps, Software Development, System
  Automation, Data Science, and Typesetting tools. I am the current active
  CTO at [[https://kuisc.com][KU Information Security Club]]. I am also the co-founder of [[https://kuemacs.github.io/][KU Emacs
  Club]]!

  I am the creator and founder of
  [[https://reddit.com/u/MemeInvestor_bot][Meme Investor Bot]] - the biggest
  interactive reddit bot on the platform that allows users from all over
  to world to invest in memes and collaborate together around their
  favorite content! Almost a year after the initial launch, more than 20
  developers and ethusiasts worked together towards making a better
  platform for collaborative content creation and promotion. We have more
  than 100 thousand registered users on our system. We have our
  [[https://meme.market][website]] where we keep all the statistics updated
  and available with the current trends, popular content, and meme
  markets! I am the main maintainer of the project. Feel free to check out
  our [[https://github.com/thecsw/memeinvestor_bot][github page]] and commit new changes!

  I am also the creator of other various projects and bots, such as
  [[https://reddit.com/u/prequelmemes_bot][u/PrequelMemes_bot]], [[https://reddit.com/u/HiveWriting_bot][u/HiveWriting_bot]], [[https://reddit.com/u/MemePolice_bot][u/MemePolice_bot]], and so much more!
  For a more detailed list of my open projects, check [[https://github.com/thecsw][my github page]]!
