#+setupfile: ../00_film_skipthis.org
#+date: 3; 12025 H.E. 2350
* Eyes Wide Shut
It actually didn't impress me that much. I recall seeing it many years ago, so
finding myself fortunate enough not remembering anything about the actual
contents or what impression it left on me before, I thought, "why not see it?"
Nicole Kidman is a babe, Tom Cruise is also a babe, but otherwise, it's rather
bland. The ``shock factor'' of the rich wearing masks and having sex somewhere in
a mansion falls into a ``and what'' territory.

To get some of the good things out of the way, besides hot leads—cinematography
is beautiful, the colors are well balanced. You could tell there is experience
behind how this is staged and filmed. Every shot and scene was nice to look at
and the choreography and tension during the mansion scenes were also handled
well.

However, the plot itself leaves more to be desired, personally. It simply did
not engage me nor did I care that much for either of
them. Especially... when.... they... talk.......... like....... t h a t. It's
not really sexy or hot, it's more of a Hollywood idea of what sexy is for the
horny audiences. Where is the juice? It feels as if the movie wanted to do more,
have some stakes, really ram in some idea or a coherent thought, but it never
could and ended up with little to say.

{{{three}}}
