* Reddit API wrapper for gophers 🎩

I like Go and I think it's a great language. I built [[https://github.com/thecsw/memeinvestor_bot][memeinvestor_bot]], which was
one of the interactive reddit bots on the platform at the time. So you can
imagine we used quite a bit of [[https://github.com/praw-dev/praw][praw]]. About year and a half later, the python
codebase became so disgusting and unmaintainable, where I decided to re-write the
whole thing in Go. (The old "let's rewrite everything" syndrome") Re-write would be
too strong, re-build from scratch is what the goal was.  

Surely, after a couple of seconds of DuckDuckGoing, I stumbled upon [[https://github.com/turnage/graw][graw]], one of
the most popular Go Reddit Api Wrappers. I remember that I was just learning Go
at a time and really just wanted to do something with it. Graw's deal with
=announcer= and other stuff confused me a bit. So I did what every software
engineer does when it itches the wrong way. Make a new library! 

I present to you, [[https://github.com/thecsw/mira][mira]]! It's a really playful and straight-forward library. Mira
aggressively uses the dot-notation ([[https://github.com/jinzhu/gorm][gorm]] style) and has the simplicity of
praw. Golang's great features as goroutines are used to implement the streaming
functionality.

-> [[https://sandyuraz.com/blog/mira_reddit][Go to the mira article]]

-> [[https://github.com/thecsw/mira][Go to mira's repository]]
