#+html_head: <script async src="wotakoi.js"></script>
#+html_head: <link rel="stylesheet" type="text/css" href="wotakoi.css">
#+options: tomb:nil preview:preview.jpeg preview-width:1333 preview-height:1000
#+html_head: <meta name="theme-color" property="theme-color" content="white">
#+date: 364; 12023 H.E. 1400
* WOTAKOI 💜

/Wotakoi/ is near and dear to my heart. It was somewhere around the start of the
end of 2022, must have been early December. I got so sick that I'll take calling
me bedridden as a form of flattery. The mood was so special that I even slept in
my living room for the entire week, moving all my bedsheets and bedroom-bound
belongings over to my big comfy soft inviting wide couch.

The only form of entertainment I was feeling attracted to was the collection of
some manga books of ``Wotakoi: Love Is Hard For Otaku.'' No clue what it meant
when I eyed them at Barnes & Noble---I like it this way. The more of a blind man
I am going in to something---the more excited I get. All the meta stuff around
the work is fine only after you've enjoyed the original body of work.

#+begin_center
*I. Absolutely. Loved. It. With. All. My. Heart.*
#+end_center

#+begin_gallery
# - [[https://photos.sandyuraz.com/NJh][Pink looks fantastic on men---we should embrace it more]] :no-zoom
- [[https://photos.sandyuraz.com/lHD][They look so cool]] :flex 60
- [[https://photos.sandyuraz.com/qHx][Narumi on the train dozed off]] :flex 30
# - [[https://photos.sandyuraz.com/xmc][Narumi is so real.]] :no-zoom
#+end_gallery

There is a certain inexplicable charm of /Wotakoi/; seeing all the nerdy adults
living day to day in their routine corporate life and making something of theirs
in the little free time between work and sleep. Working in a similar corporate
environment and /liking/ nerdy things, I can relate to it much better than to a
coming of age of 16-17 year olds. The latter is my food too; I'm not going to
bite the hand that feeds me. But there is something about an adult manga. (heh)

Surprisingly enough, even though the setting of the story is quite mundane, it
offers a great way to escape that mundaneness itself; reframe it in a more
uplifting vision---offering some sort of a ``escapist's reality, re-imagined.''
Somehow, even being deathly ill (not really /deathly/), and now, more than a year
later---modus operandi of our daily modern lives became just a little bit more
/Wotakoi/.

#+begin_gallery
- [[https://photos.sandyuraz.com/diy][This is the 🥹 emoji]] :flex 30
- [[https://photos.sandyuraz.com/ugu][The main cast together]] :flex 65
#+end_gallery

This was a quick word I wanted to put out and at the same time without touching
the actual story or going over what happens. Go read it. Or watch it! There is
an anime adaptation of the series. I haven't seen it myself, as the manga came
to me in a vulnerable part and found its way to my heart. All the pictures on
this page are from [[https://www.barnesandnoble.com/w/wotakoi-fujita/1142050947][Wotakoi: Love Is Hard for Otaku Official Art Works]]---if you
liked /Wotakoi/ or anything else, really---getting an artbook is another way of
supporting the author and appreciate all the work that has gone into creating
your special something.

#+begin_gallery
- [[https://photos.sandyuraz.com/NJh][Pink looks fantastic on men---we should embrace it more]] :no-zoom :flex 45
- [[https://photos.sandyuraz.com/xmc][Narumi is so real.]] :no-zoom :flex 45
#+end_gallery


A little easter egg, if I may---I created my own font based on /Wotakoi's/
covers (see the title of this page). Apparently, there is no font like it as it
was created an exclusive graphic of the series' book illustrations. I traced
just the letters needed to spell the title, so if you're interested, there is an
[[Wotakoi.otf][otf]] and [[Wotakoi.woff2][woff2]] available. 

#+begin_center
Merry Christmas and Happy New Year! 🎄🎅🎁
#+end_center
