{{{book}}}
#+date: 361; 12023 H.E.
* Chainsaw Man 🪚

It was the July 30th, 2023. I adored the anime adaptation of Chainsaw Man and on
an impulse, bought all available 11 volumes in English. The week at work was
exhausting, so I was happy to have this gloomy and melancholic late evening all
to myself.

"I already know how the first four volumes of the manga go," I thought as I was
staring at the menacingly-looking tower of CSM volumes. "If not today—then
when?"

From 9pm to 7am—not a moment of hesitation as I was clearing each installment,
very carefully, taking my time to go through each panel and take it in as much
as I could. All I could say, if me staying up all night (very rare) is not a
strong sign of in itself—phenomenal work by Tatsuki Fujimoto.

The worlds he creates, starting from a collection of his earlier works described
in /17-21 Fujimoto Tatsuki/ and
/22-26 Fujimoto Tatsuki/ are unique, vibrating with colors, and
possess some sort of a Lynch-ian dream-like quality. Yet, the human and
bureaucratic parts of those are very much grounded in reality.

The anime adaptation is of course a very different beast, which is out of scope
for the book. But I want to note on how even Makima feels different in the manga
and the show. In the anime, she exudes more feminine qualities (especially with
some chosen shots), whereas in the manga, Makima presents herself even more of a
mysterious beast, whom crossing paths with is a surefire way to be presented
with a paved path straight to Hell.

Beautifully written, short, concise, and at the same time, tackling many of
humanity's and sociological issues through the lens of devils and how their
powers operate. Makima is an absolute favorite character of mine. Even through
the events of the first arc, there is something so alluring and sinister about
her that biting the forbidden apple might just be worth it.

Looking forward to new chapters and continuation of Nayuta's story, as it began
in Fujimoto's earlier work. (I also have the extra rare big Makima bean
plushie—I'm all in).
