#+date: 350; 12024 H.E. 1727
#+options: preview:preview.jpg preview-height:1000 preview-width:1317
* Ao Nanjo 🩱

I'm in love with [[https://kaoming.fanbox.cc/][Kaoming's]] works and characters they bring to life so
effortlessly. So much so that I pre-ordered their [[https://meccha-japan.com/en/figuresmecha/73089-figure-ao-nanjo-illustrated-by-kaomin.html][Ao Nanjo bathing suit figure]]
almost a year and a half in advance---it was almost a complete and total
disappointment. Do not believe the pictures, as they are not accurate---with the
bathing suit not being as translucent as shown---with hair made in too simple
shapes---with the plastic on the eyes being lower quality---with the general
feel and edges looking rough; it was a bust. Unfortunately, an oversell on the
sculptor's and marketing's side---it's only OK.

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/vyJ][The back part looks especially cheap---you can see the extra sharp plastic
  edges]] :flex 30 :no-zoom
- [[https://photos.sandyuraz.com/XyM][From the bottom part, it looks fine, but could have been better]] :flex 35 :no-zoom
- [[https://photos.sandyuraz.com/qdO][Overall, a general lack of love and attention to details and the promised look
  & feel]] :flex 30 :no-zoom
#+end_gallery

