#+date: 5; 12023 H.E.
* Joker Neondroid ☕️

#+begin_gallery :num 3
- [[https://photos.sandyuraz.com/FNx][Arsène! "Arsene's design is so cool like omg"]]
- [[https://photos.sandyuraz.com/moO][rei joker "Persona 5 and Evangelion crossover??"]]
- [[https://photos.sandyuraz.com/RXY][phantoms "I like this pose with red eyes and holding 'fake' gun"]]
#+end_gallery

#+begin_gallery :num 1
- [[https://photos.sandyuraz.com/maJ][my colleagues "Where have you been? Been searching all along..."]]
#+end_gallery

My last year at college was the most grueling part of my life. Taking 21 credit
hours, three majors, two jobs, not going to Ph.D. or graduate school in favor of
going into corporate -- it all weighs in on you. No one tells you this. One of
the things that gave me immense comfort and an out was Joseph Anderson's Persona
5 streams. I would watch them while falling asleep, working my jobs, and doing
regular homework. A calming voice that was always there. It gave me peace. Very
parasocial. Thank you.

Despite me actively watching over 200 hours worth of Persona 5 content -- I have
never played the actual game. Thinking of it, I probably never will. The
soundtrack, choices made within the game (by Joe), the flow of everything -- I
want it all to belong to that time, untainted.

Funnily enough, I also watched the entirety of Persona 4 streams by Joseph
Anderson after graduation (the two months I couldn't move a muscle out of
exhaustion). Still, I would like to play the game for myself one day. Something
about it lures me more than its successor. I don't know -- we will have to
see. But as always,

#+begin_quote
/Every day's great at your Junes!/
#+end_quote
