* The Star with No Name

NOTE: This was a paper for my graduate course in Soviet Cinema taught by
[[https://slavic.ku.edu/vitaly-chernetsky][Dr. Vitaly Chernetsky]]. Here is the [[The Star with no Name.pdf][original paper]].

Did you know Romania has a railway line between Bucharest and Sinaia, a
mountain resort popular with high society thanks to its gambling and
hotel scene? An express train hurriedly runs from its point of departure
to its destination. Passengers on the train are either excited to get a
lucky gambling streak at a casino or return to business as usual.
Interestingly, none of the people on board would know a small provincial
town on the railway. But we also must ask ourselves, how would they
know? It's not like the train ever bothers to stop there. However, for
the townspeople, the sight of the never-halting passing express is an
occasion to get together at the train station and socialize. Marvel at
the jewelry of the madam from the second car and the elegant hat of the
lady from the seventh car. Even the lingering scent of French perfume is
to be celebrated. Please do mind; every passing train has never slowed
for even an iota down. Fatefully, the seemingly tranquil life of the
town is severely disturbed when a passenger is forced off the train at
the station because they tried to pay for the ticket with casino chips,
which expectedly were not accepted by the conductor.

The passenger's name is Mona, a member of the high society; bored with
her life spent in casinos and fancy hotels, she runs away from Sinaia.
She encounters Miroiu, the naïve astronomy teacher at the town's
gymnasium, with whom she spends the lovely night. Mona discovers the
wonders of a new life of love and the simple pleasures of a provincial
lifestyle. We witness the possibility of a life of fulfillment, a happy
life, and even prospects of a loving marriage. However, no star deviates
from its path. Social obligations of their ordained destiny put an end
to the utopian dream, which was so short-lived. It is a story of love,
the kind of love which knowing no bounds nor laws, violently sparks in a
single instant yet would remain untested and unlived. This paper will
compare the original play from 1944 by Mihail Sebastian, /The Star with
no Name/, and the Soviet film adaptation directed by Mikhail Kozakov,
/Nameless Star/. The primary purpose of our work will be to concentrate
on changes brought by the adaptation, how they differ, and what shifts
we can observe both stylistically and narratively. I haven't found any
research on comparative analysis of those two versions; therefore, our
work from here and on will be unique.

Firstly, the film adaptation changes multiple scenes from its source and
adds new ones and new characters instead. Even with those changes
enacted, I would like to preface that the movie stays incredibly
faithful to the original play and the emotional impact. Mikhail Kozakov
directed /Nameless Star/ almost forty-five years after the initial
publication of /The Star with no Name/ by Mihail Sebastian. The setting
in both versions is a provincial town in Romania, sometime in the 1930s.
It's a small and quiet town with around eight thousand residents. The
town is so restricted that everyone knows each other, their daily
schedule, every intrigue and little drama happening in their lives, and
all the neighbors in a multiple-block radius. Life is simple. The
differences start here.

The play opens with its first scene of the first act sometime in the
evening at the small provincial train station. The small office of the
stationmaster, which is also the ticket office, is used as the setting
in the scene. We observe a couple of interactions between the
stationmaster and peasants trying to get train tickets. All of it is
accompanied by absurd uptightness and bureaucracy of the train station.
The hilarious story shows a peasant coming to buy a ticket, only to get
refused by the stationmaster, who later walks a couple of feet to open
the other window; and refuses the peasant yet again, because now the
ticket office is closed, only to be open half an hour before the arrival
of the train. This bit, in the beginning, works as a tone-setter, which
amplifies the ridiculous rules of the small train station, mainly
because there is nothing else to do nor nothing else to exert power on.
A healthy amount of corruption and embezzlement is demonstrated by the
stationmaster forcefully selling another peasant a dubiously expensive
train ticket because his wife needed five hundred lei to go to the
market. Stationmaster Ipistat is the embodiment of these vices. He uses
the train station ticket office cash flow directly into his pocket.
Mihail Sebastian wishes to engage us with a satirical play on provincial
narrow-mindedness and the cowardly way that many municipal institutions
are run. As readers, we are immediately immersed in the reality of what
it must have felt like to be alive in the small Romania of that era.
This is a powerful opening, which is indicative of the play's rich, some
would even call, distinctly Chekhovian atmosphere. [fn:: Oana Sanziana Marian,
/Mihail Sebastian's “The Accident”/ published by “Words without Borders,” June
2011]

However, the film opens a little bit differently than its source
material. We start with a lovely scene of Marin Miroiu taking a stroll
across the town's streets with the narrator describing the setting and
period of all the events that occurred; while also giving us, the
viewers, an excellent tour of all the town's landmarks, such as the
vital train station, Pascu's convenience store, Chiroiu's tax office,
jail, and of course the gymnasium where Miroiu teaches. He walks into
the school building, and now we are in a scene of him teaching about the
Solar System and the Sun. It is, of course, not the largest nor the
brightest star, yet it gives us life. Though this introduction differs
from the play, it leaves off the same aura of the setting we are about
to get closely acquainted with. Miroiu is presented as a caring teacher,
maybe even naïve and romantic, due to some of his remarks regarding the
astronomy topics he teaches in class. The play focused on the absurdity
and corrupt nature of the small town; the film decided to turn its
attention to its provinciality. When a student in the classroom,
Zamfirescu, was quizzed over the material, she dutifully said that
Jupiter is Moon's satellite, only to show how genuinely unsophisticated
this small town is. At least it has a beloved train station, where the
diesel-electric train passes by and never stops.

After the minor crime of coercing a peasant to buy a needless and
expensive ticket, we are to meet the crucial characters of the play.
Marin comes to the train station to inquire about Mr. Pascu, who is
delivering a book from Bucharest. Of course, we find that the clock on
the platform, instead of working correctly, is constantly adjusted with
the arrivals of trains. When number 747 arrives from Campina, it's eight
o'clock. When the 63 and 97 cross paths, it's five past 12. Wall clocks:
you can never trust these things. Marin came too early, as his delivery
was scheduled for the evening. Upon hearing so, he promptly leaves,
promising to come back later. Promptly, we are graciously introduced to
Miss Cucu, or the “local upholder of justice and all the things that are
proper.” When Marin comes back, she scolds Zamfirescu for showing up at
the station, threatening to expel her, which seems to be the only
school. Our initial acquaintance with Zamfirescu differs from the film's
school scene to show how strict Miss Cucu is about the perverted train
station and its corrupting force on the students. Sending the crying
student off their way, the train whistles get louder; Mr. Pascu arrives
with the commuter train.

The adaptation took their liberty with this scene by giving it more life
and colors than the play. The first significant deviation is how crowded
the train station is compared to the play. New characters are introduced
to the story that were not present in the play, like the stationmaster's
wife. In the play's scene, the only people at the station are the
stationmaster; his assistant, Ichim; Marin Miroiu; Miss Cucu; and poor
Zamfirescu. The movie shows at least a couple dozen townsfolk enjoying a
lovely day on the station, drinking together, and schmoozing. Ladies are
in their best Sunday dresses, all men wearing full suits. For a good
reason, the current setting is entirely different from the source to
show how important this place is to the people. This little train
station, where no trains of any importance make a stop, is this
provincial town's lifeblood; it is the source of luxury and some
connection to an urban lifestyle. The moment an announcement is made
about an “arriving” electro-diesel train, every person on the platform
immediately jumps up to witness another reality that is about to pass
them by without a single thought of slowing down. Where the play showed
the absurdity of the town through its corrupt nature, the film
accomplishes this, and even more through the scene of townspeople
treating the train station as the most luxurious establishment, where
one could mingle and enjoy the scent of a lady's perfume from the fifth
cart. During this whole scene, we get a similar picture of Marin coming
to the train station to inquire about Mr. Pascu's arrival, only to come
back at a later time; and of Miss, Cucu reprimanding Zamfirescu, whom we
already know, for coming to the train station, even if they were
strictly forbidden to do so. We are shown Marin's house while waiting
for the commuter train to arrive and confronting Miss Cucu about her
narrow-mindedness and ignorance of any outside world and opportunities.
In the film, his house looks very modest yet suitable for the times and
environment that he is in.

From Mr. Pascu's awaited arrival, the play and its adaptation follow a
remarkably similar narrative, both in the setting and dialogues. Both
versions have Marin finally receiving his expensive book, which will
start a new scandal and become the talk of the town because of its cost
and purpose. The only little comedic liberty taken by the film was to
swap Miroiu's book and the stationmaster's wife's order. The sense of
this little confusion was to further illustrate the cowardliness of the
town's bureaucrats not only in the face of their responsibilities but
also their wives and spouses. Mihail Sebastian succeeds at showing what
a sad and tragic loop of misery and corruption many small-town
functionaries are stuck in. After Marin is fully engrossed in
researching his new book in the stationmaster's office, an unthinkable
happens; the revered electro-diesel train has stopped. It never stops. A
stranger is escorted out from the train by the conductor for attempting
to pay for their ticket using Sinaia's casino chips. In her distress,
the stranger, who we later learn to be Mona, is trying to kill herself
by getting run over by a train; fortunately for her, the next train is
only passing by at 11:35, which is ample time from now. Compared to the
film, Mihail Sebastian's play comically demonstrates the stationmaster's
spinelessness in his attempt to advise Mona against killing herself at
their train station; and offering to buy her a ticket to the next stop
instead where she could end her life in her way.

I watched the film in original Russian but read the play in English
translation, as I cannot read Romanian, and no one in the world seems to
possess a Russian copy of the play. While reading Mihail Sebastian's
play and even with the friction caused by translation, I was fascinated
by how faithful /Nameless Star/ stays to its source material. This
paper's focus is not on retelling the story's plot but on comparing the
Soviet adaptation to its Romanian source. Because the film stays very
close to its original text, let us explore small exciting details
instead of going through everything that happens later in the story.

Firstly, the story's setting is set in the pre-World War II era.
However, it is Wednesday in the film, and the entire town is at the
cinema. From the scene of the playing cinema, we know they are screening
the legendary German musical comedy film /The Woman of My Dreams/
directed by Georg Jacoby. However, this musical was released in 1944,
well into the war, which contradicts the time setting of the movie.
These details might be an accidental error that breaks the event's
continuity. They might have even been done on purpose. It is an exciting
detail, nonetheless.

Secondly, Mona sings in the yard the following morning and picks flowers
from the garden. Marin, in the play, rushes to the window, pleading with
Mona to stop stinging, not because he doesn't like it, but because he is
afraid that Chiroiu across the road and Atanasiu from the house with
shrubbery will hear her. However, in the film's script, Marin Miroiu is
much more liberal and less scared of the provincial scandals that will
start with his name. The adaptation presents our main hero as a more
open-minded and brave person to combat the town's prejudices and
gossips. This is not to say that Mihail Sebastian presented Marin as a
more cowardly person but merely more surprised at how his life has
changed in a single night.

Thirdly, the adaptation adds a few new scenes that are not present in
the play. When Miroiu leaves the house to get his paycheck from school
and buy Mona a new dress, we see the same shot from the beginning of the
movie when Marin walks through the town. However, instead of walking, he
is giddily hopping across the street to show his renewed state of mind.
Another scene with Grig and the stationmaster driving through the town's
roads shows how prestigious cars are.

Mihail Sebastian depicts the upper classes as leading empty life full of
boredom. Mona and Grig come from a different society; it would be safer
to say that they come from another world or planet. In Grig's world, the
notion of love or happiness does not exist in their vocabulary. They are
too busy for that; they are creatures of luxury from a world where money
is easily gained and as easily spent. Marin and Mona's love story is a
tragedy of how even with deep love transcending worldly and physical
restrictions, they are incompatible with each other, as social order and
tranquility need to be restored through the sacrifice of true love.
Perhaps, an authentic life cannot exist in the same realm as one's
social obligations and belonging.

Finally, thanks to the phenomenal acting of the film's main cast:
Anastasiya Vertinskaya as Mona; Igor Kostolevsky as Marin; and Mikhail
Kozakov as Grig, who is also the director, the play's writing received a
masterfully executed and faithful to Mihail Sebastian's ideas
adaptation, which transcends time and stays relevant even in our times.
Even to this day, many still dispute whether Mona should have stayed and
lived a provincial yet happy life with Miroiu. I observe that people who
make such claims have missed the central idea Mihail Sebastian conveyed
in his masterpiece.

#+begin_center
/No star deviates from its path./
#+end_center
