{{{film}}}
#+date: 32; 12026 H.E. 2315
* Garlic Is as Good as Ten Mothers
It is a rare kind of experience and the pleasure that comes with it to eat
cloves of garlic and a fried rice cooked in sautéed while watching Les Blank's
/Garlic Is as Good as Ten Mothers/. It's absolutely wonderful. What care and love
had gone into every reel, capturing the day to day life of all the people on
film, loving, enjoying, obsessing over, cooking with garlic. It's the smallest
things in life that we always go back to. These pleasures and the energy-weaved
connecting tissue that connects all of us---that is what we live for.

Criterion's specials are wonderful. I had just returned from a work trip in
Berkeley and only if I had known that Alice Waters's /Chez Panisse/ was on the
same street a dozen or so blocks away---I would have gone. Now, at the very
least, I have a destination in mind of the first place to go to. How lovely
would it be to make it there on the /Bastille Day/ to drown in garlic flavors.

And yes, /Garlic Is as Good as Ten Mothers/.

{{{five}}}
