{{{film}}}
{{{soot_darker}}}
#+date: 49; 12026 H.E. 0400
* Wild at Heart
This itself got me /Wild at Heart/.

Having written [[https://sandyuraz.com/blogs/twin-peaks/][extensively]] about David Lynch's work before, I now understand
that it's all if not fluff, an extra to what his craft is about. It's either,
dear reader, you feel it and get /wild/ or you don't. There isn't a right answer;
there is no virtue signaling; there is no fame or glory in ``being in the
club.'' It's more personal than that. For the longest time, I *was not* in the
cool kids club and perceived the entire Lynchian genre from a strictly academic,
sanitized, removed perspective. All of this even after having loved /Twin Peaks/
for many years at that point. Then, one day, something *clicked*. I do not know
what it was. But I like to attribute to reading David Lynch's book on
meditations, /Catching the Big Fish/, where---now, I'm recalling this from
memory---he says,

#+begin_quote
/Ideas are like fish, if you submerge yourself in the water, and stay quiet
quite, then all the fish start showing up and you can see them passing
through. Thinking too loud is like sending shockwaves through the
water, scaring all the beautiful fish away./
#+end_quote

Out of all David Lynch's works, /Wild at Heart/ is possibly the most terrifying
one, not only because of Willem Dafoe's demonic performance as Bobby Peru, but
due to the ``Lynchian'' immediate surroundings and the cold cold world that Nic
Cage with his snakeskin jacket and lovely Laura Dern are thrown into. I'll need
to revisit this myself later, after some buffer period, to, as you know, feel it
through more. David Lynch's mind was God's own private mystery.

{{{four}}}\ /loved it, some parts threw me off, need to digest/
