#+options: preview-generate:t
#+date: 278; 12025 H.E. 0049
* Feeling ☕️
I can't seem to feel when I want to feel so desperately. When I must feel, why
do I not have that sensation? There is something to be said of not being overly
emotional or letting the fleeting sensations of the moment control the mind, but
there is an equally strong argument to be made in favor of following those gusts
of inspiration, as they often lead to places and times that are locked to anyone
with a mind that is too literal and rational. Where does the carelessness stop
and indifference start?

I remember how watching movies made me feel as if I were involved in the scene
unfolding right in front of my eyes. The heroes of the story arguing and
fighting of whatever it might be---I'm there, in the corner of the room, in the
front seat of the bus, or standing across the corner of the street, seeing it
unfolding. Feeling what the air smells like. Feeling what the sensation of the
moment is down to the humidity level. And now, instead of feeling, it's knowing,
but it's a lonely world out here, because instead of experiencing it so, I can
only imagine what it must /feel/ like to live through it, rather than giving
myself to it almost unconsciously.

Maybe it is the busy life, but what I watch now feels more like content rather
than art. The memories of what I watch are stronger than the moment
itself. Watching /Happy Together/ by Wong Kar-Wai right now, I haven't felt
anything. Not to say that I'm forcing myself to feel things, as that is a
dead-end for real. What happened? I used to watch the likes of /Lost in
Translation/ or /The Big Lebowski/ and know exactly what those environments were
like without ever physically being present there. What is the balance? How do we
stay feeling and conscious beings, but also not become slaves to it? How do I do
it?

Listening to /Something About Us/ during my first big heartbreak, it was
devastating yet healing. I could say there was an argument of fetishizing one's
depression or feeling sorry for oneself and one---me, specifically---should only
do so for a very limited time, otherwise it has a nasty habit of growing
uncontrollably into something much more mediocre. As much as I would like to
avoid that, I fear of becoming something too rational, too analytical, too
unfeeling. Do I feel so much from day to day life that I no longer have the
capacity to extend it to the arts I used to devote so much of  myself to?

I also know that I cannot and must not force myself to feel, as that defeats the
purpose of the genuine reaction. But, somehow we must also train and discipline
ourselves to be present in the moment, but thoughts creep in that may not be
there and giving them too much attention---even subconsciously---irritates us
and makes me want it to go away, which only accents the attention on it ever so
more. The mind is not something physical that we can simply touch and affect
directly by grabbing everything that mustn't be there and plugging it
off.

Last time I recall feeling and getting transported to another life, another
Universe was reading through /Brothers Karamazov/. My day to day then as a college
student about to graduate was trying. In the morning, I would do my classes'
homework assignment and some async lectures. From then until evening-ish, I was
working as a research fellow at a national lab, so no rest of the wicked
there. From the early hours of the evening after work, with a little sustenance
that went a long way back then, I would grab my ten pound /BK/ and read carefully
through each line until I exhaust myself to the point of passing out on the
couch where all of my reading and weeping would happen.

Famously, I always say that my reading experience had peaked with /BK/, which I
still believe to be the case. I say that in the best possible sense, since it
does not take away the enjoyment---at least, not fully---from whatever I'm
reading, but I know that seldom anything could reach the heights /Dostoevsky/
conquered with his novel. It is such that I refuse to believe a mere mortal man
can produce anything of this substance, it's too much. It must be the Universe
taking a snapshot of what had actually transpired at that time and materializing
paper with all the ink on it. All of this because I refuse to believe a human
mind can internalize and articulate emotions of such depth in such a way.

I don't know. Living a life too rational is to devoid yourself of the pleasures
of what makes us... us, but take it too much in the other way, and you have the
infantile and naivete that gets warned about everywhere. What is the practical
application of romance to the modern life? If /Dostoevsky/ talked of ``active
love'', where is the ``active feeling'' or ``active romance'' as in the /BK/-style
definition of what it means to feel freely and subconsciously, but also staying
rational around them? I should go and read more and watch more and try to stay
present more. I think I am present. I think I am. I think I am. I'm here. Hello.
