* Don't be weird about it 🥡

93; 12022 H.E.

An alternative title I had for this essay was /Embracing Yourself/, embracing your
interests, and staying true to yourself. I'm getting ahead of myself. Let's walk
through some of my thought processes more coherently.  

We're all just people that do our own thing and have our hobbies, no matter how
niche they are. I observe many people would shy away from something they might
like simply because they fear the ones around them might not understand their
interests. However, this line of thought might severely limit you from pursuing
the path that is meant for you. There is nothing as evil and twisted as losing
the grasp of who you are.   

Of course, we are talking about interests that are both legal and within the
realm of common sense. Some of the people I talked to would immediately jump to
extreme cases (most of the time illegal) to counter my arguments. Just how sad is
that? You are not able to thread the subtle thought process and are only good
for boring swings to the left or right. This is not a good argument or even an
ounce of thinking. It is simply a cheap /ha, gotcha/ trick. Now we have that
cleared up, let's continue.  

Many fear introducing their hobbies to someone if asked, therefore creating this
weird atmosphere with a healthy dose of awkwardness. An interesting observation
can be made that a situation is as awkward as you make it. If you own up to who
you are, to what you are into, speak with passion and confidence, your
interlocutor will get the vibe you exude and on their part, understand exactly
what you are saying.  

What if you are being judged for your interests? Well, too bad for that
person. Not only because they lose the pleasure of getting to know you better,
but also how closed-minded they should be, instead of recognizing and
appreciating all the beauty and wonders of every day, they decide to miss it and
spend it on something less noble. I can only see how fun it must to be go around
judging and enjoy eating mud.   

Life is yet again, too short to be /too complacent/ with your surroundings’
expectations and burdening the heavyweight of one's prejudice upon
yourself. Learn more about who you are; even dare to befriend yourself. Only you
know what is best for you. I would not want to die with regrets of moments
missed and time passed. Make the bold decision to live.
