#+setupfile: ../_film.org
#+date: 366; 12024 H.E.
* The Six Triple Eight
It has a good story to tell but wholly lacks in imagination, discipline,
technique, nuance, and courage to tell it well. The final execution presented to
us is not only mediocre, it's actively bad as it ruined a good historical
context---which I wasn't even aware of, my first time learning about 6888---the
cast was wooden, the shots were bland, the acting was over-the-top, and the
whole painted war landscape lacked any substance and didn't just play it
safe---it was comatose.

More appropriately, it's a hallmark movie about war. This is unforgivable. These
directors, producers, studios, and writers that have never known what war
is---how truly revolting it is. The loss of life, loss of dreams, loss of
families, communities, societies, and entire races---it's all treated with such
disrespect and lack of subtlety that it made me want to turn off the movie
during the first fifteen minutes. A family member played it for us as their pick
on Netflix, so we all persevered.

Absolute shitshow. The core morale of the store is constantly undercut by its
cartoonishly heavy-handed delivery. Writers tried to grab as much as they could
and were able to hold onto nothing. Waste of time and resources. Nothing but a
feel-good movie about ``some war far away'' that borders on malevolent
propaganda, but judging by its everything---it doesn't have the chops to be
that, it simply thinks too highly of itself. However, I will note that I did
enjoy the last five minutes of the film. Not because it was ending, but thanks
to a nice documentary-style reel of interviews and real footage of 6888th
Central Postal Directory Battalion. Just that would have been good enough. I
hope this story gets told later in a more convincing way.

{{{one}}}
