#+setupfile: ../00_sasakura_skipthis.org
#+date: 197; 12025 H.E. 2254
* Manhattan 🍒

{{{pics(manhattan.jpg)}}}

You can never go wrong with a Manhattan. I can never go wrong with a
Manhattan. There does exist a number of perfect combinations of foods and
beverages, like cappuccino and a croissant, like fish and chips with a Guiness,
like an americano with a bagel---like a Manhattan with a steak. Even if I'm not
treating myself to a nice cut of a red meat---the sharp yet viscous sensation of
this drink is almost impossible to beat.

My Manhattan is the simplest one there is, it's only that the parts have to be
well-chosen. For the rye, you must go with something at least 100 proof,
otherwise the lower proof whiskies lose themselves in the sweetness of the
vermouth and spiciness of the bitters. I like when my Manhattan has a bite to it
and feels almost like a meal of its own---it has to have body, as a Manhattan
that is too watered down or thinned out by dilution or sweetness is a Manhattan
wasted. Here it is,

- 2 ounces of /Old Forester 100 Proof Rye Whiskey/
- 1 ounce of /Dolin Sweet Vermouth/
- 2 dashes of /Angostura Bitters/
- 1 dash of /Dale DeGroff’s Pimento Aromatic Bitters/
- 1 /Dirty Sue/ whiskey cherry (*NEVER* red#40 maraschino)

Get some harder ice if possible. Pre-stir the ice in a mixing glass to chill it
down and get rid of any excess water. Put some bitters in the mixing glass,
following up with the whiskey, and topping up with vermouth. Stir gently but
firmly for 20 seconds and strain with a julep strainer into a /Nick & Nora/
glass. Carefully drop the cherry into the glass. Enjoy in the comfort of your
own skin accompanied by some good music---preferably silky/Brooklyn-style
jazz---and take it in. Life distilled to its simplest pleasures---the best ones.

Some like their Manhattans in an old fashioned glass or on the rocks, like Linda
Florentino in [[https://sandyuraz.com/drama/the-last-seduction/][/The Last Seduction/]]---blasphemy. This is a spirit-forward drink,
where tasting the bite yet drowning in its tender love is the absolute peak
experience we can hope for in a bar.
