* Cheburashka, I seek your sociolinguistic wisdom

NOTE: This story was written for my SLAV 540 Slavic Sociolinguistics [[slav540midterm.pdf][midterm]].

I wonder where he is. It's already been more than half an hour and he is still
not here. Everyone knows it. Everyone should know it. It is the unspoken rule in
our society that you are never to be late to a tea party, especially to the one
you are invited to.

This is not too big of an issue. At the end of it all, I am the one who asked
him to come over on such short notice, all because I need his help with my
upcoming linguistics midterm. I have to write an essay about top-down changes
made to alphabets and languages, and also how such a change reflects on
communities that are affected. I am positive that he knows the answer.

I hear knocks on the door. The door handle slowly goes down, the door was left
ajar, so there is no need to turn the handle. I would think it is just a
formality to announce one's arrival.

‘Ha! You're finally here, please come on in,’ I said excitingly after waiting
for his arrival.

‘My apologies for being a little bit late, Sandy. They had a building
construction and closed off the short routes.’ I could hear a little bit of
sadness in my long-awaited guest's voice.

‘No need to worry about it all! I have everything ready for us, Cheburashka’

‘Thank you,’ Cheburashka smiled. ‘I see we have some tea here with sweets. Oh!
Is that one of those Japanese rolled cakes?’

To which I proudly replied, ‘This is a tea party, after all!’

‘Delicious! Did you want to talk to me about something? It sounded fairly urgent
on the phone,’ he looked at me curiously.

‘You are the greatest sociolinguist I know. I was interested in talking to you
about some of the historical top-down changes enacted by elected officials on
alphabets and how those affected relevant societies,’ I said so quickly, so it
doesn't sound like a loaded question.

‘That's a loaded question, Sandy,’ oops. ‘Is this for a course or something?
Either way, I would love to talk about it,’ awesome!

‘I'll try to start and go from what I know, so please do correct me if you feel
the need to. Languages are like people, they are being born, they breathe,
evolve, develop themselves, and naturally die or come to their final resting
place. Speaking of the Slavic world, there were many liberal policies that aimed
at bringing minorities and people from the periphery to acquire Russian and
educating them. In class I remember, it started as far as in 14th century with
Stefan Permskij, who was establishing written languages for previously illiterate
Finnic people,’ is what I remember from our first lectures.

‘That's good, but ask yourself, were the changes and language education always
so liberal and slow in nature?’ Cheburashka leaned closer as if he were quizzing
me. He definitely was.

‘Well, no! Think of Peter the Great and all of the reforms that he brought,
especially to Russian...’

He caught the awkward silence, ‘What did he do exactly?’

‘I hoped you could explore that area a little bit more,’ I said.

‘Why sure. As you just mentioned right before, unfortunately, not all language
changes and enacted policies were so liberal and open to multiple
languages. Many policies, especially in the history of Russia were called top-down,
meaning the changes were less natural and more forced into rules, whether
they are for political or practical reasons. You mentioned Peter the Great, so
why don't we start with him? Peter was proclaimed as /Emperor of All Russia/. He
implemented sweeping reforms aimed at modernizing Russia, ranging from
industrialization, shipbuilding to clothing styles and heavy taxes or
beards. During his whole modernization period, he realized that not only does
Russia need to modernize its equipment and thinking, but also its language.’

He took a sip of his tea with a small bite from the rolled cake.

‘If you were to tell a shipbuilder to construct plans that are similar to
Western alternatives, which have parts that one has never seen, therefore not
even have a word for it, wouldn't that be a problem? Peter started sponsoring
education on all secular lines. He opened schools. Translation of books written
in western European languages was actively supported. Most of all, the
Russian alphabet was modernized and at the same time borrowed (sometimes
adapting) words from foreign languages. In essence, importing all of the
technical terms required for new machinery, made Russian applicable in
describing new developments and ongoing modernization efforts. Observe that this
didn't happen naturally. It was a big pressure from the top of the government to
mirror Western culture and make the language adopt the sweeping changes brought
by his reforms,’ he regurgitated it as if he were reading it from a book.

‘I see! Even if top-down changes sound a little bit harsh, they were the
the catalyst for the Russian Empire’s evolution into one of the most powerful nations
in the world. The language and alphabet changes united people all across
Russia. Streamlined printing process, such that any Russian citizen from an
the entire region can read and understand the latest developments of the industry,
the navy, victories of the Russian army, thus bringing Russia and Russian people
from medieval times into modernity,’ it was exciting to see how this seemingly
small change in vocabulary and alphabet can propel an entire society into a new
era. I remember he called it the "civil type", which abandoned the medieval
calligraphy tradition and moved onto Westernized typefaces. This allowed the
usage of Russian printing machines.’

‘Now you start seeing it,’ Cheburashka said as if he were a proud father looking
at his son. ‘Was this the only time there was such a change to the language?’ he
asked me quickly.

‘Of course, there were more! The other big-time for language modernization and
changes from the top brass were during the Soviet era.’

‘Exactly, sounds like home to me, go on!’ He started chewing one of the
chocolate chip cookies I had on the table.

‘I had to read an old Russian text from the 19th century and I must say the words
looked super goofy. There were weird letters like Greek $\theta$, Latin $i$,
and "myaghkii znak" with a line strike through. The most egregious of them all
was almost every word ending with "tverdyi znak".’

‘They did look goofy because they actually came from Greek!’ Cheburashka
apparently likes chocolate chip cookies. ‘$\theta$, $i$, came straight from
Greek and were later replaced with "ph" and "i". In medieval Russian, "tverdyi
znak" signaled a sound that was long gone, as it disappeared from the language
entirely. However, it was still written at the end of almost every word--’

‘But isn't that wasteful? I imagine all the ink that is used to type up a letter
that just doesn't contribute or do anything,’ I interjected rudely.

‘Of course and this is one of the big reasons why in 1918, Bolsheviks that just
came to power launched a reform of Russian orthography as part of a bigger
project to increase mass literacy. The letters that you don't seem to like very
much was removed from the language, you could say "by force", everyone had to
follow the new standards. Naturally, from a cost-benefit viewpoint, the
orthographic forms meant economies of scale: the reduction of redundant signs
generated savings in metal type, typesetting labor, ink, and paper
[Marc Greenberg]’ 

‘I would assume that the changes weren't driven purely out of economical
interests, but also more of ideology development and literacy education. If I
look at it, fewer letters, and a simpler structure would ease up the language
acquisition, which would allow people to learn it at a faster pace, therefore
increasing the educated and literate portion of the population,’ I was quiet
proud of myself to see the connection there. ‘This is a self-revolving cycle, where
even such a small change to the language produces more educated people, educated
people take care of everything else. The Bolsheviks aimed at solving what seemed
almost an impossible challenge - plant the seed of socialist ideology into the
minds and hearts of a divided population, consisting of a minority of literate
elite and an overwhelming majority of underclass peasants and workers with
little literacy or even none whatsoever.’

‘The effects that this successful adoption had on people and the Soviet society
should be left for another time, the least we can say is that it was grand,’
Cheburashka was pouring another cup of tea.

I happily realized, ‘Thank you! I think I have everything I need for my
midterm.’

‘Are you already kicking me out?’ he asked grinningly.

‘What are you talking about? I could never!’ I was flabbergasted.

‘I'm just kidding, say, have you finally watched KonoSuba?’ he said picking up
another one of those fluffy Japanese cakes. 

‘It's funny you mention it...’
