* Video games are kinda boring 🕹

93; 12022 H.E.

I observe that video games just aren't that fun. It is not my intention now to
trivialize it down to /oh cmon bro, it's pixels changing on your monitor/, but to
discuss the effect of video games on us, the entertainment value, and its
necessity (or its uselessness) in our lives. Nonetheless, prepare for a hot and
a subjective take. Shall we?  

I am no stranger to video games, consoles, gacha, and playing for the majority
of waking hours in a day. My steam account has around 478 hours in Team Fortress
2 (I loved that game), 389 in Grand Theft Auto V (it was so much fun), 380 in
csgo (silver was my ceiling), 377 in Payday 2 (nothing like being a smooth
criminal), 233 in Sid Meier's Civilization V (Gandhi loves nuclear weapons), and
collectively about 300 more hours in other games.  

Phew, just listing them out and seeing all the time spent is quite something. Do
I regret the many hours I spent playing because I could have invested them into
something else? Nope. It was a blast, I enjoyed the games, as all of the hours
were during a span of ~6 years. ``But Sandy, you spent all this time and now
games are /kinda/ boring?''. Yes, that too.  

I stopped playing games, and just quit cold turkey when I went to college. Not
only because of the lack of free time I once possessed but also of the sheer
boredom that came with every new session I would start. In no way am I a
competitive player nor do I play ranked games in any way, however, even casual
ones don't seem as exhilarating as they once were. It's all just the same.  

You play any shooter game, you go around, you shoot players, and win with your
team. Think of any popular game (csgo, valorant, Fortnite, apex) and it is the
same formula chewed up and spit right back at ya. Of course, they have
differences like unique visuals, new items, and various ults/powers, but *at the
very core, it's the same rotten stew*. This methodology applies to any genre
(except storyline-driven ones), whether it is an RTS or MOBA or RPG, or
others. They lack a higher purpose.  

What do I mean by that? I want a big picture, a grand goal that we strive
towards. Something noble that we yearn for. I'm not talking about raising your
level, getting medals, or in-game achievements. There has to be a uniting
principle that brings individuals together to work on a common goal. A bit of an
extreme, yet a good example in my head is for /Sword Art Online/.  

Players are stuck in the game called /Sword Art Online/ and if they try to leave
the game before the final boss is beaten, then the neural gear they're hooked
into will send a lethal electrical current to the brain, therefore killing them
instantly. A horrifying premise, yet the people in it had a unifying goal to
work with each other, as it meant the survival of everyone stuck in the game.  

Alternatively, imagine a less brutal scenario, where players need to clear all
levels' bosses, yet that can only be done by a decisive and well-thought-out
collaboration of all factions, guilds, and game classes. This is to prevent one
DPS or tank group from simply rushing the whole game. The game should have a
variety of factions, jobs, and playstyles one could take. Whether you like
trading and economy (like EVE online), simple farming (like Stardew), risky
adventuring (dungeon-clearing stuff), or anything else, it should be your
prerogative to play what your heart desires.  

It would be a whole self-sustaining world, life can go fast or slow, players can
be active or passive and levels get cleared over a span of multiple weeks or
months. I swear this is not a Zuckerberg-style Metaverse pitch. Instead of
replacing your actual real life with a virtual one, this one would simply work
as an augmentation, where it may complement some of your fantasies and
entertainment needs.   

Also, something important to note, current games are kinda boring because of the
way we interact with them. We are still using keyboards and mice, which have
been around since the beginning of the world. It severely limits how you
interact with the world, only leaving you to inherently flawed human-computer
interfaces. VR headsets and current gear aren’t much better.  

Modern virtual reality needs to work more on the feedback from the virtual
world. If I awkwardly hold my stick and hit something in the game, I should feel
such a sensation in the real world, otherwise, it breaks the illusion. Ideally,
I would love a full-dive interface, where you plug yourself in and all your
senses get connected with a game. You can just lie on your bed, not moving, yet
fully exercising the usual neuron activations to control your body and
experience various sensations.  

Now that (ignoring all privacy and security considerations) is something truly
fun! All I seek is a full sensory experience of what I see and feel within a
virtual environment. In my mind, video games are boring just because of how we
chose to interact with them, limiting them to our eyes, ears, and fingers. There
is more to the art of human-computer interfacing than we allow ourselves to
experience right now.
