{{{film}}}
#+date: 32; 12026 H.E. 2300
* No Other Choice
Trying to write something about Park Chan-wook's new film about how we do live
in a society is proving to be a more difficult task than I had originally
anticipated. The primary reason being that there is not much that I can latch on
to here---with the sole exception of seeing my boy Lee Byung-hun looking through
for the entire run of the film.

It's fun to see the antics the main anti-hero goes through to get his job, now
tainted and marred with the blood and misery of everyone who had happened to be
in his way. With the movie putting such a heavy focus on the not-so-subtle
messaging about what the modern world had done to a man---it betrays itself in
answering the title---did he /really/ have no other choice?

Not to say that /No Other Choice/ fails to convince us on the main premise, but
the further the plot had gone in, the less believable it got to a point of
pushing the messaging so heavily that it had become a caricature of itself---it
may very well be the intention behind it, but the experience of going through it
falls flat on its face, since there isn't much in terms of technical aspects or
aesthetical pleasures to compensate for what is ``another commentary on
society.''

It's a similar feeling I have toward /Oldboy/ and /Parasite/, with the former at
least having fun fight scenes to accompany the waning attention and the latter
leaving a displeasing aftertaste. All of the adventures that the husband had
gone through had been for nothing and it was a nice bowtie to show how he ended
up managing automated AI systems, securing himself the coveted spot and totally
betraying his bravado speech at the beginning of the film about workers standing
up and with each other.

{{{three}}}
