#+options: preview-generate:t
** 42; 12024 H.E.
 *stranger:* You believe... that there are people out there... People like us.

*marin*  I don't know about people. And I doubt they're like us. But maybe some kind of lighter, more luminous beings, less burdened... (Looking up at her, in a different tone)  When I first saw you tonight, walking into that smoky train station – so bright, so clear, shining – for a moment I thought that you came from another world.


*stranger*  Perhaps I am from another world.


*marin* No... no...


*stranger*  How do you know?


*marin*  Because no star deviates from its path, no star stops in it's journey.


*stranger* I am the star that stopped.

-"The Star with no Name"

** 42; 12024 H.E.
 "When I consider the short duration of my life, swallowed up in the eternity before and after, the little space which I fill, and even can see, engulfed in the infinite immensity of spaces of which I am ignorant, and which know me not, I am frightened, and am astonished at being here rather than there; for there is no reason why here rather than there, why now rather than then. Who has put me here? By whose order and direction have this place and time been allotted to me?" –Blaise Pascal

** 42; 12024 H.E.
 "you scooped out my nose" -S.

** 41; 12024 H.E.
 Everytime I find the meaning of life, they change it.

* K.K.'s Fortunes 🦋
** 41; 12024 H.E.
 
omg miso soup!







