* K.K.'s Fortunes 🦋
** 62; 12024 H.E.
 /Without the darkness, you would never know the light./

** 62; 12024 H.E.
 /Beauty is not caused. It is/ - Emily Dickinson

** 60; 12024 H.E.
 "I asked him if he could turn off one of the lights, the glare on the white walls was making me drowsy. He said he couldn't. That was how they'd been wired. It was all or nothing." 
—The Stranger, Albert Camus

** 59; 12024 H.E.
Do not go gentle into that good night,\
Old age should burn and rave at close of day;\
Rage, rage against the dying of the light.\

Though wise men at their end know dark is right,\
Because their words had forked no lightning they\
Do not go gentle into that good night.\

Good men, the last wave by, crying how bright\
Their frail deeds might have danced in a green bay,\
Rage, rage against the dying of the light.\

Wild men who caught and sang the sun in flight,\
And learn, too late, they grieved it on its way,\
Do not go gentle into that good night.\

Grave men, near death, who see with blinding sight\
Blind eyes could blaze like meteors and be gay,\
Rage, rage against the dying of the light.\

And you, my father, there on the sad height,\
Curse, bless, me now with your fierce tears, I pray.\
Do not go gentle into that good night.\
Rage, rage against the dying of the light.\

** 59; 12024 H.E.
 /-we cannot change what has happened, what has happened changes us./

** 57; 12024 H.E.
 /....No one watching—....shards of glass sparkling in the sun. glittering confetti, beautiful and dangerous./ -a dark room

** 55; 12024 H.E.
 "spaghetti bobbit" 🍝

** 55; 12024 H.E.
/Dark skies grey air/ \
/looming over a damp uncanny/ \
/motel, Sleeping in a strangers/ \
/home, their Brain scattered/ \
/on the sidewalks of their/ \
/mind. It smells exhausted/ \
/in here, hair from past/ \
/Travelers scattered on the/ \
/Plastic shower floor/ \
/She pulls The mirror Down/ \
/in the car to see her Blue/ \
/Doll eyes and Blushed lips/ \
/she had Colored with cherry/ \
/Juice in the car ride/ \
/earlier. the roads sweating/ \
/of recent rains, their/ \
/moisture glistening in/ \
/the Dull 5pm light/ \
/She stared at her face/ \
/in an unfamiliar/ \
/mirror/ - something she'd scribbled onto a piece of torn scrap paper maybe even
an old envelope some years ago, even with it being left undated the memory of
where it was written still remains in the rooms of her mind. 
One of the largest thunderstorms she'd ever witnessed happened days later on
that trip.

** 51; 12024 H.E.
  /"Bro are you okay your child like wonder and whimsy have been replaced with a profound sadness"/ —jojo quoting a meme.

** 51; 12024 H.E.
 /"–I love you but go away, so I can miss you."/

** 43; 12024 H.E.
 /``–Do be, do be, do.''/ –*Scooby-Doo.

** 42; 12024 H.E.


 /lights down./

/end of act./

** 42; 12024 H.E.
 *stranger:* You believe... that there are people out there... People like us.

*marin*  I don't know about people. And I doubt they're like us. But maybe some kind of lighter, more luminous beings, less burdened... (Looking up at her, in a different tone)  When I first saw you tonight, walking into that smoky train station – so bright, so clear, shining – for a moment I thought that you came from another world.


*stranger*  Perhaps I am from another world.


*marin* No... no...


*stranger*  How do you know?


*marin*  Because no star deviates from its path, no star stops in it's journey.


*stranger* I am the star that stopped.

-"The Star with no Name"

** 42; 12024 H.E.
 "When I consider the short duration of my life, swallowed up in the eternity before and after, the little space which I fill, and even can see, engulfed in the infinite immensity of spaces of which I am ignorant, and which know me not, I am frightened, and am astonished at being here rather than there; for there is no reason why here rather than there, why now rather than then. Who has put me here? By whose order and direction have this place and time been allotted to me?" –Blaise Pascal

** 42; 12024 H.E.
 "you scooped out my nose" -S.

** 41; 12024 H.E.
 Everytime I find the meaning of life, they change it.

** 41; 12024 H.E.
 
omg miso soup!







