#+setupfile: ../_film.org
#+date: 123; 12025 H.E. 2150
* Supermarket Woman
Juzo Itami did it again---a wonderful story, a Western story of ambition,
rivalry, and triumphic glory. If /Tampopo/ told us the story of a struggling ramen
shop, then this film’s core setting is even more mundane---the supermarket. Like
Goro from /Tampopo/ helping out Tampopo, now we have Tampopo---played by the one
and only, Nobuko Miyamoto---helping out Goro’s ``Honest Mart'' fight off the
existential threat that is the newly-renovated store that is super slimy in
its business tactics---/Discount Demon/.

I absolutely love the sheer focus and discipline the film has in its telling of
this saga. You would think how inconsequential the dynamics of your local
neighborhood supermarket would be, but the film rewards us with a warm and
humanist telling of all the human elements that go into making a truly great
store, the one that will reward the housewives with a drama, fine-tuned to their
personal story---marking each visit as vital part of finding and re-affirming
their identity of supporting their families with the love that goes into making
a delicious meal.

The focus on the goal is much greater than in /Tampopo/---even though we had the
little vignettes, especially with the horny for food yakuza scenes were a lot of
fun---/Supermarket Woman/ delivers a story you can dive yourself into. Feel the
responsibility that comes with putting store advertisements in daily
newspapers; learn the hard truths of incompatibility of artisanal craft
and pride with at-scale and value-oriented operations that a supermarket needs
to run properly; recognize the inherent human element of it all, and the
absolute importance of supporting the local community.

I watched this film twice in one week, one with my partner and the other time
for when we were hosting a good number of our friends for a fiery grill
cookout. This is an absolute must watch---you would be strapped to find anything
with the heart, comedy, drama, and gripping chase scenes as you would in Juzo
Itami's /Supermarket Woman/.

{{{five}}}
