= Using Foundation - style Time 💫
Sagindyk Urazayev <ctu@ku.edu>
About_LINK | Bookshelf_LINK | Fortunes_LINK | Home_LINK
:toc: left
:toc-title: Table of Adventures ⛵
:nofooter:
:experimental:

197; 12020 H.E.

Just recently, I've finally finished the original Foundation trilogy by
Isaac Asimov. I've probably read the first book about three times in the
last four years but I could never get my hands on the remaining two
(_Foundation and Empire_, _Second Foundation_). Not going too deep into
the series, I just want to say they are life - changing, in a good way.

During my read, I saw an interesting date format used by Galactic Empire
and Foundation in the form of `DAY OF THE YEAR; YEAR ERA TIME`.
Something about it gave me an idea of switching my timestamps from
traditional  * Wednesday, July 15th 2020 09:09 PM *  to  * 197; 12020 H.E
2109 * . I wrote a quick webpage that shows
https://sandyuraz.com/time[your current local time] in this format. Why
year 12020? I have link:../year_12019[a post] on that.

This is it. Something about this way of stamping time motivates me and
inspires me. So much for me being a sci - fi romantic 🤷🏻‍♀️

Also, if you use XFCE, here is a clock format you can use:
`%j; 1%Y H.E. %H%M` or `%j; 1%Y H.E. %H%M.%S` to also show dot - separated
seconds counter
