* You are what you eat 🍚

105; 12022 H.E.

#+drop_cap
Eating is *important*. Eating well is *crucial*. For years, I have seen myself
become the kind of person who eats to live, rather than the other type of living
to eat. I would go have my breakfast/lunch/dinner and consume calories just
because I knew I had to, otherwise, it wouldn't go too good for you. This was
all right for me at the time, as I had a crazy packed schedule, which hadn't
allowed me to simply slow down and taste what I was eating.

As an always-broke college student, frozen foods and instant meals seemed like
an absolute deal. I can buy this frozen pizza for $6.99 and get a whole
delicious dinner with some extras left? /sign me up/ I think I followed this
cursed eating regime for my whole junior year, as I have never been busier. I
don't even remember eating that whole year or what I ate. The fact I am alive
now means I had to consume something.

I do want to note that I know how to cook and prepare complex dishes. My
schedule was planned wrong by me, such that I stripped myself of time and
enjoyment for cooking and grocery shopping. I've also tried HelloFresh and other
food delivery (or ready ingredients) for a couple of months, however, even that
proved to be kind of a hassle and /a little pricey/ if that's what you are relying
on.

#+drop_cap
Then it happened. I started throwing up from any sight or smell of frozen or
heavily processed foods, such as frozen pizzas, fries, vegetables, and
burritos. It got so bad to the point that I could recall myself starving in the
middle of the day, while the fridge had food in it. My body and mind would
actively reject anything that reminded me of processed and /just-heat-it-up/
foods.

Cooking for yourself is a double-edged sword as you have to enjoy your food and
not burn yourself out of it. Making similar or the same dishes for some periods
of time can force you to never want to look at your concoction. I would try to
make myself exquisite and involved recipes because they looked and tasted good
with a million spices and ingredients. /I found that the key to a healthy and
sustainable food regime is in something else./

That something is *simplicity*. The simplicity of a dish/recipe and the quality of
ingredients can change your whole view on what food is and how we treat
it. Instead of eating just to survive and because I have to, I started to
finally look forward to cooking again, but to a new much simpler, faster, and
richer experience as well. You just have to [[https://en.wikipedia.org/wiki/KISS_principle][keep it simple, stupid.]]

#+drop_cap
Instead of using a bazillion ingredients from different disciplines, I prefer to
utilize a few and be sure of their quality. The simplicity of a dish brings out
the quality of ingredients, you just have to let them do the talking. Same with
spices, I primarily now use just salt/pepper and /maybe/ one more, depending on if
it goes well with the main ingredient (like meat+garlic). This saves you up on
the cost of extra ingredients, preparation time, and complexity, but also
improves the taste and does not overwhelm your tastebuds.

What are those few ingredients? For me, you must have eggs, milk, rice, pasta,
tomatoes, butter, olive oil, flour, poultry, beef (/depending on your dietary
preferences/restrictions/), fruits, cheese, green onions, potatoes, cilantro, and
fresh bread. I know it looks like a lot; imagining it, you could see how few
ingredients it is. With this combo, /the skies are your limits/. I can combine
them in any way possible, producing varying flavors, yet still relying on the
basics and keeping the nutritional balance.

I am also a believer in the school of eating out. Even though I like to cook
simple dishes, which you don't get bored of by combining them in different ways
and also because of the sheer foundational nature of those dishes, *I love* to eat
out anywhere to try out new flavors, add something to my list of must-haves, and
later on experiment with new recipes I tasted somewhere in the wild, seeing if
they can fit my dietary framework.

I must say, I started eating better, more regularly, it's filling, and you don't
feel like someone dropped a brick into your stomach (/looking at you,
McDonald’s/). It even resulted in positive mood changes and better sleep. I love
having guests over pretty often, so with making something presentable and good
quickly, sprinkling some chopped greens over (aesthetics of the food matter a
lot too), and voilà, you have yourself a delicious meal in front of you and your
guests. Let the number of your ingredients be few, yet make sure they are
good. I observe this applies to many situations in our lives.   
