{{{film}}}
#+date: 185; 12025 H.E. 1459
* A Story of Floating Weeds

#+drop_cap
My father once told me, ``Only if the new generations are better off than the
last, then that is progress. That is why you must be better than I am.'' I have
never forgotten those words as they guide me on what it means to move forward,
not just yourself, but everyone around me and especially those who will come
after me. There is nobody quite like Yasujirō Ozu, who distills down universal
values onto film; cutting through time and our made-up barriers. Almost a
century later, I find myself weeping watching /A Story of Floating Weeds/.

I have not had much experience with the silent era of Japanese cinema, something
I think I should attend to. This first introduction, though I am already a
self-proclaimed adoring follower of Ozu's works and his style—I could not have
asked for anything more fulfilling than this. "You must be a great man." The
humility, strength, and courage it takes to come to a realization and sacrifice
that must follow is a tale spanning time for as long as human dignity and pride
were around for.

#+drop_cap
Absolutely cannot miss the sublime composition in every single one of Ozu's
frames. Always the same height—near the ground. Always the same
lens—50mm. Always evoking the same feeling—a sense of still beauty. It is such a
treat for the eyes and a soothing elixir for the mind that I end up staring at
all the different shots and the Criterion menu playing right now that I forgot I
was writing this piece at all. This is why we make movies and why we watch them.

{{{five}}}
