* From School to Corporate 📞

On February 22nd, 2023, I gave my traditional annual spotlight talk at KU
(University of Kansas) ACM (Association for Computing Machinery) chapter
meeting.

Last time I gave a talk, I was still a student (senior at the time) at KU. I
would call that talk my personal ``magnum opus'', [[https://sandyuraz.com/projects/art/][The Art of Computer Science ❤️]].

I wondered to myself, what can I talk about now? My presentations always tried
to avoid talking about anything too technical, as my interests line up more with
higher-level topics, which can capture all kinds of audiences.

How about I summarize everything I learned about corporate, internships,
and strategies with all the cynicism that it comes with? How does college
prepare one for the private sector or whether it's needed at all?

Please join me through seeing what it means to be a young adult under
capitalism, sprinkled with humble a retrospective into what I have done
throughout my studies and some personal regrets as well.

There isn't a recording like last time, so please find the deck embedded
below. If it doesn't work, it's available through [[https://1drv.ms/b/s!AgTLtpZCbrUtigqsxy2Dve2gk4F5?e=9eNVs0][a direct link]].

#+begin_export html responsive
<iframe
        src="https://onedrive.live.com/embed?cid=2DB56E4296B6CB04&resid=2DB56E4296B6CB04%211287&authkey=AK4SpFdSWpv14lE&em=2"
        width="1000px"
        frameborder="0"
        scrolling="no"
></iframe>
#+end_export
