#+date: 16; 12023 H.E.
* Rem sitting 🪑

#+begin_gallery :num 3
- [[https://bnz05pap002files.storage.live.com/y4m6GX-joS-DXkWse66fZ7ksuV60Jl7Bgoh02i4q6Fnl_WZbCrpkkiYAvlAfvCDcc15hK1CqNm5CnpygSN-LSJGyxfX9KynLMNZjnNvmmh4is8bgrspSAYvH7V6YF3Nhjd2RIdRZnASQwwHiPfOUT6T_5nFbNnz9aR7y5vkIB8Ry7ZLPZU2Wn8VbRmeA91s46EQ?width=2268&height=4032&cropmode=none][From above "the way the tshirt texture falls off is pleasant"]]
- [[https://bnz05pap002files.storage.live.com/y4muAE3qsHRLePB5sPa7Xa006jeQnx0PwUh2rXB_tNE15BuQLFpkQNGnQoCxbyctgHnJyP2xh1HdzvRq4Rb8lx51LNk3CVtqynPWvRkclECsRkkzWXkdCh5ffMgaxYWtuK97Cphg_0IfvIMMYUeyEO2po0nc0S7evw6FTFRhXBbjy4EbzROSLl6wEtb9QUeIdG_?width=2268&height=4032&cropmode=none][Frontal shot "Rem's scene with Subaru... she be real for that"]]
- [[https://bnz05pap002files.storage.live.com/y4m3VaT6fsCbiheM56v0oJAQmixwAqb6CLpws4JvO9mpOhZxW8utY_lqeiDCZWRuLPOjopiuXpiken1hCQN8_NBm8HWGJ2BtBr9tHUZURb4Uc68BFbu7UOwjzY0jhWTIv8x1vqKJOGId38B2X8AS1IWzetGe-9ucH0GuHvz74ZHy-9qY85Am1Yvu2gL8H8hXDAv?width=2268&height=4032&cropmode=none][Full height "what a great pose and sculpting done on this figure"]]
#+end_gallery

#+begin_gallery :num 1
- [[https://bnz05pap002files.storage.live.com/y4mue1lLjJiDiLSrWDwlVEFPyErAYUIK7m6SfNYMpRuAAeB7S5UZzOdlzbW4m9_SsAb5R-6BPTk0vSO4C6UaiInJd_fmjLHVwHj4ipOEZpFIkzom3IZsXSIyftrIe8dLAH0taQe1rOCIMK5J4X_W0n9nDnRRo9EjxfAjV0W3e7AVWli4ccNwhaSSG0j-_3rhcge?width=4032&height=2268&cropmode=none][Fancy sitting "this is where the two Rems actually are, see adam's post"]]
#+end_gallery

#+begin_center
*[[../rem-fancy][There can]] [[../winter-rem][never be]] [[../rem][too many Rem]].*
#+end_center

I've been scrolling through a couple of [[https://rezero.fandom.com/wiki/Rem/Image_Gallery][pictures of Rem from the anime]]. There is
a distinct feeling of "being home" when I see her. Heartwarmingly
welcoming. It's hard to put it into words exactly. Still, I can see why it is
almost impossible to recover financially if you take a liking to her.

It may be because of the time that I watched /Re:Zero/. I would call it the best
time of my life -- I remember it so fondly. It was the winter break of my senior
year. It lasted for around a month, my roommate went to see his relatives, and
everyone else did somewhat similar. It was just me in my apartment for the whole
month.

I don't remember leaving the place throughout the break. I must have had a
mountain of ramen stashed up in my kitchen closet, so much that it might have
rivaled some nations' strategic reserves. Like a goblin or a hobbit stuck in a
cave. Ah, what a time. I miss it sometimes.

I ate ramen, went to bed at like 4 am every night (or morning?), woke up in the
early afternoon, did some chores, and watched anime. One of those shows was
/Re:Zero/. A funny little note, I watched the first one or two episodes with my
roommate, who didn't like it and dropped it. I decided to stick with it and look
where we ended up. *In the best timeline.*
