{{{soot_darker}}}
#+setupfile: _alucard.org
#+html_head: <link rel="stylesheet" type="text/css" href="alucard.css">
* Let us dream instead.

/Let me explain. The Moon used to represent the world of fantasy and dreams. Now
even the Moon has been conquered and become mundane. In today's world, all of
it's legends and mysteries have been exposed, explained, and rendered plain and
boring in the harsh light of day! We lament such trends. We've gathered here to
resist./

#+html_tags: style="text-align:right";
--- Count Alucard from /I.L/

I've taken some pictures throughout the years, which I've been meaning to
publish for a long long while. The time had finally come. Many are shot on my
iPhone 13 Mini in raw with Halide.

-----

{{{img(2024/2024-08-16 swordfish toms.webp | Swordfish Tom's | 40)}}}
{{{date(Friday, August 16th, 12024 H.E.)}}}
*Nothing to see here but the best bar in Kansas City.*

{{{img(2024/2024-08-05 bitch in heat.webp | BITCH IN HEAT | 40 )}}}
{{{date(Monday, August 5th, 12024 H.E.)}}}
*Friend's lighter was pretty cool.*

{{{img(2024/2024-08-05 beach the sun.webp | Oh, the water was gorge. | 80 )}}}
{{{date(Monday, August 5th, 12024 H.E.)}}}
*The air smells different.*

{{{img(2024/2024-08-05 beach.webp | It was cold this morning. | 90)}}}
{{{date(Monday, August 5th, 12024 H.E.)}}}
*What a better way to start the birthday?*

{{{img(2024/2024-03-21 desert.webp | The Jungle Dome. | 65)}}}
{{{date(Friday, March 21st, 12024 H.E.)}}}
*Mitchell Park Domes Horticulture Conservatory in Milwaukee.*

{{{img(2024/2024-02-17 the house.webp | Home sweet home. | 40)}}}
{{{date(Monday, February 17th, 12024 H.E.)}}}
*This was Heaven to me.*

{{{img(2024/2024-02-04 kitchen.webp | Tea, Sweets, and Ink. | 60)}}}
{{{date(Sunday, February 4th, 12024 H.E.)}}}
*This is how I like to write my heart out.*

{{{img(2024/2024-01-16 najimi.webp | I just love their spunk and energy. | 35)}}}
{{{date(Tuesday, January 16th, 12024 H.E.)}}}
*I love them Najimi notebooks---got enough for a lifetime.*

{{{img(2024/2024-01-11 snow.webp | I thought this looked so cool. | 70)}}}
{{{date(Thursday, January 11th, 12024 H.E.)}}}
*It was snowing that day and with nobody out---it was cold.*
