#+setupfile: ../00_film_skipthis.org
#+date: 36; 12025 H.E. 2359
* The Brutalist

/The Brutalist/ with Adrian Brody left a mix of conflicting feelings---not the kinds
that make you think, but the kinds that make you forget you have ever even seen
the movie two days after the fact, which is me right now at night in the kitchen
with nothing more than a paper and a pen; finally, decided to jot down a note or
tow of what I thought.

The exquisite parts are the usual suspects, like /Vistavision/ format and the
actors, namely Adrian Brody and Guy Pierce. The most enjoyable 90 minutes in a
movie theater this year and it's only been a month. The whole first arc was
nothing short of greatness in composition, writing, and execution through
acting. But anything after that was such a brutal miss that it left me wondering
whether /The Brutalist/ stands for how sharp of a nosedive the film would take
after leaving its intermission. This was the bad part.

The bad part is in how heavy-handed the writing and story turned out to be, as
if the muse guiding them from the beginning has left the premises of the
writers' room to never be heard back from ever again. I just don't
understand. With a sharp story, gorgeous cinematography, and a compelling
structure of it all---it should have been a slam dunk.

The heavy handedness of business owners literally ``owning'' the person. The
not-so-subtle-eat-the-rich caricature-esque mission to drill into the audience's
mind; really, out of nowhere, as if completely out of ideas---the final twist
delivered absolutely nothing and only alienated the film from its strong core it
already wasted halfway through its second act. The suspense was gone, as so any
subtlety

/The Brutalist/ was doing well at the start. The latter kind of nothing-burger
``artsy'' shots of postmodernist buildings have solidified my theory of their
muse abandoning them even stronger.The final nail in the coffin was the hammer
of the ``generational message.'' The director didn't just make a mis-step or a
snafu. The second half opened my eyes to it. /The Brutalist/ feels more of a
director's argument that if he shows us serious, intellectual things, shows us
that he thinks of serious and intellectual thoughts, then he of course himself
must be a serious and an intellectual being.

When I view it from this lens now---it all makes sense. The north star was not
creating a great film, but to for us to regard him as a great director. The two,
of course, being things that are far from each other. Formally speaking, the
camerawork is excellent. Two leads' acting is strong. The setting of the time
and place is intriguing and a lot of opportunity to work out from different
angles. Utterly ruined by misplaced time and energy feeding one's ego than to
what they are creating. This is the ugly part of the experience. I had a great
time though. Went with my buddy, had a whole Panera Chicken Pesto sandwich,
double g&t, long island iced tea, and a double shot cognac and soda.

What a night.

{{{two}}}
