#+setupfile: ../_film.org
#+date: 38; 12025 H.E. 2333
* Mulholland Drive

*It does not get more perfect than this.*

I really can't believe myself that I never got around to watching /Mulholland
Drive/ any time sooner. Even though I studied /Twin Peaks/ for my college film
class and followed David Lynch's works across media---/Mulholland Drive/ somehow
had escaped me. Finally, thanks to my partner's grandfather, who in verbatim
told me,

#+begin_quote
You need to go back and start from the beginning.\ It is a great movie.
#+end_quote

Wow. I have really only seen the scene about the mysterious figure behind the
diner and no matter how many years have passed since---I screamed. I screamed so
loud. I screamed from top of my lungs until my partner had to hug me to calm me
down. When the expected scare came with the man behind the diner with such a
hideous face showed himself---it was game over for me and for Betty.

Speaking of Betty---Naomi Watts is drop dead gorgeous. Same of course goes for
Laura Harring. When it comes to works like this, especially since it's of
Lynch's---I can't nor want to say much. There is no need for me to digest or
interpret or do any of this superfluous work. It is /simply/ and /objectively/
*perfect*. There is nothing to remove, nothing to add, nothing to alter.

Everyone will have their own experience. Chewing it through will be akin to
devaluing it, as it's not meant for it. Go for a ride when it's dark on
/Mulholland Drive/.

#+begin_quote
*``Silencio. No hay banda. There is no band. It is an illusion.''*
#+end_quote

{{{five}}}
