{{{film}}}
#+date: 176; 12025 H.E. 2150
* Ballerina
I am a lifetime John Wick customer. Show me anything made by the same people or
in the same world and I am in, same deal as /Matrix/ and /Ballerina/ was no
exception. Only having a few seconds of John Wick in the beginning of the movie
made it all worth it. Everything that appeared after was a treat for the senses.

There is really no films like John Wick. Even though Ballerina is noticeably
weaker and lacking compared to the mainline series' installments, the ratio of
shooting and fighting to talking and pretty much anything else sits in that 99
to 1 ratio, which is just the way I prefer it. The coldest take here would be
that Ana de Armas is very hot, no matter how clumsy or funny some of the scenes
involving her were.

My partner and my friends that I went to the theaters with to see Ballerina
haven't enjoyed the unending stream of beautified violence as much as I
did—their loss lol. This was a refreshing cocktail, I'm feeling a little of gin,
soda, and some cherry syrup perhaps, as its refreshing, boozy, and sweet profile
left me satisfied for the night.

{{{four}}}
