* How to start a story 🪝

84; 12022 H.E.

My toilet is clogged and the cold weather outside is making me cruelly feel all
lonely. This is a fine time to get intimate with a good book and drown myself in
the cozy atmosphere that follows it. I am a spoiled reader, so it better have a
good opening sentence. Speaking of a good opening, how do you start a story?  

I believe the very first sentence should be able to hook the reader's
attention. With so many books in print, a vast array of writers of all genres,
so much to read, yet with limited time, naturally, we are incentivized, I would
dare to say, forced to choose a pick what we would want to invest our time into.  

Frequently, the first introduction into a text is the deciding factor whether
it's read or sadly shelved into the abyss. This usually comes from one's taste,
preferences, and experience in reading. Please consider this take as a
subjective one, derived from what I tend to like in my reading.  

I agree with Chekhov that we should start a story with an action or right in the
middle of it. Some would start describing the scenery, time, background,
etc. (the boring stuff) Tolstoy would throw us right into the heart of
things. Anna Karenina starts with a truly iconic line  

#+begin_quote
/All happy families are alike; each unhappy family is unhappy in its own way./ \
#+end_quote  

This immediately followed with a scene of a woman crying over learning about her
husband's unfaithfulness. In the meantime, said husband is peacefully having
breakfast while preparing to go to work. Mastery.  

``But Sandy,'' my friend exclaimed, ``Starting in the middle of the action kind
of opening can be so confusing because you have no idea what's happening or
who's who.'' To which I replied, ``Well, of course, this technique is not
standalone; it requires both talent and experience, so you’re not alienating
your reader.'' I'm still a lifetime’s worth of experience away from pulling it
off. Not even so sure about the talent part.  

Young child, you should not be worried. There is still hope for us. Many great
writers have come and gone. Fortunately, they left a piece of them behind, a
piece of their soul. I would like to share with you some of my all-time favorite
openings and first sentences. We will start strong.  

Herman Melville's /Moby Dick/ is a classic that transcends time and puts the
flexibility of English as a language to the test. I cannot think of a more
powerful and memorable introduction  

#+begin_quote
/Call me Ishmael./
#+end_quote 

Call to action. Clean. Simple. Immediately draws you in. Iconic. I even adapted
/Moby Dick's/ opening in my [[https://sandyuraz.com/dossier][dossier]]. It's a juicy book, it will have its own time
to shine here. Let's move on.  

Albert Camus was an interesting man. He once famously said,

#+begin_quote
/The meaning of life is whatever prevents you from killing yourself./
#+end_quote 

One of my dear friends loves him, especially /The Stranger/, which opens simply as 

#+begin_quote
/Maman died today./
#+end_quote 

It's *bold*, melancholic, and straight to the heart of what the story is going to
be about. I wish to have the courage to start like that and the competence to
follow up with a narrative that lives up to its promising start.   

If you are interested further in patterns and psychology behind openings lines,
highly recommend a great essay ``[[https://lithub.com/what-makes-a-great-opening-line/][What Makes a Great Opening Line?]]'' by Allegra
Hyde. 

A small honorable mention, I got into some Japanese light novels recently. One
of the shounen books I like simply starts with

#+begin_quote
/Is it wrong to try to pick up girls in a dungeon?/
#+end_quote
