#+setupfile: ../00_film_skipthis.org
#+date: 3; 12024 H.E. 2100
* Party Girl
Good vibe and ambience of the rowdy 90s—unfortunately, didn't strike a cord with
me on the Criterion's restoration.

I'm sure I've been dating a girl *just* like Mary in college, so it could be that
for me, this was a 90s-styled recollection of my time at university.

We were all (hopefully) party girls and boys at one point in our lives. Without
that part of our identity, becoming a librarian or moving on wouldn't be as
fulfilling. woohoo.

The strongest part of the film for me is of course Mary's wardrobe. Please bring
the fashion style of that time and hers specifically. I want to give it a higher
score than 5/10, just for her garderobe, but this feels right to me.

I do like how they portrayed many underrepresented communities and types of people
you meet, as-is. To my point above—this is what my university was like. So it's not
necessarily "diverse," but real.

Yes, I've read [[https://archive.ph/20200608135245/https://www.wsj.com/articles/party-girl-oral-history-parker-posey-11591621366][WSJ's piece]] on it. To make something like this on a shoestring
budget of $150k in 1995?! I could get into it as a cult film in the future if I
decide to rewatch!

{{{two}}}
