* Komi-san wa, Komyushō Desu 🥑

I had the pleasure to watch the anime adaptation of /Komi Can't
Communicate/. First of all, I have to say that I absolutely loved it. It's on
[[https://www.netflix.com/title/81228573][Netflix]], so go check it out! This review will be succinct, you will see why.

Starting the show was a little rough for me. For whatever reason, the first
couple of episodes were something I just had to get myself through, hoping that
it hooks me better along the way. The beginning feels a little boring, due to
largely us not being well acquainted with Tadano Hitohito and Komi Shouko. We're
thrown into this wild high school life, where everyone is almost a caricature of
a specific persona type.

And you know what? *I adore it.* There is a weak spot in me for the Slice of Life
kind of shows and feelings. One of my favorite parts of Neon Genesis Evangelion
is the one with the [[https://youtu.be/Vk2g-2tC5qM][alternate reality]], which is just so (not) wholesome. Komi
definitely struck that beautiful note of having a lightweight and simply
endearing atmosphere.

Shouko has one single purpose and that is to make 100 friends. Hitohito is her
classmate that sincerely wants to help her. Interestingly, all done without an
inherited romantic ploy to get to her. I can go on describing small moments I
enjoyed, but that would border on retelling the story, so it would be better for
you to read the manga or watch the show.

Finally, I need to say that my favorite character is Osana Najimi. She has good
energy, good vibes. Well, he? she? They prefer anything and canonically, their
gender is simply "Najimi". Thanks to her incredible communication skills and
pure talent, she is the complete polar opposite of Komi. There is something
about Najimi-chan whom I utmost admire. It's the positive energy and sincerity
with people that matter to her/him. 

Most importantly...

*I live for Osana Najimi.*

I am obsessed with good YT edits, so please enjoy some of them below.

YOUTUBE Cy-LWx3-Mmw

YOUTUBE x5YqmvwcFR8

YOUTUBE 0r9JuDz-OzE

YOUTUBE jIl6PHT6jww

YOUTUBE Z1unSE8VEQc

YOUTUBE BwGFrPspArA

YOUTUBE CDuNr-nx76g

YOUTUBE e_rY2di38Is

YOUTUBE 1Ev6vOgSCbI

YOUTUBE QXwlge4a_s4

YOUTUBE OTEfMinT3hE

YOUTUBE ksNFqxv1iro

/Najimi Osana adapts to things./
