#+setupfile: ../00_film_skipthis.org
#+date: 223; 12025 H.E.
* Anora
I was a little surprised to see the movie that I had just seen airing in my
local movie theaters to get mentioned as a new /Criterion/ physical release in one
of their emails I get every now and then. Having a fresh movie off the press
like that getting a physical copy must serve as some sort of a strong-ish signal
of its relative quality. Especially with all the buzz from its numerous awards
and nominations, I realized there is no better way to experience it than on my
eight hour long flight from Chicago to Frankfurt in Boeing B747-8's Economy
Class.

Having had a chance to reflect on /Anora/ over the past month or so, I think it's
pretty alright. The one scene that I think about is where the glamour of her
life in the club is sharply contrasted with her walking back home early in the
morning wearing a persona so different from what we have seen before. The
abundance of ``raw'' scenes involving sex, screaming, layered dialogues,
etc. lost their allure the more they threw them at my face. The whole chase
scene with Armenians and Russians was more appropriate for a Scooby-Doo episode,
since losing their momentum they had in the beginning, they lost the point that
got me hooked in the beginning.

{{{three}}}
