#+setupfile: ../00_film_skipthis.org
#+date: 273; 12025 H.E. 2359
* A Minecraft Movie
/Minecraft Movie/ is probably one of the worst movies I have ever had the
displeasure of seeing. It's just straight-up bad, man. I studied films in
college, took classes, even did a whole graduate-level course on trash films
like /Asylum/, John Waters, Sharknado, etc., but they all had a charm to
eat---they were campy, they had /something/ to say, they tried so desperately to
be something that they weren't resulting in a product that genuine. /Minecraft
Movie/ is the polar opposite of it all, as it lacks any kind of substance, soul,
purpose, and worst of all, for its kind, it lacks entertainment.

When thinking of what to give this movie on my made-up scale of ``goodness,'' I
thought to myself that giving it two out of five is a solid mark, since the end
product, that is, a /primarily/ and /only/ a /commercial/ product, is mediocre to its
core. Unfortunately, I had found an /Extras/ tab in my HBO app, which presented a
15-minute long documentary on the making of the movie. I'm always here for a
good documentary and behind-the-scenes scoop, which usually gives me more
appreciation for the production side of things.

I am sad to report that my respect for the creators and whoever had the final
say had deteriorated to levels hard to imagine. Seeing all the work that had
been poured into the project, ranging from inviting seasoned game veterans to
building real-life props and iterating on them for many months to find that
perfect representation for them---only for all of that effort to go unnoticed
and essentially, ignored.

I wouldn't leave you without an example. In the scene of Steve's secret dungeon,
where the characters would build their weapons and stuff, the documentary showed
how each shelf was stacked with unique items from all over the game, built with
care and love, full of references to any corners of the game. The final movie
cut glanced over all of it, only to focus our attention on the boy making his
tater tot gun, promptly leading the whole squad leaving the building pronto.

In that time, one should ask themselves, ``what was the point of all the prop
work?'' Worst of all, whenever it /did/ appear for a split second in the
background, I was fully convinced it was green screened, so I have disregarded
it mentally almost immediately. In contrary, imagine when they were just about
to enter the scene of the secret stash, we had a few camera angles from
different shooting spots of the shelves and interior, giving us appreciation not
only for the production designers' efforts, but in the story, for how
well-traveled Steve really is, since he was able to collect all of the rare loot
and items that gamers could appreciate.

It is getting the lowest possible rating from me for the totally missing the
mark in making the movie /even/ entertaining and wasting the potential they had
for free with the IP and stafff assigned.

{{{one}}}
