= Installing Glorious Arch Linux =
Sagindyk Urazayev <thecsw@ku.edu>
LinkedIn_LINK | GitHub_LINK | Resume_LINK | PGP Key_LINK | Home_LINK

== Pre-Installation ==

Open the
https://www.archlinux.org/[Arch Linux Official Website]
and download the latest image file. Later on just take a flash drive and burn it
with `rufus` on Windows or with `dd` on Linux.

== Installation ==

=== BIOS and Flash Drive ===

==== BIOS Configuration ====

This part is quite easy. The only thing that you should do is to tell
your BIOS to boot from Flash Drives instead of bootloader and other
drives.
This process is different for every BIOS Version and motherboard,
however, this is really easy as all the entries in the BIOS menu are
self-explanatory.

==== Flash Drive ====

Just plug in your flash drive and power on/reboot your device.

Now you will see a systemd prompt asking to boot. Choose the boot option
that includes Arch Linux in it.

 Root on archios

Now you will see a promtpt that looks like this.

```
root@archios
```

Everything is going very well. Now, this guide includes Arch Linux
installation without dual boot. So suppose that Arch Linux is the only
Operating System on your device. If you want to go with dual boot with
Windows or other OS. Refer to another guide or do it at your own risk.

### Verify the boot mode (OPTIONAL)

If you see a bunch of files when running this command, then everything is OK

```
ls /sys/firmware/efi/efivars
```

### Connecting to internet (OPTIONAL)

If you have an Ethernet connection, you may skip this step. If you are trying
to install Arch Linux on a laptop, please use `wifi-menu` to connect to a wifi
point.

### Disk Partitioning

Okay, now we need to partition our hard/state drive. How do we do that?
Actually, there are many ways to to it, however I prefer to use `cfdisk`.
It has pseudo-GUI, which is easier to work and operate with. Before
partitioning, we should find the name of your drive. For that, in your
command line type.

```
fdisk -l
```

You will see a list of available storages. Ignore everything that ends
with: boot, root, include, etc. What you are interested in is the
biggest available drive. For example, my laptop has integrated SD Card
27GB and it is called `/dev/mmcblk0`.
For the sake of simplicity, let's use notation `/dev/sda` for the name of
the drive.
Okay, good. Now, launch `cfdisk` by typing

```
cfdisk -z /dev/sda
```

You will enter pseudo-GUI interface. Select **gpt** and now you will see
your drive's partitions. Next, we need to create 3 partitions: `EFI
System(/dev/sda1)`, `Swap memory(/dev/sda2)` and `Root Directory
(x86\_64)(/dev/sda3)`. I don't create home partitions, as I just don't
like it.

By the rules, your swap should be 2xRAM and EFI System 512MB. Everything
else can be given to Root Directory. Now, exit cfdisk by choosing QUIT.

### Formatting partitions

We need to format partitions appropriately and accordignly.
Your EFI System should be FAT32 formatted, because we use systemd-boot.
To do that, type

```
mkfs.fat -F32 /dev/sda1
```

Your swap partition should be formatted as swap memory (obviously)

```
mkswap /dev/sda2
swapon /dev/sda2
```

Your main directory should be formatted as ext4, so to use all your
files further on

```
mkfs.ext4 /dev/sda3
```

Very good, our partitions are properly formatted and we can go on.

## Mounting

Now, we should mount our partitions. Firstly, we should mount our root
partition

```
mount /dev/sda3 /mnt
```

Then, we should mount the EFI System, so the system would know where is
the boot point. We also need to create boot directory on our own.

```
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
```

Awesome, everything is mounted, now we can start installing the system!

## Installing the actual OS

### Finding fast mirrors

This part is quite easy. However, when I was installing my system, I had
a problem with downloading speed, it was something like 20-50KB/s.
Awful. To fix that and get the maximum download speed, do the following:

```
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.backup
rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
```
Now you will be connected to the fastest mirrors in your location.
Hurray!

### Pacstrap

Now we will install the base system. Here, we will intall base and
base-devel packages, because it will get us enough packages to start
using Arch Linux.

```
pacstrap /mnt base base-devel
```

### Genfstab

Now, the system is installed on the device and we need to tell our OS
and Bootloader about the partitions of our disk. To do so, perform:

```
genfstab -U /mnt >> /mnt/etc/fstab
```

CHECK THE `/mnt/etc/fstab` FOR ANY CORRUPTIONS!!!
