name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo hello
