#+options: tomb:nil toc:nil preview-height:2256 preview-width:1496
#+date: 224; 12023 H.E.
* The drive-thru challenge 🍔

On August 5th, 12023 H.E., my two best friends and I did the
[[https://knowyourmeme.com/memes/dougdoug-fast-food-drive-thru-challenge][DougDoug Fast-Food Drive-Thru Challenge]] that involves

#+begin_quote
driving to 10 different fast food places and ordering the food that the car in
front of you has ordered, then completing their order while driving to the next
location and attempting to consume all the food within a set amount of time.
#+end_quote

** The rules
Usually, you would have 4 fighters going to 10 places. A couple of requirements
apply:

- Maximum of 1 drink place
- Maximum of 1-2 dessert places
- Maximum of 1 repeat place (can't circle around Starbucks, for example)
- *Have to go to KFC* because the value basket might end your run.

However, we did it /for the love of the game/ and there were only 3 of us. So,
considering the average consumption per person is 5-6k calories
[fn:: Ludwig did the challenge, which inspired us to try it out as well. The
yard cast, the four of them ended up collectively consuming 17,385 calories.
[[https://youtu.be/0G8kYMaiGZI][Ludwig's YouTube video]]]
, we decided to roll up to 5 places and test our luck.

I will rely on [[https://www.menuwithnutrition.com/][MenuWithNutrition]] to tell me our caloric intake based on what we
end up getting from each one of our stops. Pretty cool website, I must say. It
just popped up as the first search result for ``KFC calories.'' Each meal will
have the caloric intake and the CPF (Carbs, Protein, Fat) percentage in that order.

** First stop: /KFC/

Because KFC is a required drive-thru to hit, I thought, ``Well, if we end up
with a big family basket---the run is as good as over.'' We will try it as the
first place, such that if we lose---we lose fast and ingloriously. But little
did we know what Fast Food Gods had in store for us.

We pulled up to the drive-thru, last time having shared KFC for New Year's or
previous Thanksgiving (don't remember, there was another meme we did)---the car
in front of us looked to be a regular-looking car and all they had was:
twenty-ish nuggets and two biscuit+coleslaw. My friends---*this is an absolute
win*. Only costs about $22.05.

So, here is the breakdown of the two combos we got.

- 2×12 /Nuggets/ = 2×620 Cal = 1240 Cal ^{{| C:25%, P:17%, F:58%}}
- 2×1 /Coleslaw/ = 2×170 Cal = 340 Cal ^{{| C:34%, P:1%, F:65%}}
- 2×1 /Biscuit/ = 2×180 Cal = 360 Cal ^{{| C:50%, P:9%, F:41%}}
- 2×1 /20 fl oz Mountan Dew/ = 2×270 = 540 Cal ^{{| C:100%}}
- *Total:* 2480 Calories ^{{/chuckle, we're in danger/}}

Even with a whole day's worth of calories (I on average consume <1000 Cal), I
would still consider our first stop to have set us on a world-record pace. It
was also /really/ good. Probably the best KFC I have had in years. Now, it's time
to go to the most famous and misunderstood real estate company in the world.

** Second stop: /Stinky Don/

We could not *not go* to /McDonald's/. The word ``Fast Food'' and /McDonald's/ are
forever ethereally linked between and to each other. I have not personally gone
to the chain for about 2-3 years. Just had a really bad experience once, which
dissuaded me from ever craving that BigMac (meh) or fries again. But hey, aren't
we doing this for the /love of the game/?! Yet again, we could not have predicted
what is yet to transpire.

As usual (we're battle-hardened now), we rolled in to the drive-thru, ``Uhm, hi,
so... we have a bit of a strange request---can we order whatever the car in
front of us had? ... Yeah, just the same thing. *Don't care what they had---I'll
have it too*'' And we really had to do it, as the big F-150 in front of us
looked rather daunting when it comes to a regular's order of stinky don.

``Brace yourselves, brothers.''---*huh*. A /single/ order of Double Quarter Pounder
with Cheese?! (In France they call it, /Royale with Cheese/
[fn:: As Vincent (/Pulp Fiction/) said, ``No, they got the metric system there,
they wouldn't know what the fuck a Quarter Pounder is.'']
). Phew. Okay. We have been /savee/---

``*Jame*. What is /this/? Why did we just get handed over 3 bags full of
McDonald's food and immediately saluted goodbye to?'' Oh. Ohhh. They gave us
the *wrong* order. Instead of getting a single meal, to which we paid exactly
$10.35 for, we have just received a hundred dollars worth of lab goo, including:
6 double cheeseburgers, 40 Chicken McNuggets, 6 large fries, and 2
radioactive-looking drinks. Did we just rob a family or a kid's birthday party
of their food? Well, the staff doesn't seem to want their food back either
(they'll just remake it).

On any given McDonald's day---this would be fantastic news. However, this is
detrimental to our current world-pace record drive-thru speedrun. So, if we
recall the ancient texts from /KnowYourMeme/,

#+begin_quote
driving to 10 different fast food places and ordering the food that the car in
front of you has ordered, then *completing their order* while driving to the next
location and attempting to consume all the food within a set amount of time.
#+end_quote

/Technically/ speaking, ``their'' order was a single /Royale with Cheese/ meal and
*not* the Last Supper we got by mistake. So, I agreed to wolf down the burger,
which I must say---was freaking *delicious*. Maybe I haven't had a good McDonald's
or it's been a while, but it was unironically /really/ good. The calorie count for
what we consumed this time was:

- /Double Cheeseburger/ = 450 Cal ^{{| C:30%, P:22%, F:48%}}
- /French Fries, large/ = 460 Cal ^{{| C:53%, P:5%, F:42%}}
- /Diet Coke, medium/ = 0 Cal
- *Total*: 910 Cal

Not so bad if I do say so myself... One of us ended up taking the
non-eligible-for-the-competition-food back home.

#+begin_details what if we ate the wrong order?
- 6×1 /Double Cheesburger/ = 2700 Cal ^{{| C:30%, P:22%, F:48%}}
- /Chicken McNuggets, 40 Piece/ = 1660 Cal ^{{| C:25%, P:22%, F:53%}}
- 6×1 /French Fries, large/ = 2760 Cal ^{{| C:53%, P:5%, F:42%}}
- 6×1 /Diet Coke, medium/ = 0 Cal
- *Total*: *7120 Cal*

yeah... *no.*
#+end_details

** Third stop: /Dunkin'/

After the garfunkle with /McDonald's/, it's time to visit our first drink/dessert
(the line has become beyond blurry here) place, because why not? I'm craving for
something /sweeeet/. 

A beaten-up family-style Ford in front of us had at least 5-6 people cruising
together, which made us realize---our streak of luck might finally come to an
end here. And /Dunkin'/ ain't such a bad spot to fold.

It especially came to a scare, when the lady started aggressively and audibly
pressing some buttons on her keyboard, emitting 10 beeps per second, which led
me to assume she was paging through the previous order.

Surprisingly enough, they ordered almost /nothing/. All we got after =std::copy='ing
their order were:

- /Double Espresso/ = 10 Cal ^{{| C:100%}}
- 2×1 /Double Chocolate Donut/ = 740 Cal ^{{| C:43%, P:4%, F:53%}}
- *Total*: 750 Cal

/Again.../ not bad. Though I did feel bad for Jame, who just finished a big gulp
of Mountain Dew from /KFC/ and downed the double espresso from /Dunkin'/. To say the
least, he was *wired in*.

** Fourth stop: /Taco Bell/

This was just /nasty/. Someone in font of us ordered five Chicken Chipotle melts
drowned in what I presume to be Sriracha? Not a graet experience through and
through. It was shocking that as I'm the lightest and most dystrophic-looking
guy, ate the most out of the pool. One of us had to chow down the whole thing.

Oh, and yeah. This order had no drinks. Turned out to be $13.61.

- 5×1 /Chicken Chipotle Melt/ = 950 Cal ^{{| C:32%, P:25%, F:43%}}
- *Total*: 950 Cal

** Fifth stop: /Starbucks/

Last but not least---/bux/. The lady very politely, almost between-the-lines,
yelled at us with, ``Are you *sure* you want the previous order?'' It's the last
stop, we have other things to do tonight, so let's get this over with. ``Yeah,
please, we'll have whatever the customer in front of us had!''

It. Was. A. Single. Iced. Pink. Drink. with coconut milk. I've got a picture
where we all drink it together with separate straws. It's *real romantic*, but I
don't feel like putting it here.

- /Iced Pink Drink/ = 105 Cal ^{{| C:80%, P:3%, F:17%}}
- *Total*: 105 Cal

I guess... we got off real easy on this one. Haven't we?

** Speedrun results

From the first receipt from /KFC/ at 5:37 PM, finishing with the last /Starbucks/
receipt closed on 6:52 PM and 5195 consumed calories (~1732 calories per
person)---this turned out to be *great success*! And one of the least expensive
hangouts we've had in a while (we venmoed like $20 per person). I was still
hungry later that evening, so there was enough room for a full dinner with
proper nutrition.
