{{{film}}}
#+date: 37; 12026 H.E. 0939
* Chloe
The premise of hiring a callgirl to seduce your husband that you suspect of
cheating, of say confronting him about it is a tough sell. Add on top all the
times the movie's writing hammered how good they were and still are as a couple,
then the primary tension has weak legs to stand on. The final twist still pays
off, somewhat, even if the viewer can see it coming from a mile away, but
ultimately, deflated with the lackluster series of events that have no rhyth
nor rhyme, as the sole saving grace the director was banking one were the nude
shots of Amanda Seyfried, which helped, but not nearly enough to save the plot
from itself. There is little to say about Julianne Moore, as she plays these
sorts of roles somewhat often, say in /The Big Lebowski/ or /Boogie Nights/ or /Don
Jon/, to name a few. /Chloe/ herself, the titular character, who the movie is named
after, has just one job of looking hot, telling juicy stories of how she had a
good time with (also hot) Liam Neeson, strip naked, and repeat this sequence
exactly about seven or eight times to pad the runtime. There is nothing for the
writers to tell us about her or anything that survives the shallowest of
scratches, resulting in their big star getting reduced to that of a movie prop.

{{{two}}}
